# Generated by GitHub Copilot - Aug-28-2026
from datetime import UTC, datetime
from typing import Annotated

from fastapi import APIRouter, Cookie, Depends, Response, status
from pydantic import BaseModel, Field, field_validator
from sqlalchemy import func, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.orm import Session

from api_errors import ApiHTTPException
from auth import (
    DUMMY_PASSWORD_HASH,
    SESSION_COOKIE_NAME,
    SESSION_COOKIE_SECURE,
    SESSION_MAX_AGE_SECONDS,
    create_session_token,
    hash_password,
    read_session_token,
    verify_password,
)
from database import get_db
from models import Account

router = APIRouter(prefix="/api/auth", tags=["authentication"])
NO_STORE_HEADERS = {"Cache-Control": "no-store"}


class RegisterRequest(BaseModel):
    """Validated credentials for creating an Account."""

    username: str = Field(min_length=3, max_length=32)
    password: str = Field(min_length=8, max_length=128)

    @field_validator("username", mode="before")
    @classmethod
    def trim_username(cls, value: object) -> object:
        """Trim surrounding whitespace before enforcing username length."""
        return value.strip() if isinstance(value, str) else value

    @field_validator("username")
    @classmethod
    def reject_control_characters(cls, value: str) -> str:
        """Reject usernames containing control or other non-printable characters."""
        if not value.isprintable():
            raise ValueError("Username must not contain control characters")
        return value


class AccountResponse(BaseModel):
    """Public Account fields safe to return to the browser."""

    id: int
    username: str


class LoginRequest(RegisterRequest):
    """Validated credentials for signing in to an existing Account."""


def _public_account(account: Account) -> AccountResponse:
    """Map a database Account to its public representation."""
    return AccountResponse(id=account.id, username=account.username)


def _set_session_cookie(response: Response, account_id: int) -> None:
    """Attach the signed Account session using browser security controls."""
    response.set_cookie(
        key=SESSION_COOKIE_NAME,
        value=create_session_token(account_id),
        max_age=SESSION_MAX_AGE_SECONDS,
        httponly=True,
        secure=SESSION_COOKIE_SECURE,
        samesite="lax",
        path="/",
    )
    response.headers["Cache-Control"] = "no-store"


def get_optional_account(
    database: Annotated[Session, Depends(get_db)],
    session_token: Annotated[str | None, Cookie(alias=SESSION_COOKIE_NAME)] = None,
) -> Account | None:
    """Resolve a valid Account session while allowing anonymous requests."""
    if session_token is None:
        return None
    account_id = read_session_token(session_token)
    return database.get(Account, account_id) if account_id is not None else None


@router.post(
    "/register",
    response_model=AccountResponse,
    status_code=status.HTTP_201_CREATED,
)
def register_account(
    request: RegisterRequest,
    response: Response,
    database: Annotated[Session, Depends(get_db)],
) -> AccountResponse:
    """Create an Account, hash its password, and establish a signed session."""
    normalized_username = request.username.lower()
    existing_account_id = database.scalar(
        select(Account.id).where(func.lower(Account.username) == normalized_username)
    )
    if existing_account_id is not None:
        raise ApiHTTPException(
            status_code=409,
            code="auth_username_taken",
            detail="Username is already registered",
            headers=NO_STORE_HEADERS,
        )

    account = Account(
        username=request.username,
        password_hash=hash_password(request.password),
    )
    database.add(account)
    try:
        database.commit()
    except IntegrityError as error:
        database.rollback()
        raise ApiHTTPException(
            status_code=409,
            code="auth_username_taken",
            detail="Username is already registered",
            headers=NO_STORE_HEADERS,
        ) from error

    database.refresh(account)
    _set_session_cookie(response, account.id)
    return _public_account(account)


@router.post("/login", response_model=AccountResponse)
def login_account(
    request: LoginRequest,
    response: Response,
    database: Annotated[Session, Depends(get_db)],
) -> AccountResponse:
    """Verify Account credentials and establish a signed session."""
    account = database.scalar(
        select(Account).where(func.lower(Account.username) == request.username.lower())
    )
    encoded_hash = account.password_hash if account is not None else DUMMY_PASSWORD_HASH
    credentials_valid = verify_password(request.password, encoded_hash)
    if account is None or not credentials_valid:
        raise ApiHTTPException(
            status_code=401,
            code="auth_invalid_credentials",
            detail="Invalid username or password",
            headers=NO_STORE_HEADERS,
        )

    account.last_login_at = datetime.now(UTC)
    database.commit()
    _set_session_cookie(response, account.id)
    return _public_account(account)


@router.post("/logout")
def logout_account(response: Response) -> dict[str, str]:
    """End the browser session without modifying the Account."""
    response.delete_cookie(
        key=SESSION_COOKIE_NAME,
        httponly=True,
        secure=SESSION_COOKIE_SECURE,
        samesite="lax",
        path="/",
    )
    response.headers["Cache-Control"] = "no-store"
    return {"status": "signed_out"}


@router.get("/me", response_model=AccountResponse)
def get_current_account(
    response: Response,
    account: Annotated[Account | None, Depends(get_optional_account)],
) -> AccountResponse:
    """Reload and return the Account identified by a valid session cookie."""
    response.headers["Cache-Control"] = "no-store"
    if account is None:
        raise ApiHTTPException(
            status_code=401,
            code="auth_required",
            detail="Not authenticated",
            headers=NO_STORE_HEADERS,
        )
    return _public_account(account)