# Generated by GitHub Copilot - Aug-28-2026
import os
from typing import Any

from dotenv import load_dotenv
from itsdangerous import BadSignature, SignatureExpired, URLSafeTimedSerializer
from pwdlib import PasswordHash

load_dotenv()

SESSION_COOKIE_NAME = "hamburg_session"
SESSION_MAX_AGE_SECONDS = 60 * 60 * 24 * 30
SESSION_SALT = "hamburg-whereabouts-account-session-v1"

password_hash = PasswordHash.recommended()
DUMMY_PASSWORD_HASH = password_hash.hash("dummy-password-used-only-for-timing")


def _required_session_secret() -> str:
    """Load a non-placeholder signing secret or fail closed."""
    secret = os.getenv("SESSION_SECRET", "")
    if len(secret) < 32 or secret.startswith("replace-this"):
        raise RuntimeError(
            "SESSION_SECRET must be set to a non-placeholder value of at least 32 characters"
        )
    return secret


def _environment_flag(name: str, default: bool) -> bool:
    """Parse a strict boolean environment setting."""
    raw_value = os.getenv(name)
    if raw_value is None:
        return default
    normalized = raw_value.strip().lower()
    if normalized not in {"true", "false"}:
        raise RuntimeError(f"{name} must be either true or false")
    return normalized == "true"


SESSION_COOKIE_SECURE = _environment_flag("SESSION_COOKIE_SECURE", default=True)
serializer = URLSafeTimedSerializer(_required_session_secret(), salt=SESSION_SALT)


def hash_password(password: str) -> str:
    """Hash a password with pwdlib's recommended Argon2 configuration."""
    return password_hash.hash(password)


def verify_password(password: str, encoded_hash: str) -> bool:
    """Verify a password against an Account's Argon2 hash."""
    return password_hash.verify(password, encoded_hash)


def create_session_token(account_id: int) -> str:
    """Create a signed token containing only the Account identifier."""
    return serializer.dumps({"account_id": account_id})


def read_session_token(token: str) -> int | None:
    """Return the Account identifier from a valid, unexpired session token."""
    try:
        payload: Any = serializer.loads(token, max_age=SESSION_MAX_AGE_SECONDS)
    except (BadSignature, SignatureExpired):
        return None
    if not isinstance(payload, dict):
        return None
    account_id = payload.get("account_id")
    if not isinstance(account_id, int) or isinstance(account_id, bool):
        return None
    return account_id