# Generated by GitHub Copilot - Aug-28-2026
import os
from collections.abc import Generator

from dotenv import load_dotenv
from sqlalchemy import create_engine
from sqlalchemy.engine import make_url
from sqlalchemy.orm import DeclarativeBase, Session, sessionmaker

load_dotenv()

DATABASE_URL = os.environ["DATABASE_URL"]
DATABASE_CONNECT_TIMEOUT_SECONDS = int(
    os.getenv("DATABASE_CONNECT_TIMEOUT_SECONDS", "5")
)
if not 1 <= DATABASE_CONNECT_TIMEOUT_SECONDS <= 30:
    raise RuntimeError("DATABASE_CONNECT_TIMEOUT_SECONDS must be between 1 and 30")

database_url = make_url(DATABASE_URL)
connect_args = (
    {"connect_timeout": DATABASE_CONNECT_TIMEOUT_SECONDS}
    if database_url.drivername.startswith("postgresql")
    else {}
)
engine = create_engine(DATABASE_URL, pool_pre_ping=True, connect_args=connect_args)
SessionLocal = sessionmaker(bind=engine, autoflush=False, expire_on_commit=False)


class Base(DeclarativeBase):
    """Base class for application database models."""


def get_db() -> Generator[Session, None, None]:
    """Yield one database session and always release its connection."""
    with SessionLocal() as session:
        yield session