# Generated by GitHub Copilot - Aug-28-2026
from datetime import date, datetime
from typing import Literal

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from database import Base


class Account(Base):
    """Persistent Player identity with a case-preserving username."""

    __tablename__ = "account"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(32), nullable=False)
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False)
    is_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    daily_games: Mapped[list["GameDailyDistricts"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )
    training_cards: Mapped[list["TrainingCard"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )
    training_attempts: Mapped[list["TrainingAttempt"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )
    training_sessions: Mapped[list["TrainingSession"]] = relationship(
        back_populates="account", cascade="all, delete-orphan"
    )

    __table_args__ = (
        Index("uq_account_username_lower", func.lower(username), unique=True),
    )


class GameDailyDistricts(Base):
    """One Account's server-authoritative attempt at a Daily Challenge."""

    __tablename__ = "game_daily_districts"
    __table_args__ = (
        UniqueConstraint(
            "account_id", "challenge_date", name="uq_game_account_challenge_date"
        ),
        CheckConstraint(
            "budget_remaining BETWEEN 0 AND 10", name="ck_game_budget_range"
        ),
        CheckConstraint(
            "status IN ('in_progress', 'finished')", name="ck_game_status"
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    challenge_date: Mapped[date] = mapped_column(Date, nullable=False)
    budget_remaining: Mapped[int] = mapped_column(Integer, nullable=False, default=10)
    solved_pin_indices: Mapped[list[int]] = mapped_column(
        JSON, nullable=False, default=list
    )
    status: Mapped[Literal["in_progress", "finished"]] = mapped_column(
        String(16), nullable=False, default="in_progress"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    finished_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    finish_reason: Mapped[str | None] = mapped_column(String(16))

    account: Mapped[Account] = relationship(back_populates="daily_games")
    guesses: Mapped[list["Guess"]] = relationship(
        back_populates="game",
        cascade="all, delete-orphan",
        order_by="Guess.id",
    )


class Guess(Base):
    """One accepted Guess belonging to a persistent Account Game."""

    __tablename__ = "guess"

    id: Mapped[int] = mapped_column(primary_key=True)
    game_id: Mapped[int] = mapped_column(
        ForeignKey("game_daily_districts.id", ondelete="CASCADE"), nullable=False
    )
    guessed_district_id: Mapped[int] = mapped_column(Integer, nullable=False)
    was_correct: Mapped[bool] = mapped_column(Boolean, nullable=False)
    solved_pin_index: Mapped[int | None] = mapped_column(Integer)
    distance_km: Mapped[float | None] = mapped_column(Float)
    # Exact metric value for leaderboard aggregation; distance_km remains the
    # player-facing, one-decimal value retained for existing history.
    distance_meters: Mapped[float | None] = mapped_column(Float)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    game: Mapped[GameDailyDistricts] = relationship(back_populates="guesses")


class TrainingCard(Base):
    """One Account's review schedule for a District and exercise direction."""

    __tablename__ = "training_card"
    __table_args__ = (
        UniqueConstraint(
            "account_id",
            "district_id",
            "direction",
            name="uq_training_card_account_district_direction",
        ),
        CheckConstraint("stage BETWEEN 0 AND 6", name="ck_training_card_stage"),
        CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_card_direction"
        ),
        Index("ix_training_card_account_due", "account_id", "due_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    district_id: Mapped[int] = mapped_column(Integer, nullable=False)
    direction: Mapped[Literal["name", "find"]] = mapped_column(
        String(8), nullable=False
    )
    stage: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    due_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    shelved: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    already_known: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    last_was_correct: Mapped[bool | None] = mapped_column(Boolean)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    account: Mapped[Account] = relationship(back_populates="training_cards")


class TrainingAttempt(Base):
    """One immutable graded Training response."""

    __tablename__ = "training_attempt"
    __table_args__ = (
        CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_attempt_direction"
        ),
        CheckConstraint(
            "outcome IN ('correct', 'incorrect', 'dont_know')",
            name="ck_training_attempt_outcome",
        ),
        Index("ix_training_attempt_account_created", "account_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    district_id: Mapped[int] = mapped_column(Integer, nullable=False)
    direction: Mapped[Literal["name", "find"]] = mapped_column(
        String(8), nullable=False
    )
    outcome: Mapped[Literal["correct", "incorrect", "dont_know"]] = mapped_column(
        String(16), nullable=False
    )
    answered_district_id: Mapped[int | None] = mapped_column(Integer)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )

    account: Mapped[Account] = relationship(back_populates="training_attempts")


class TrainingSession(Base):
    """A server-owned endless Training queue and its session counters."""

    __tablename__ = "training_session"
    __table_args__ = (
        CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_session_direction"
        ),
        CheckConstraint(
            "status IN ('active', 'stopped')", name="ck_training_session_status"
        ),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False
    )
    direction: Mapped[Literal["name", "find"]] = mapped_column(
        String(8), nullable=False
    )
    selected_bezirke: Mapped[list[str]] = mapped_column(JSON, nullable=False, default=list)
    queue_district_ids: Mapped[list[int]] = mapped_column(JSON, nullable=False, default=list)
    recent_district_ids: Mapped[list[int]] = mapped_column(JSON, nullable=False, default=list)
    active_district_id: Mapped[int | None] = mapped_column(Integer)
    last_answer_district_id: Mapped[int | None] = mapped_column(Integer)
    last_answer_correct: Mapped[bool | None] = mapped_column(Boolean)
    attempt_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    correct_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    introduced_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[Literal["active", "stopped"]] = mapped_column(
        String(8), nullable=False, default="active"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    account: Mapped[Account] = relationship(back_populates="training_sessions")


class AnalyticsEvent(Base):
    """One consented, allowlisted product telemetry event."""

    __tablename__ = "analytics_event"
    __table_args__ = (
        Index("ix_analytics_event_occurred_type", "occurred_at", "event_type"),
        Index("ix_analytics_event_visitor", "visitor_id"),
        Index("ix_analytics_event_account", "account_id"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    event_id: Mapped[str] = mapped_column(String(36), unique=True, nullable=False)
    visitor_id: Mapped[str] = mapped_column(String(36), nullable=False)
    account_id: Mapped[int | None] = mapped_column(
        ForeignKey("account.id", ondelete="SET NULL")
    )
    event_type: Mapped[str] = mapped_column(String(40), nullable=False)
    properties: Mapped[dict[str, object]] = mapped_column(JSON, nullable=False, default=dict)
    occurred_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class VisitorAccountLink(Base):
    """Current Account attribution for one consented browser identifier."""

    __tablename__ = "visitor_account_link"

    visitor_id: Mapped[str] = mapped_column(String(36), primary_key=True)
    account_id: Mapped[int] = mapped_column(
        ForeignKey("account.id", ondelete="CASCADE"), nullable=False, index=True
    )
    linked_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )


class AnalyticsDailyAggregate(Base):
    """Non-identifying daily analytics retained after raw event expiry."""

    __tablename__ = "analytics_daily_aggregate"

    day: Mapped[date] = mapped_column(Date, primary_key=True)
    metrics: Mapped[dict[str, object]] = mapped_column(JSON, nullable=False, default=dict)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )