# Generated by GitHub Copilot - Aug-28-2026
from __future__ import annotations

import random
from datetime import UTC, datetime, timedelta
from typing import Annotated, Any, Literal

from fastapi import APIRouter, Depends, HTTPException, Response, status
from pydantic import BaseModel, Field
from sqlalchemy import delete, func, select
from sqlalchemy.orm import Session

from auth_routes import get_optional_account
from database import get_db
from game import District, DistrictCatalog
from models import Account, TrainingAttempt, TrainingCard, TrainingSession

Direction = Literal["name", "find"]
TrainingOutcome = Literal["correct", "incorrect", "dont_know"]
REVIEW_INTERVAL_DAYS = (0, 1, 3, 7, 14, 30, 60)
NO_STORE_HEADERS = {"Cache-Control": "no-store"}


class StartSessionRequest(BaseModel):
    """Validated settings for one endless Training session."""

    direction: Direction
    selected_bezirke: list[str] = Field(min_length=1, max_length=7)


class AnswerRequest(BaseModel):
    """One response to the server-owned active Training question."""

    answer_text: str | None = Field(default=None, max_length=80)
    selected_district_id: int | None = None
    dont_know: bool = False


class CardActionRequest(BaseModel):
    """A reversible Training-card management action."""

    action: Literal["already_known", "shelve", "restore"]


def require_account(
    account: Annotated[Account | None, Depends(get_optional_account)],
) -> Account:
    """Require a valid signed Account for every Training operation."""
    if account is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Sign in to use Training",
            headers=NO_STORE_HEADERS,
        )
    return account


def _normalize_name(value: str) -> str:
    """Normalize official German names without accepting arbitrary typos."""
    normalized = value.strip().lower()
    for source, replacement in (("ä", "ae"), ("ö", "oe"), ("ü", "ue"), ("ß", "ss")):
        normalized = normalized.replace(source, replacement)
    return "".join(character for character in normalized if character.isalnum())


def _as_utc(value: datetime) -> datetime:
    """Normalize timestamps from drivers that omit timezone information."""
    if value.tzinfo is None:
        return value.replace(tzinfo=UTC)
    return value.astimezone(UTC)


def _district_name_index(catalog: DistrictCatalog) -> dict[str, District]:
    """Build the normalized Training answer index from trusted catalog names."""
    return {_normalize_name(district.name): district for district in catalog.districts}


def _validated_scope(
    catalog: DistrictCatalog, selected_bezirke: list[str]
) -> list[str]:
    """Reject duplicate or unknown Bezirk filters before queue generation."""
    available = {district.bezirk for district in catalog.districts}
    selected = set(selected_bezirke)
    if len(selected) != len(selected_bezirke) or not selected.issubset(available):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail="Select one or more valid Bezirke",
            headers=NO_STORE_HEADERS,
        )
    return sorted(selected)


def _scope_districts(
    catalog: DistrictCatalog, selected_bezirke: list[str]
) -> list[District]:
    """Return catalog Districts included in a validated Training scope."""
    selected = set(selected_bezirke)
    return [district for district in catalog.districts if district.bezirk in selected]


def _eligible_districts(
    database: Session,
    catalog: DistrictCatalog,
    account_id: int,
    direction: Direction,
    selected_bezirke: list[str],
) -> list[District]:
    """Apply scope and the Name It introduction gate for Find It."""
    districts = _scope_districts(catalog, selected_bezirke)
    if direction == "name":
        return districts
    introduced_ids = set(
        database.scalars(
            select(TrainingCard.district_id).where(
                TrainingCard.account_id == account_id,
                TrainingCard.direction == "name",
            )
        )
    )
    return [district for district in districts if district.id in introduced_ids]


def _cards_by_district(
    database: Session, account_id: int, direction: Direction
) -> dict[int, TrainingCard]:
    """Load one Account's cards for a direction in a single query."""
    cards = database.scalars(
        select(TrainingCard).where(
            TrainingCard.account_id == account_id,
            TrainingCard.direction == direction,
        )
    )
    return {card.district_id: card for card in cards}


def _build_queue(
    database: Session,
    catalog: DistrictCatalog,
    session: TrainingSession,
) -> list[int]:
    """Order due reviews, unseen items, then useful early reviews."""
    direction: Direction = session.direction
    districts = _eligible_districts(
        database,
        catalog,
        session.account_id,
        direction,
        session.selected_bezirke,
    )
    if not districts:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Practice a Stadtteil in Name It before using Find It",
            headers=NO_STORE_HEADERS,
        )

    district_ids = {district.id for district in districts}
    cards = _cards_by_district(database, session.account_id, direction)
    now = datetime.now(UTC)
    due = sorted(
        (
            card
            for card in cards.values()
            if card.district_id in district_ids
            and not card.shelved
            and _as_utc(card.due_at) <= now
        ),
        key=lambda card: _as_utc(card.due_at),
    )
    unseen = [
        district.id
        for district in districts
        if district.id not in cards
    ]
    random.SystemRandom().shuffle(unseen)
    queue = [card.district_id for card in due] + unseen
    if queue:
        return queue

    early = sorted(
        (
            card
            for card in cards.values()
            if card.district_id in district_ids and not card.shelved
        ),
        key=lambda card: (card.stage, _as_utc(card.due_at)),
    )
    return [card.district_id for card in early]


def _question_payload(
    catalog: DistrictCatalog, session: TrainingSession, district_id: int
) -> dict[str, Any]:
    """Expose only the prompt fields needed by the active direction."""
    district = catalog.by_id[district_id]
    return {
        "session_id": session.id,
        "direction": session.direction,
        "district_id": district.id,
        "prompt_name": district.name if session.direction == "find" else None,
        "bezirk": district.bezirk if session.direction == "find" else None,
        "attempt_count": session.attempt_count,
        "correct_count": session.correct_count,
    }


def _next_question(
    database: Session,
    catalog: DistrictCatalog,
    session: TrainingSession,
) -> dict[str, Any]:
    """Return the active question idempotently or advance the server queue."""
    if session.status != "active":
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Training session has stopped",
            headers=NO_STORE_HEADERS,
        )
    if session.active_district_id is not None:
        return _question_payload(catalog, session, session.active_district_id)

    queue = list(session.queue_district_ids)
    if not queue:
        queue = _build_queue(database, catalog, session)
    if not queue:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="No Stadtteile are available in this scope",
            headers=NO_STORE_HEADERS,
        )

    district_id = queue.pop(0)
    session.queue_district_ids = queue
    session.active_district_id = district_id
    session.recent_district_ids = [
        *session.recent_district_ids[-2:],
        district_id,
    ]
    database.commit()
    return _question_payload(catalog, session, district_id)


def _card_for_answer(
    database: Session,
    account_id: int,
    district_id: int,
    direction: Direction,
    now: datetime,
) -> tuple[TrainingCard, bool]:
    """Load or initialize the review card created by a first graded answer."""
    card = database.scalar(
        select(TrainingCard).where(
            TrainingCard.account_id == account_id,
            TrainingCard.district_id == district_id,
            TrainingCard.direction == direction,
        )
    )
    if card is not None:
        return card, False
    card = TrainingCard(
        account_id=account_id,
        district_id=district_id,
        direction=direction,
        stage=0,
        due_at=now,
        shelved=False,
        already_known=False,
    )
    database.add(card)
    return card, True


def _grade_answer(
    catalog: DistrictCatalog,
    session: TrainingSession,
    request: AnswerRequest,
) -> tuple[TrainingOutcome, int | None]:
    """Grade a direction-specific answer against the active District."""
    target_id = session.active_district_id
    if target_id is None:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Request the next Training question first",
            headers=NO_STORE_HEADERS,
        )
    if request.dont_know:
        if request.answer_text is not None or request.selected_district_id is not None:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Don’t Know cannot include another answer",
                headers=NO_STORE_HEADERS,
            )
        return "dont_know", None

    if session.direction == "name":
        if request.answer_text is None or request.selected_district_id is not None:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Name It requires one typed answer",
                headers=NO_STORE_HEADERS,
            )
        answered = _district_name_index(catalog).get(_normalize_name(request.answer_text))
        answered_id = answered.id if answered is not None else None
    else:
        if request.selected_district_id is None or request.answer_text is not None:
            raise HTTPException(
                status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                detail="Find It requires one selected Stadtteil",
                headers=NO_STORE_HEADERS,
            )
        if request.selected_district_id not in catalog.by_id:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail="Selected Stadtteil was not found",
                headers=NO_STORE_HEADERS,
            )
        answered_id = request.selected_district_id
    return ("correct" if answered_id == target_id else "incorrect"), answered_id


def _category(card: TrainingCard) -> str:
    """Translate scheduler state into learner-facing mastery language."""
    if card.shelved:
        return "shelved"
    if card.last_was_correct is False:
        return "needs_practice"
    if card.stage <= 2:
        return "learning"
    if card.stage <= 4:
        return "familiar"
    return "known"


def _progress_payload(
    database: Session, catalog: DistrictCatalog, account_id: int
) -> dict[str, Any]:
    """Aggregate compact overall, per-mode, and per-card Training progress."""
    cards = list(
        database.scalars(
            select(TrainingCard)
            .where(TrainingCard.account_id == account_id)
            .order_by(TrainingCard.direction, TrainingCard.district_id)
        )
    )
    now = datetime.now(UTC)
    attempt_count = database.scalar(
        select(func.count(TrainingAttempt.id)).where(
            TrainingAttempt.account_id == account_id
        )
    ) or 0
    correct_count = database.scalar(
        select(func.count(TrainingAttempt.id)).where(
            TrainingAttempt.account_id == account_id,
            TrainingAttempt.outcome == "correct",
        )
    ) or 0

    directions: dict[str, dict[str, int | float]] = {}
    for direction in ("name", "find"):
        direction_cards = [card for card in cards if card.direction == direction]
        direction_attempts = database.scalar(
            select(func.count(TrainingAttempt.id)).where(
                TrainingAttempt.account_id == account_id,
                TrainingAttempt.direction == direction,
            )
        ) or 0
        direction_correct = database.scalar(
            select(func.count(TrainingAttempt.id)).where(
                TrainingAttempt.account_id == account_id,
                TrainingAttempt.direction == direction,
                TrainingAttempt.outcome == "correct",
            )
        ) or 0
        directions[direction] = {
            "attempts": direction_attempts,
            "correct": direction_correct,
            "accuracy": round(direction_correct / direction_attempts * 100, 1)
            if direction_attempts
            else 0,
            "practiced": len(direction_cards),
            "due": sum(
                not card.shelved and _as_utc(card.due_at) <= now
                for card in direction_cards
            ),
        }

    card_lookup = {(card.district_id, card.direction): card for card in cards}
    items: list[dict[str, Any]] = []
    for district in catalog.districts:
        name_card = card_lookup.get((district.id, "name"))
        find_card = card_lookup.get((district.id, "find"))
        if name_card is None and find_card is None:
            continue
        items.append(
            {
                "district_id": district.id,
                "name": district.name,
                "bezirk": district.bezirk,
                "name_category": _category(name_card) if name_card else "not_seen",
                "find_category": _category(find_card) if find_card else "not_seen",
                "fully_known": bool(
                    name_card
                    and find_card
                    and not name_card.shelved
                    and not find_card.shelved
                    and name_card.stage == 6
                    and find_card.stage == 6
                ),
            }
        )
    return {
        "attempts": attempt_count,
        "correct": correct_count,
        "accuracy": round(correct_count / attempt_count * 100, 1)
        if attempt_count
        else 0,
        "practiced": len({card.district_id for card in cards}),
        "fully_known": sum(item["fully_known"] for item in items),
        "directions": directions,
        "items": items,
    }


def create_training_router(catalog: DistrictCatalog) -> APIRouter:
    """Create Training routes over the shared in-memory District catalog."""
    router = APIRouter(prefix="/api/training", tags=["training"])

    @router.get("/bootstrap")
    def bootstrap_training(
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Return public Training geometry and the signed Account's progress."""
        response.headers.update(NO_STORE_HEADERS)
        return {
            "districts": [
                {
                    "id": district.id,
                    "name": district.name,
                    "bezirk": district.bezirk,
                    "boundary": district.boundary,
                }
                for district in catalog.districts
            ],
            "bezirke": sorted({district.bezirk for district in catalog.districts}),
            "progress": _progress_payload(database, catalog, account.id),
        }

    @router.get("/progress")
    def get_training_progress(
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Return the current Account's aggregate Training progress."""
        response.headers.update(NO_STORE_HEADERS)
        return _progress_payload(database, catalog, account.id)

    @router.post("/sessions", status_code=status.HTTP_201_CREATED)
    def start_training_session(
        request: StartSessionRequest,
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Stop stale sessions and start a new endless Training queue."""
        response.headers.update(NO_STORE_HEADERS)
        selected_bezirke = _validated_scope(catalog, request.selected_bezirke)
        database.execute(
            select(TrainingSession)
            .where(
                TrainingSession.account_id == account.id,
                TrainingSession.status == "active",
            )
            .with_for_update()
        )
        active_sessions = database.scalars(
            select(TrainingSession).where(
                TrainingSession.account_id == account.id,
                TrainingSession.status == "active",
            )
        )
        now = datetime.now(UTC)
        for active_session in active_sessions:
            active_session.status = "stopped"
            active_session.ended_at = now
        session = TrainingSession(
            account_id=account.id,
            direction=request.direction,
            selected_bezirke=selected_bezirke,
            queue_district_ids=[],
            recent_district_ids=[],
            status="active",
        )
        database.add(session)
        database.flush()
        session.queue_district_ids = _build_queue(database, catalog, session)
        database.commit()
        return _next_question(database, catalog, session)

    @router.post("/sessions/{session_id}/next")
    def next_training_question(
        session_id: int,
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Advance to the next question after feedback acknowledgment."""
        response.headers.update(NO_STORE_HEADERS)
        session = database.scalar(
            select(TrainingSession)
            .where(
                TrainingSession.id == session_id,
                TrainingSession.account_id == account.id,
            )
            .with_for_update()
        )
        if session is None:
            raise HTTPException(status_code=404, detail="Training session not found")
        return _next_question(database, catalog, session)

    @router.post("/sessions/{session_id}/answer")
    def answer_training_question(
        session_id: int,
        request: AnswerRequest,
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Grade one active question and update its review schedule atomically."""
        response.headers.update(NO_STORE_HEADERS)
        session = database.scalar(
            select(TrainingSession)
            .where(
                TrainingSession.id == session_id,
                TrainingSession.account_id == account.id,
                TrainingSession.status == "active",
            )
            .with_for_update()
        )
        if session is None:
            raise HTTPException(status_code=404, detail="Active Training session not found")
        target_id = session.active_district_id
        outcome, answered_id = _grade_answer(catalog, session, request)
        if target_id is None:
            raise HTTPException(status_code=409, detail="No active Training question")

        now = datetime.now(UTC)
        direction: Direction = session.direction
        card, created = _card_for_answer(
            database, account.id, target_id, direction, now
        )
        correct = outcome == "correct"
        if correct:
            card.stage = min(card.stage + 1, 6)
            card.due_at = now + timedelta(days=REVIEW_INTERVAL_DAYS[card.stage])
        else:
            card.stage = 0
            card.due_at = now
            queue = list(session.queue_district_ids)
            queue.insert(min(3, len(queue)), target_id)
            session.queue_district_ids = queue
        card.last_was_correct = correct
        session.active_district_id = None
        session.last_answer_district_id = target_id
        session.last_answer_correct = correct
        session.attempt_count += 1
        session.correct_count += int(correct)
        if created and direction == "name":
            session.introduced_count += 1
        database.add(
            TrainingAttempt(
                account_id=account.id,
                district_id=target_id,
                direction=direction,
                outcome=outcome,
                answered_district_id=answered_id,
            )
        )
        database.commit()

        target = catalog.by_id[target_id]
        selected = catalog.by_id.get(answered_id) if answered_id is not None else None
        return {
            "correct": correct,
            "outcome": outcome,
            "answer": {
                "district_id": target.id,
                "name": target.name,
                "bezirk": target.bezirk,
                "boundary": target.boundary,
            },
            "selected": {
                "district_id": selected.id,
                "name": selected.name,
                "boundary": selected.boundary,
            }
            if selected is not None
            else None,
            "stage": card.stage,
            "due_at": card.due_at,
            "session": {
                "attempts": session.attempt_count,
                "correct": session.correct_count,
                "introduced": session.introduced_count,
            },
        }

    @router.post("/sessions/{session_id}/stop")
    def stop_training_session(
        session_id: int,
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Stop without grading an unanswered active question."""
        response.headers.update(NO_STORE_HEADERS)
        session = database.scalar(
            select(TrainingSession).where(
                TrainingSession.id == session_id,
                TrainingSession.account_id == account.id,
            )
        )
        if session is None:
            raise HTTPException(status_code=404, detail="Training session not found")
        if session.status == "active":
            session.status = "stopped"
            session.active_district_id = None
            session.ended_at = datetime.now(UTC)
            database.commit()
        return {
            "attempts": session.attempt_count,
            "correct": session.correct_count,
            "accuracy": round(session.correct_count / session.attempt_count * 100, 1)
            if session.attempt_count
            else 0,
            "introduced": session.introduced_count,
            "needs_practice": len(
                {
                    attempt.district_id
                    for attempt in database.scalars(
                        select(TrainingAttempt).where(
                            TrainingAttempt.account_id == account.id,
                            TrainingAttempt.created_at >= session.created_at,
                            TrainingAttempt.outcome != "correct",
                        )
                    )
                }
            ),
        }

    @router.post("/cards/{direction}/{district_id}")
    def manage_training_card(
        direction: Direction,
        district_id: int,
        request: CardActionRequest,
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> dict[str, Any]:
        """Mark a demonstrated answer known or change reversible shelf state."""
        response.headers.update(NO_STORE_HEADERS)
        if district_id not in catalog.by_id:
            raise HTTPException(status_code=404, detail="Stadtteil not found")
        card = database.scalar(
            select(TrainingCard).where(
                TrainingCard.account_id == account.id,
                TrainingCard.district_id == district_id,
                TrainingCard.direction == direction,
            )
        )
        if card is None:
            raise HTTPException(status_code=404, detail="Training card not found")
        if request.action == "already_known":
            latest_attempt = database.scalar(
                select(TrainingAttempt)
                .where(
                    TrainingAttempt.account_id == account.id,
                    TrainingAttempt.district_id == district_id,
                    TrainingAttempt.direction == direction,
                )
                .order_by(TrainingAttempt.id.desc())
                .limit(1)
            )
            if latest_attempt is None or latest_attempt.outcome != "correct":
                raise HTTPException(
                    status_code=409,
                    detail="Answer correctly before marking a Stadtteil known",
                )
            card.stage = 6
            card.due_at = datetime.now(UTC) + timedelta(days=60)
            card.already_known = True
            card.last_was_correct = True
        elif request.action == "shelve":
            card.shelved = True
        else:
            card.shelved = False
            card.due_at = datetime.now(UTC)
        database.commit()
        return _progress_payload(database, catalog, account.id)

    @router.delete("", status_code=status.HTTP_204_NO_CONTENT)
    def reset_training_progress(
        response: Response,
        database: Annotated[Session, Depends(get_db)],
        account: Annotated[Account, Depends(require_account)],
    ) -> None:
        """Delete only the signed Account's Training state and history."""
        response.headers.update(NO_STORE_HEADERS)
        database.execute(
            delete(TrainingAttempt).where(TrainingAttempt.account_id == account.id)
        )
        database.execute(
            delete(TrainingCard).where(TrainingCard.account_id == account.id)
        )
        database.execute(
            delete(TrainingSession).where(TrainingSession.account_id == account.id)
        )
        database.commit()

    return router