# Generated by GitHub Copilot - Aug-28-2026
import os
from collections.abc import Generator

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine, delete
from sqlalchemy.orm import Session, sessionmaker
from sqlalchemy.pool import StaticPool

os.environ["DATABASE_URL"] = "sqlite+pysqlite:///:memory:"
os.environ["SESSION_SECRET"] = "test-only-session-secret-with-32-characters"
os.environ["SESSION_COOKIE_SECURE"] = "false"

from database import Base, get_db
from main import app
from models import (
    Account,
    AnalyticsDailyAggregate,
    AnalyticsEvent,
    GameDailyDistricts,
    Guess,
    TrainingAttempt,
    TrainingCard,
    TrainingSession,
    VisitorAccountLink,
)

test_engine = create_engine(
    "sqlite+pysqlite:///:memory:",
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
TestSession = sessionmaker(
    bind=test_engine, autoflush=False, expire_on_commit=False
)
Base.metadata.create_all(test_engine)


def override_get_db() -> Generator[Session, None, None]:
    """Yield an isolated database session for API tests."""
    with TestSession() as session:
        yield session


app.dependency_overrides[get_db] = override_get_db


def _delete_records() -> None:
    """Remove test records in foreign-key order while retaining the schema."""
    with TestSession.begin() as session:
        session.execute(delete(AnalyticsEvent))
        session.execute(delete(VisitorAccountLink))
        session.execute(delete(AnalyticsDailyAggregate))
        session.execute(delete(TrainingAttempt))
        session.execute(delete(TrainingCard))
        session.execute(delete(TrainingSession))
        session.execute(delete(Guess))
        session.execute(delete(GameDailyDistricts))
        session.execute(delete(Account))


@pytest.fixture(autouse=True)
def clear_database() -> Generator[None, None, None]:
    """Isolate each API test."""
    _delete_records()
    yield
    _delete_records()


@pytest.fixture
def client() -> Generator[TestClient, None, None]:
    """Provide an API client with an independent cookie jar."""
    with TestClient(app) as test_client:
        yield test_client