# Generated by GitHub Copilot - Aug-28-2026
from conftest import TestSession
from fastapi.testclient import TestClient
from sqlalchemy import func, select

from game import PIN_BORDER_CLEARANCE_MAX_METERS, PIN_BORDER_CLEARANCE_METERS
from main import app, catalog, challenge_generator, current_challenge_date
from models import Account, GameDailyDistricts, Guess

client = TestClient(app)


def test_daily_is_deterministic_and_does_not_leak_answers() -> None:
    first = client.get("/api/daily")
    second = client.get("/api/daily")

    assert first.status_code == 200
    assert first.json() == second.json()
    assert first.json()["generation_version"] == "daily-districts-v2"
    assert len(first.json()["pins"]) == 5
    assert first.json()["solved_pins"] == []
    serialized = first.text.lower()
    assert "district_name" not in serialized
    assert "boundary" not in serialized
    assert "guessed_district_id" not in serialized


def test_correct_global_guess_reveals_only_matching_pin() -> None:
    challenge_date = current_challenge_date()
    pin = challenge_generator.generate(challenge_date)[3]

    response = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": challenge_date.isoformat(),
            "guessed_district_id": pin.district.id,
            "anonymous_state": {
                "budget_remaining": 10,
                "solved_pin_indices": [],
            },
        },
    )

    assert response.status_code == 200
    result = response.json()
    assert result["correct"] is True
    assert result["solved_pin_index"] == 3
    assert result["budget_remaining"] == 9
    assert result["distance_km"] is None
    assert result["missed_district"] is None
    assert len(result["reveals"]) == 1
    assert result["reveals"][0]["index"] == 3
    assert result["reveals"][0]["district_name"] == pin.district.name
    assert result["reveals"][0]["boundary"]["type"] == "MultiPolygon"


def test_miss_returns_distance_and_spends_budget() -> None:
    challenge_date = current_challenge_date()
    pins = challenge_generator.generate(challenge_date)
    answer_ids = {pin.district.id for pin in pins}
    miss = next(district for district in catalog.districts if district.id not in answer_ids)

    response = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": challenge_date.isoformat(),
            "guessed_district_id": miss.id,
            "anonymous_state": {
                "budget_remaining": 10,
                "solved_pin_indices": [],
            },
        },
    )

    assert response.status_code == 200
    result = response.json()
    assert result["correct"] is False
    assert result["solved_pin_index"] is None
    assert result["budget_remaining"] == 9
    assert result["distance_km"] >= 0
    assert result["missed_district"]["district_id"] == miss.id
    assert result["missed_district"]["district_name"] == miss.name
    assert result["missed_district"]["distance_km"] == result["distance_km"]
    assert result["missed_district"]["boundary"]["type"] == "MultiPolygon"
    assert result["reveals"] == []


def test_authenticated_duplicate_guess_does_not_spend_budget(client: TestClient) -> None:
    client.post(
        "/api/auth/register",
        json={"username": "DuplicatePlayer", "password": "valid-password"},
    )
    challenge_date = current_challenge_date()
    answer_ids = {pin.district.id for pin in challenge_generator.generate(challenge_date)}
    miss = next(district for district in catalog.districts if district.id not in answer_ids)
    payload = {
        "challenge_date": challenge_date.isoformat(),
        "guessed_district_id": miss.id,
    }

    first = client.post("/api/daily/guess", json=payload)
    repeated = client.post("/api/daily/guess", json=payload)
    restored = client.get("/api/daily")

    assert first.status_code == 200
    assert first.json()["budget_remaining"] == 9
    assert repeated.status_code == 409
    assert repeated.json() == {"detail": "This Stadtteil has already been guessed", "code": "daily_already_guessed"}
    assert restored.status_code == 200
    assert restored.json()["budget_remaining"] == 9
    assert len(restored.json()["guess_history"]) == 1


def test_last_guess_reveals_every_pin() -> None:
    challenge_date = current_challenge_date()
    pins = challenge_generator.generate(challenge_date)
    answer_ids = {pin.district.id for pin in pins}
    miss = next(district for district in catalog.districts if district.id not in answer_ids)

    response = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": challenge_date.isoformat(),
            "guessed_district_id": miss.id,
            "anonymous_state": {
                "budget_remaining": 1,
                "solved_pin_indices": [],
            },
        },
    )

    assert response.status_code == 200
    result = response.json()
    assert result["status"] == "finished"
    assert result["budget_remaining"] == 0
    assert len(result["reveals"]) == 5


def test_invalid_anonymous_state_is_rejected() -> None:
    response = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": current_challenge_date().isoformat(),
            "guessed_district_id": 1,
            "anonymous_state": {
                "budget_remaining": 10,
                "solved_pin_indices": [0, 0],
            },
        },
    )

    assert response.status_code == 422


def test_authenticated_progress_is_restored_after_login(client: TestClient) -> None:
    """An Account's accepted Guess is restored without trusting browser state."""
    client.post(
        "/api/auth/register",
        json={"username": "ResumePlayer", "password": "valid-password"},
    )
    challenge_date = current_challenge_date()
    pins = challenge_generator.generate(challenge_date)
    answer_ids = {pin.district.id for pin in pins}
    miss = next(district for district in catalog.districts if district.id not in answer_ids)

    guessed = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": challenge_date.isoformat(),
            "guessed_district_id": miss.id,
            "anonymous_state": {
                "budget_remaining": 1,
                "solved_pin_indices": [0, 1, 2, 3],
            },
        },
    )
    client.cookies.clear()
    login = client.post(
        "/api/auth/login",
        json={"username": "ResumePlayer", "password": "valid-password"},
    )
    restored = client.get("/api/daily")

    assert guessed.status_code == 200
    assert guessed.json()["budget_remaining"] == 9
    assert guessed.json()["status"] == "in_progress"
    assert login.status_code == 200
    assert restored.status_code == 200
    assert restored.json()["state_source"] == "account"
    assert restored.json()["budget_remaining"] == 9
    assert restored.json()["status"] == "in_progress"
    assert restored.json()["solved_pins"] == []
    assert restored.json()["guess_history"] == [
        {
            "district_id": miss.id,
            "district_name": miss.name,
            "correct": False,
            "distance_km": guessed.json()["distance_km"],
            "solved_pin_index": None,
        }
    ]
    assert restored.json()["missed_districts"][0]["district_id"] == miss.id


def test_authenticated_finished_game_cannot_be_replayed(client: TestClient) -> None:
    """A finished Account Game remains finished and rejects later Guesses."""
    client.post(
        "/api/auth/register",
        json={"username": "DailyPlayer", "password": "valid-password"},
    )
    challenge_date = current_challenge_date()
    pins = challenge_generator.generate(challenge_date)
    answer_ids = {pin.district.id for pin in pins}
    misses = [district for district in catalog.districts if district.id not in answer_ids]

    for miss in misses[:10]:
        response = client.post(
            "/api/daily/guess",
            json={
                "challenge_date": challenge_date.isoformat(),
                "guessed_district_id": miss.id,
            },
        )
        assert response.status_code == 200

    client.cookies.clear()
    login = client.post(
        "/api/auth/login",
        json={"username": "DailyPlayer", "password": "valid-password"},
    )
    restored = client.get("/api/daily")
    replay = client.post(
        "/api/daily/guess",
        json={
            "challenge_date": challenge_date.isoformat(),
            "guessed_district_id": pins[0].district.id,
        },
    )

    assert login.status_code == 200
    assert restored.status_code == 200
    assert restored.json()["status"] == "finished"
    assert restored.json()["budget_remaining"] == 0
    assert len(restored.json()["solved_pins"]) == 5
    assert len(restored.json()["guess_history"]) == 10
    assert replay.status_code == 409
    assert replay.json() == {
        "detail": "Today's Daily Challenge is already finished",
        "code": "http.409",
    }
    with TestSession() as database:
        guess_count = database.scalar(
            select(func.count())
            .select_from(Guess)
            .join(GameDailyDistricts)
            .join(Account)
            .where(Account.username == "DailyPlayer")
        )
        assert guess_count == 10


def test_seeded_challenge_is_deterministic_and_isolated() -> None:
    first = client.get("/api/challenges/harbour-party")
    repeated = client.get("/api/challenges/harbour-party")
    different = client.get("/api/challenges/another-party")

    assert first.status_code == 200
    assert first.json() == repeated.json()
    assert first.json()["generation_version"] == "daily-districts-v2"
    assert first.json()["seed"] == "harbour-party"
    assert first.json()["pins"] != different.json()["pins"]
    assert "district_name" not in first.text.lower()
    assert "boundary" not in first.text.lower()


def test_seeded_guess_uses_seeded_answers() -> None:
    seed = "harbour-party"
    pin = challenge_generator.generate_seeded(seed)[2]

    response = client.post(
        f"/api/challenges/{seed}/guess",
        json={
            "guessed_district_id": pin.district.id,
            "anonymous_state": {
                "budget_remaining": 10,
                "solved_pin_indices": [],
            },
        },
    )

    assert response.status_code == 200
    result = response.json()
    assert result["correct"] is True
    assert result["solved_pin_index"] == 2
    assert len(result["reveals"]) == 1


def test_seeded_challenge_rejects_unsafe_seed() -> None:
    response = client.get("/api/challenges/not%20url%20safe")

    assert response.status_code == 422


def test_generated_pins_keep_clear_of_district_boundaries() -> None:
    seeds = ["harbour-party", "friday-at-the-harbour", "narrow-district-check"]

    for district in catalog.districts:
        assert not district.pin_area_metric.is_empty
        assert PIN_BORDER_CLEARANCE_METERS <= district.pin_clearance_meters
        assert district.pin_clearance_meters <= PIN_BORDER_CLEARANCE_MAX_METERS

    clearances = {district.pin_clearance_meters for district in catalog.districts}
    assert min(clearances) == PIN_BORDER_CLEARANCE_METERS
    assert max(clearances) == PIN_BORDER_CLEARANCE_MAX_METERS

    for seed in seeds:
        for pin in challenge_generator.generate_seeded(seed):
            clearance = pin.point_metric.distance(pin.district.geometry_metric.boundary)
            assert clearance >= pin.district.pin_clearance_meters - 0.01


def test_give_up_reveals_all_pins_without_spending_budget() -> None:
    seed = "harbour-party"

    response = client.post(
        f"/api/challenges/{seed}/give-up",
        json={
            "anonymous_state": {
                "budget_remaining": 7,
                "solved_pin_indices": [1],
            },
        },
    )

    assert response.status_code == 200
    result = response.json()
    assert result["status"] == "finished"
    assert result["budget_remaining"] == 7
    assert len(result["reveals"]) == 5
