# Generated by GitHub Copilot - Aug-28-2026
from conftest import TestSession
from fastapi.testclient import TestClient
from sqlalchemy import func, select

from main import catalog
from models import Account, TrainingAttempt, TrainingCard, TrainingSession
from training import _normalize_name


def _register(client: TestClient, username: str) -> None:
    """Create the signed Account required by Training endpoints."""
    response = client.post(
        "/api/auth/register",
        json={"username": username, "password": "valid-password"},
    )
    assert response.status_code == 201


def _all_bezirke() -> list[str]:
    """Return the trusted complete Bezirk scope used by API tests."""
    return sorted({district.bezirk for district in catalog.districts})


def test_training_requires_a_signed_account(client: TestClient) -> None:
    """Anonymous users cannot read geometry, progress, or start sessions."""
    bootstrap = client.get("/api/training/bootstrap")
    session = client.post(
        "/api/training/sessions",
        json={"direction": "name", "selected_bezirke": _all_bezirke()},
    )

    assert bootstrap.status_code == 401
    assert bootstrap.headers["cache-control"] == "no-store"
    assert session.status_code == 401


def test_bootstrap_returns_training_geometry_and_empty_progress(
    client: TestClient,
) -> None:
    """Signed users receive all boundaries without any fabricated progress."""
    _register(client, "BootstrapPlayer")

    response = client.get("/api/training/bootstrap")

    assert response.status_code == 200
    result = response.json()
    assert len(result["districts"]) == 104
    assert len(result["bezirke"]) == 7
    assert result["districts"][0]["boundary"]["type"] == "MultiPolygon"
    assert result["progress"]["attempts"] == 0
    assert result["progress"]["directions"]["name"]["due"] == 0
    assert response.headers["cache-control"] == "no-store"


def test_name_answer_unlocks_find_and_accepts_keyboard_variants(
    client: TestClient,
) -> None:
    """A first Name It answer creates its card and makes Find It eligible."""
    _register(client, "LearningPlayer")
    started = client.post(
        "/api/training/sessions",
        json={"direction": "name", "selected_bezirke": _all_bezirke()},
    )
    question = started.json()
    district = catalog.by_id[question["district_id"]]

    answer = client.post(
        f"/api/training/sessions/{question['session_id']}/answer",
        json={"answer_text": district.name},
    )
    find_session = client.post(
        "/api/training/sessions",
        json={"direction": "find", "selected_bezirke": _all_bezirke()},
    )

    assert started.status_code == 201
    assert question["prompt_name"] is None
    assert answer.status_code == 200
    assert answer.json()["correct"] is True
    assert answer.json()["stage"] == 1
    assert find_session.status_code == 201
    assert find_session.json()["prompt_name"] == district.name
    assert _normalize_name("Groß Flottbek") == _normalize_name("gross-flottbek")
    assert _normalize_name("Rönneburg") == _normalize_name("roenneburg")


def test_missed_item_returns_after_three_completed_questions(
    client: TestClient,
) -> None:
    """The persisted session queue enforces the chosen correction gap."""
    _register(client, "QueuePlayer")
    started = client.post(
        "/api/training/sessions",
        json={"direction": "name", "selected_bezirke": _all_bezirke()},
    ).json()
    session_id = started["session_id"]
    missed_id = started["district_id"]

    missed = client.post(
        f"/api/training/sessions/{session_id}/answer",
        json={"answer_text": "not-a-hamburg-stadtteil"},
    )
    intervening_ids: list[int] = []
    for _ in range(3):
        question = client.post(
            f"/api/training/sessions/{session_id}/next"
        ).json()
        intervening_ids.append(question["district_id"])
        answer = client.post(
            f"/api/training/sessions/{session_id}/answer",
            json={"answer_text": catalog.by_id[question["district_id"]].name},
        )
        assert answer.status_code == 200
    repeated = client.post(f"/api/training/sessions/{session_id}/next")

    assert missed.status_code == 200
    assert missed.json()["outcome"] == "incorrect"
    assert missed_id not in intervening_ids
    assert repeated.status_code == 200
    assert repeated.json()["district_id"] == missed_id


def test_card_management_progress_and_training_only_reset(
    client: TestClient,
) -> None:
    """Known, shelf, restore, progress, and reset mutations stay Account-scoped."""
    _register(client, "ManagePlayer")
    question = client.post(
        "/api/training/sessions",
        json={"direction": "name", "selected_bezirke": _all_bezirke()},
    ).json()
    district = catalog.by_id[question["district_id"]]
    client.post(
        f"/api/training/sessions/{question['session_id']}/answer",
        json={"answer_text": district.name},
    )

    known = client.post(
        f"/api/training/cards/name/{district.id}",
        json={"action": "already_known"},
    )
    shelved = client.post(
        f"/api/training/cards/name/{district.id}", json={"action": "shelve"}
    )
    restored = client.post(
        f"/api/training/cards/name/{district.id}", json={"action": "restore"}
    )
    progress = client.get("/api/training/progress")
    reset = client.delete("/api/training")

    assert known.status_code == 200
    assert known.json()["items"][0]["name_category"] == "known"
    assert shelved.json()["items"][0]["name_category"] == "shelved"
    assert restored.json()["items"][0]["name_category"] == "known"
    assert progress.json()["attempts"] == 1
    assert reset.status_code == 204
    with TestSession() as database:
        account_id = database.scalar(
            select(Account.id).where(Account.username == "ManagePlayer")
        )
        assert database.scalar(
            select(func.count(TrainingCard.id)).where(
                TrainingCard.account_id == account_id
            )
        ) == 0
        assert database.scalar(
            select(func.count(TrainingAttempt.id)).where(
                TrainingAttempt.account_id == account_id
            )
        ) == 0
        assert database.scalar(
            select(func.count(TrainingSession.id)).where(
                TrainingSession.account_id == account_id
            )
        ) == 0