# Generated by GitHub Copilot - Aug-28-2026
import pytest
from fastapi.testclient import TestClient
from sqlalchemy import select
from sqlalchemy.exc import OperationalError
from sqlalchemy.orm import Session

from auth import SESSION_COOKIE_NAME, password_hash
from models import Account
from tests.conftest import TestSession


def test_registration_hashes_password_and_sets_session_cookie(
    client: TestClient,
) -> None:
    """Registration persists a hash and establishes a protected session."""
    response = client.post(
        "/api/auth/register",
        json={"username": "  TestPlayer  ", "password": "correct-horse"},
    )

    assert response.status_code == 201
    assert response.json() == {"id": 1, "username": "TestPlayer"}
    assert response.headers["cache-control"] == "no-store"
    set_cookie = response.headers["set-cookie"]
    assert "HttpOnly" in set_cookie
    assert "SameSite=lax" in set_cookie
    assert "Max-Age=2592000" in set_cookie
    assert "Secure" not in set_cookie

    with TestSession() as database:
        account = database.scalar(select(Account))
        assert account is not None
        assert account.password_hash != "correct-horse"
        assert account.password_hash.startswith("$argon2")
        assert password_hash.verify("correct-horse", account.password_hash)


def test_current_account_is_restored_from_session(client: TestClient) -> None:
    """A valid registration cookie resolves to the persisted Account."""
    registered = client.post(
        "/api/auth/register",
        json={"username": "PersistentPlayer", "password": "valid-password"},
    )

    response = client.get("/api/auth/me")

    assert registered.status_code == 201
    assert response.status_code == 200
    assert response.json() == registered.json()
    assert response.headers["cache-control"] == "no-store"


def test_login_accepts_case_insensitive_username_and_sets_session(
    client: TestClient,
) -> None:
    """Valid credentials restore the Account using its display-case username."""
    registered = client.post(
        "/api/auth/register",
        json={"username": "KnownPlayer", "password": "valid-password"},
    )
    client.cookies.clear()

    login = client.post(
        "/api/auth/login",
        json={"username": "  knownplayer  ", "password": "valid-password"},
    )
    current = client.get("/api/auth/me")

    assert registered.status_code == 201
    assert login.status_code == 200
    assert login.json() == registered.json()
    assert login.headers["cache-control"] == "no-store"
    assert "HttpOnly" in login.headers["set-cookie"]
    assert current.status_code == 200
    assert current.json() == registered.json()


@pytest.mark.parametrize(
    ("username", "password"),
    [
        ("KnownPlayer", "wrong-password"),
        ("UnknownPlayer", "valid-password"),
    ],
)
def test_login_rejects_credentials_without_account_disclosure(
    client: TestClient, username: str, password: str
) -> None:
    """Unknown usernames and wrong passwords return the same protected response."""
    client.post(
        "/api/auth/register",
        json={"username": "KnownPlayer", "password": "valid-password"},
    )
    client.cookies.clear()

    response = client.post(
        "/api/auth/login",
        json={"username": username, "password": password},
    )

    assert response.status_code == 401
    assert response.json() == {"detail": "Invalid username or password"}
    assert response.headers["cache-control"] == "no-store"
    assert "set-cookie" not in response.headers


def test_logout_clears_session_cookie(client: TestClient) -> None:
    """Signing out invalidates the browser session without deleting the Account."""
    registered = client.post(
        "/api/auth/register",
        json={"username": "SigningOut", "password": "valid-password"},
    )

    logout = client.post("/api/auth/logout")
    current = client.get("/api/auth/me")

    assert registered.status_code == 201
    assert logout.status_code == 200
    assert logout.json() == {"status": "signed_out"}
    assert logout.headers["cache-control"] == "no-store"
    assert f'{SESSION_COOKIE_NAME}=""' in logout.headers["set-cookie"]
    assert "Max-Age=0" in logout.headers["set-cookie"]
    assert current.status_code == 401
    with TestSession() as database:
        assert database.scalar(select(Account).where(Account.username == "SigningOut"))


def test_current_account_rejects_missing_and_tampered_sessions(
    client: TestClient,
) -> None:
    """Missing or invalid signatures never authenticate an Account."""
    missing = client.get("/api/auth/me")
    client.cookies.set(SESSION_COOKIE_NAME, "tampered-token")
    tampered = client.get("/api/auth/me")

    assert missing.status_code == 401
    assert missing.json() == {"detail": "Not authenticated"}
    assert missing.headers["cache-control"] == "no-store"
    assert tampered.status_code == 401
    assert tampered.json() == {"detail": "Not authenticated"}
    assert tampered.headers["cache-control"] == "no-store"


def test_username_uniqueness_is_case_insensitive(client: TestClient) -> None:
    """Username comparisons reject duplicates regardless of display case."""
    first = client.post(
        "/api/auth/register",
        json={"username": "HamburgFan", "password": "valid-password"},
    )
    duplicate = client.post(
        "/api/auth/register",
        json={"username": "hamburgfan", "password": "another-password"},
    )

    assert first.status_code == 201
    assert duplicate.status_code == 409
    assert duplicate.json() == {"detail": "Username is already registered"}


def test_uniqueness_conflict_rolls_back_session(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A concurrent-style unique conflict rolls back before later requests."""
    first = client.post(
        "/api/auth/register",
        json={"username": "Concurrent", "password": "valid-password"},
    )
    monkeypatch.setattr(Session, "scalar", lambda *_args, **_kwargs: None)
    conflict = client.post(
        "/api/auth/register",
        json={"username": "CONCURRENT", "password": "another-password"},
    )

    assert first.status_code == 201
    assert conflict.status_code == 409


def test_registration_returns_prompt_service_unavailable_response(
    client: TestClient, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Database connection failures return a sanitized retryable response."""

    def raise_connection_error(*_args: object, **_kwargs: object) -> None:
        """Simulate an unavailable database without contacting PostgreSQL."""
        raise OperationalError("SELECT account", {}, TimeoutError("unavailable"))

    monkeypatch.setattr(Session, "scalar", raise_connection_error)

    response = client.post(
        "/api/auth/register",
        json={"username": "Unavailable", "password": "valid-password"},
    )

    assert response.status_code == 503
    assert response.json() == {
        "detail": "Account service temporarily unavailable. Please try again."
    }
    assert response.headers["cache-control"] == "no-store"
    assert response.headers["retry-after"] == "5"


@pytest.mark.parametrize(
    ("username", "password"),
    [
        ("ab", "valid-password"),
        ("a" * 33, "valid-password"),
        ("valid-name", "short7"),
        ("valid-name", "p" * 129),
        ("bad\nname", "valid-password"),
    ],
)
def test_registration_rejects_invalid_credentials(
    client: TestClient, username: str, password: str
) -> None:
    """Credential validation rejects out-of-contract input."""
    response = client.post(
        "/api/auth/register",
        json={"username": username, "password": password},
    )

    assert response.status_code == 422


@pytest.mark.parametrize(
    ("username", "password"),
    [
        ("abc", "p" * 8),
        ("u" * 32, "p" * 128),
    ],
)
def test_registration_accepts_credential_boundaries(
    client: TestClient, username: str, password: str
) -> None:
    """Credential validation accepts values exactly at documented limits."""
    response = client.post(
        "/api/auth/register",
        json={"username": username, "password": password},
    )

    assert response.status_code == 201