// In development Vite proxies relative API calls to the local backend. This
// also works when the frontend is opened through WSL, a container, or a LAN IP.
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? ''

// Generated by GitHub Copilot - Aug-28-2026
export class ApiError extends Error {
  readonly status: number

  /** Create an error retaining the HTTP status for caller-specific handling. */
  constructor(status: number, message: string) {
    super(message)
    this.name = 'ApiError'
    this.status = status
  }
}

export async function apiFetch<T>(
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const headers = new Headers(init.headers)
  if (init.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json')
  }

  const response = await fetch(`${API_BASE_URL}${path}`, {
    ...init,
    credentials: 'include',
    headers,
  })

  if (!response.ok) {
    const contentType = response.headers.get('content-type')
    if (contentType?.includes('application/json')) {
      const body = await response.json() as { detail?: unknown }
      const message = typeof body.detail === 'string'
        ? body.detail
        : `Request failed with status ${response.status}`
      throw new ApiError(response.status, message)
    }
    throw new ApiError(
      response.status,
      (await response.text()) || `Request failed with status ${response.status}`,
    )
  }

  return response.json() as Promise<T>
}
