// In development Vite proxies relative API calls to the local backend. This
// also works when the frontend is opened through WSL, a container, or a LAN IP.
const API_BASE_URL = import.meta.env.VITE_API_BASE_URL ?? ''

// Generated by GitHub Copilot - Aug-28-2026
export class ApiError extends Error {
  readonly status: number
  readonly code: string | null

  /** Create an error retaining stable machine-readable response metadata. */
  constructor(status: number, message: string, code: string | null = null) {
    super(message)
    this.name = 'ApiError'
    this.status = status
    this.code = code
  }
}

/** Prefer a localized API code and never expose backend diagnostic prose to players. */
export function apiErrorMessage(
  reason: unknown,
  translate: (key: string) => string,
  fallbackKey: string,
) {
  if (reason instanceof ApiError && reason.code) {
    const key = `common.errorByCode.${reason.code}`
    const translated = translate(key)
    if (translated !== key) return translated
  }
  return translate(fallbackKey)
}

export async function apiFetch<T>(
  path: string,
  init: RequestInit = {},
): Promise<T> {
  const headers = new Headers(init.headers)
  if (init.body && !headers.has('Content-Type')) {
    headers.set('Content-Type', 'application/json')
  }

  const response = await fetch(`${API_BASE_URL}${path}`, {
    ...init,
    credentials: 'include',
    headers,
  })

  if (!response.ok) {
    const contentType = response.headers.get('content-type')
    if (contentType?.includes('application/json')) {
      const body = await response.json() as { detail?: unknown; code?: unknown }
      const message = typeof body.detail === 'string'
        ? body.detail
        : `Request failed with status ${response.status}`
      throw new ApiError(
        response.status,
        message,
        typeof body.code === 'string' ? body.code : null,
      )
    }
    throw new ApiError(
      response.status,
      (await response.text()) || `Request failed with status ${response.status}`,
    )
  }

  return response.json() as Promise<T>
}
