// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleUserRound, Compass, Copy, Dices, Flag, Home, LocateFixed, LogIn, RefreshCw, Share2, UserPlus, X } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useTranslation } from 'react-i18next'
import { AdminPage } from './AdminPage'
import { AnalyticsPrivacy } from './AnalyticsPrivacy'
import { AppMenu } from './AppMenu'
import { ExploreApp } from './ExploreApp'
import { LoginDialog } from './LoginDialog'
import type { MissedDistrict, Pin, Reveal } from './MapView'
import { MapView } from './MapView'
import { ModeHome } from './ModeHome'
import type { Account } from './RegisterDialog'
import { RegisterDialog } from './RegisterDialog'
import { TrainingApp, TrainingProgressPage } from './TrainingApp'
import { ApiError, apiErrorMessage, apiFetch } from './api'
import i18n, { activeLanguage } from './i18n'
import { firstTouchContext, track } from './analytics'
import './App.css'

type District = {
  id: number
  name: string
}

type ChallengeResponse = {
  generation_version: string
  date?: string
  seed?: string
  pins: Pin[]
  initial_budget: number
  budget_remaining: number
  solved_pins: Reveal[]
  missed_districts: MissedDistrict[]
  guess_history: ApiGuessHistoryEntry[]
  status: 'in_progress' | 'finished'
  state_source: 'anonymous' | 'account'
}

type Challenge = ChallengeResponse & {
  mode: 'daily' | 'seeded'
  id: string
}

type GuessResult = {
  correct: boolean
  solved_pin_index: number | null
  distance_km: number | null
  missed_district: MissedDistrict | null
  budget_remaining: number
  status: 'in_progress' | 'finished'
  reveals: Reveal[]
}

type GiveUpResult = {
  budget_remaining: number
  status: 'finished'
  reveals: Reveal[]
}

type GuessHistoryEntry = {
  districtId: number
  districtName: string
  correct: boolean
  distanceKm: number | null
  solvedPinIndex: number | null
}

type ApiGuessHistoryEntry = {
  district_id: number
  district_name: string
  correct: boolean
  distance_km: number | null
  solved_pin_index: number | null
}

type Progress = {
  date: string
  budgetRemaining: number
  solvedPinIndices: number[]
  reveals: Reveal[]
  missedDistricts: MissedDistrict[]
  guessHistory: GuessHistoryEntry[]
  status: 'in_progress' | 'finished'
  finishReason: 'solved' | 'budget' | 'gave_up' | null
}

type Feedback = {
  kind: 'correct' | 'miss' | 'error'
  message: string
}

const requestedSeed = new URLSearchParams(window.location.search).get('seed')

function phraseToSeed(phrase: string) {
  return phrase
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
}

function inviteUrl(seed: string) {
  const url = new URL(window.location.origin)
  url.searchParams.set('seed', seed)
  return url.toString()
}

function storageKey(challenge: Challenge) {
  return challenge.mode === 'daily'
    ? `hamburg-whereabouts:${challenge.generation_version}:${challenge.id}`
    : `hamburg-whereabouts:${challenge.generation_version}:seed:${challenge.id}`
}

function loadProgress(challenge: Challenge): Progress {
  const initial: Progress = {
    date: challenge.id,
    budgetRemaining: challenge.initial_budget,
    solvedPinIndices: [],
    reveals: [],
    missedDistricts: [],
    guessHistory: [],
    status: 'in_progress',
    finishReason: null,
  }
  try {
    const stored = localStorage.getItem(storageKey(challenge))
    if (!stored) return initial
    const parsed = JSON.parse(stored) as Partial<Progress>
    if (
      parsed.date !== challenge.id ||
      typeof parsed.budgetRemaining !== 'number' ||
      parsed.budgetRemaining < 0 ||
      parsed.budgetRemaining > challenge.initial_budget ||
      !Array.isArray(parsed.solvedPinIndices) ||
      !Array.isArray(parsed.reveals)
    ) {
      return initial
    }
    return {
      date: challenge.id,
      budgetRemaining: parsed.budgetRemaining,
      solvedPinIndices: parsed.solvedPinIndices,
      reveals: parsed.reveals,
      missedDistricts: Array.isArray(parsed.missedDistricts) ? parsed.missedDistricts : [],
      guessHistory: Array.isArray(parsed.guessHistory) ? parsed.guessHistory : [],
      status: parsed.status === 'finished' ? 'finished' : 'in_progress',
      finishReason: parsed.finishReason === 'solved' || parsed.finishReason === 'budget' || parsed.finishReason === 'gave_up'
        ? parsed.finishReason
        : null,
    }
  } catch {
    return initial
  }
}

/** Select trusted Account progress or challenge-scoped anonymous browser progress. */
function progressFromChallenge(challenge: Challenge): Progress {
  if (challenge.mode === 'seeded' || challenge.state_source === 'anonymous') {
    return loadProgress(challenge)
  }
  const solvedPinIndices = challenge.guess_history.flatMap((entry) => (
    entry.correct && entry.solved_pin_index !== null ? [entry.solved_pin_index] : []
  ))
  return {
    date: challenge.id,
    budgetRemaining: challenge.budget_remaining,
    solvedPinIndices,
    reveals: challenge.solved_pins,
    missedDistricts: challenge.missed_districts,
    guessHistory: challenge.guess_history.map((entry) => ({
      districtId: entry.district_id,
      districtName: entry.district_name,
      correct: entry.correct,
      distanceKm: entry.distance_km,
      solvedPinIndex: entry.solved_pin_index,
    })),
    status: challenge.status,
    finishReason: challenge.status === 'finished'
      ? solvedPinIndices.length === challenge.pins.length ? 'solved' : 'budget'
      : null,
  }
}

function mergeMissedDistricts(existing: MissedDistrict[], incoming: MissedDistrict) {
  const byId = new Map(existing.map((district) => [district.district_id, district]))
  byId.set(incoming.district_id, incoming)
  return [...byId.values()]
}

function mergeReveals(existing: Reveal[], incoming: Reveal[]) {
  const byIndex = new Map(existing.map((reveal) => [reveal.index, reveal]))
  incoming.forEach((reveal) => byIndex.set(reveal.index, reveal))
  return [...byIndex.values()].sort((a, b) => a.index - b.index)
}

/** Preserve the existing Daily Challenge behavior at its dedicated route. */
function DailyApp({ onHome }: { onHome: () => void }) {
  const { t } = useTranslation()
  const [screen, setScreen] = useState<'start' | 'game' | 'finished'>('start')
  const [challenge, setChallenge] = useState<Challenge | null>(null)
  const [districts, setDistricts] = useState<District[]>([])
  const [progress, setProgress] = useState<Progress | null>(null)
  const [guess, setGuess] = useState('')
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(-1)
  const [feedback, setFeedback] = useState<Feedback | null>(null)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [confirmingGiveUp, setConfirmingGiveUp] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [account, setAccount] = useState<Account | null>(null)
  const [accountError, setAccountError] = useState<string | null>(null)
  const [loginOpen, setLoginOpen] = useState(false)
  const [registrationOpen, setRegistrationOpen] = useState(false)
  const [shareLabel, setShareLabel] = useState<'copy' | 'copied' | 'failed'>('copy')
  const [shareStatus, setShareStatus] = useState<string | null>(null)
  const [customPhrase, setCustomPhrase] = useState(requestedSeed ?? '')
  const [creatorError, setCreatorError] = useState<string | null>(null)
  const guessInputRef = useRef<HTMLInputElement>(null)
  const loginButtonRef = useRef<HTMLButtonElement>(null)
  const registrationButtonRef = useRef<HTMLButtonElement>(null)


  useEffect(() => {
    let cancelled = false
    const challengePath = requestedSeed
      ? `/api/challenges/${encodeURIComponent(requestedSeed)}`
      : '/api/daily'
    Promise.all([
      apiFetch<ChallengeResponse>(challengePath),
      apiFetch<District[]>('/api/districts'),
    ])
      .then(([response, districtList]) => {
        if (cancelled) return
        const loadedChallenge: Challenge = requestedSeed
          ? {
              ...response,
              mode: 'seeded',
              id: requestedSeed,
              missed_districts: [],
              guess_history: [],
              state_source: 'anonymous',
            }
          : { ...response, mode: 'daily', id: response.date ?? '' }
        setChallenge(loadedChallenge)
        setDistricts(districtList)
        setProgress(progressFromChallenge(loadedChallenge))
      })
      .catch((reason: unknown) => {
        if (!cancelled) {
          setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'daily.loadError'))
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Open login without changing anonymous Daily Challenge state. */
  function openLogin() {
    setAccountError(null)
    setLoginOpen(true)
  }

  /** Close login and return keyboard focus to its opener. */
  function closeLogin() {
    setLoginOpen(false)
    requestAnimationFrame(() => loginButtonRef.current?.focus())
  }

  useEffect(() => {
    let cancelled = false
    apiFetch<Account>('/api/auth/me')
      .then((currentAccount) => {
        if (!cancelled) setAccount(currentAccount)
      })
      .catch((reason: unknown) => {
        if (
          !cancelled &&
          !(reason instanceof ApiError && reason.status === 401)
        ) {
          setAccountError(i18n.t('common.accountStatusError'))
        }
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Open registration without changing anonymous Daily Challenge state. */
  function openRegistration() {
    setAccountError(null)
    setRegistrationOpen(true)
  }

  /** Close registration and return keyboard focus to its opener. */
  function closeRegistration() {
    setRegistrationOpen(false)
    requestAnimationFrame(() => registrationButtonRef.current?.focus())
  }

  /** Retain a new session and replace browser progress with Account progress. */
  async function handleAuthenticated(authenticatedAccount: Account) {
    setAccount(authenticatedAccount)
    setAccountError(null)
    if (challenge?.mode === 'seeded') return
    try {
      const response = await apiFetch<ChallengeResponse>('/api/daily')
      const daily: Challenge = {
        ...response,
        mode: 'daily',
        id: response.date ?? '',
      }
      setChallenge(daily)
      setProgress(progressFromChallenge(daily))
    } catch {
      setAccountError(t('daily.accountProgressError'))
    }
  }

  function begin() {
    if (!progress) return
    track(challenge?.mode === 'seeded' ? 'seeded_started' : 'daily_started', challenge?.mode === 'seeded' ? { seed: challenge.id } : {})
    setScreen(progress.status === 'finished' ? 'finished' : 'game')
    requestAnimationFrame(() => guessInputRef.current?.focus())
  }

  function returnToStart() {
    setFeedback(null)
    setConfirmingGiveUp(false)
    setScreen('start')
  }

  function createRandomChallenge() {
    const values = crypto.getRandomValues(new Uint32Array(2))
    const seed = Array.from(values, (value) => value.toString(36)).join('-')
    window.location.assign(`/daily?seed=${seed}`)
  }

  async function copyInviteLink() {
    if (!challenge || challenge.mode !== 'seeded') return
    try {
      await navigator.clipboard.writeText(inviteUrl(challenge.id))
      setShareLabel('copied')
      setShareStatus(t('daily.inviteCopied'))
    } catch {
      setShareLabel('failed')
      setShareStatus(t('daily.clipboardBlocked'))
    }
  }

  async function shareInviteLink() {
    if (!challenge || challenge.mode !== 'seeded') return
    if (!navigator.share) {
      await copyInviteLink()
      return
    }
    try {
      await navigator.share({
        title: 'Hamburg Whereabouts',
        text: t('daily.shareText'),
        url: inviteUrl(challenge.id),
      })
      setShareStatus(t('daily.inviteShared'))
    } catch (reason) {
      if (reason instanceof DOMException && reason.name === 'AbortError') return
      setShareStatus(t('daily.shareFailed'))
    }
  }

  function previewCustomPhrase(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const seed = phraseToSeed(customPhrase)
    if (seed.length < 3) {
      setCreatorError(t('daily.phraseValidation'))
      return
    }
    window.location.assign(`/?seed=${seed}`)
  }

  function findDistrict(value: string) {
    const normalized = value.trim().toLocaleLowerCase('de')
    return districts.find(
      (district) => district.name.toLocaleLowerCase('de') === normalized,
    )
  }

  async function checkGuess(district: District) {
    if (!challenge || !progress || submitting || progress.status === 'finished') return
    if (progress.guessHistory.some((entry) => entry.districtId === district.id)) {
      setGuess('')
      setActiveSuggestionIndex(-1)
      setConfirmingGiveUp(false)
      setFeedback({ kind: 'error', message: t('daily.alreadyGuessed', { district: district.name }) })
      requestAnimationFrame(() => guessInputRef.current?.focus())
      return
    }

    setSubmitting(true)
    setConfirmingGiveUp(false)
    setFeedback(null)
    try {
      const guessPath = challenge.mode === 'daily'
        ? '/api/daily/guess'
        : `/api/challenges/${encodeURIComponent(challenge.id)}/guess`
      const body = challenge.mode === 'daily'
        ? {
            challenge_date: challenge.id,
            guessed_district_id: district.id,
            anonymous_state: {
              budget_remaining: progress.budgetRemaining,
              solved_pin_indices: progress.solvedPinIndices,
            },
          }
        : {
            guessed_district_id: district.id,
            anonymous_state: {
              budget_remaining: progress.budgetRemaining,
              solved_pin_indices: progress.solvedPinIndices,
            },
          }
      const result = await apiFetch<GuessResult>(guessPath, {
        method: 'POST',
        body: JSON.stringify(body),
      })
      const nextSolved = result.solved_pin_index === null
        ? progress.solvedPinIndices
        : [...new Set([...progress.solvedPinIndices, result.solved_pin_index])]
      const next: Progress = {
        ...progress,
        budgetRemaining: result.budget_remaining,
        solvedPinIndices: nextSolved,
        reveals: mergeReveals(progress.reveals, result.reveals),
        missedDistricts: result.missed_district
          ? mergeMissedDistricts(progress.missedDistricts, result.missed_district)
          : progress.missedDistricts,
        guessHistory: [
          ...progress.guessHistory,
          {
            districtId: district.id,
            districtName: district.name,
            correct: result.correct,
            distanceKm: result.distance_km,
            solvedPinIndex: result.solved_pin_index,
          },
        ],
        status: result.status,
        finishReason: result.status === 'finished'
          ? nextSolved.length === challenge.pins.length ? 'solved' : 'budget'
          : null,
      }
      if (challenge.state_source === 'anonymous') {
        localStorage.setItem(storageKey(challenge), JSON.stringify(next))
      }
      setProgress(next)
      setGuess('')
      setFeedback(
        result.correct
          ? { kind: 'correct', message: t('daily.found', { district: district.name }) }
          : { kind: 'miss', message: t('daily.distance', { district: district.name, distance: new Intl.NumberFormat(activeLanguage(), { style: 'unit', unit: 'kilometer', maximumFractionDigits: 1 }).format(result.distance_km ?? 0) }) },
      )
      if (result.status === 'finished') {
        track(challenge.mode === 'seeded' ? 'seeded_completed' : 'daily_completed', {
          reason: next.finishReason ?? 'finished',
          pins_solved: nextSolved.length,
          guesses_spent: challenge.initial_budget - result.budget_remaining,
          ...(challenge.mode === 'seeded' ? { seed: challenge.id } : {}),
        })
        setScreen('finished')
      }
    } catch (reason) {
      setFeedback({
        kind: 'error',
        message: apiErrorMessage(reason, t, 'daily.guessError'),
      })
    } finally {
      setSubmitting(false)
      requestAnimationFrame(() => guessInputRef.current?.focus())
    }
  }

  async function giveUp() {
    if (!challenge || !progress || submitting || progress.status === 'finished') return
    if (!confirmingGiveUp) {
      setConfirmingGiveUp(true)
      return
    }

    setSubmitting(true)
    setFeedback(null)
    try {
      const giveUpPath = challenge.mode === 'daily'
        ? '/api/daily/give-up'
        : `/api/challenges/${encodeURIComponent(challenge.id)}/give-up`
      const body = challenge.mode === 'daily'
        ? {
            challenge_date: challenge.id,
            anonymous_state: {
              budget_remaining: progress.budgetRemaining,
              solved_pin_indices: progress.solvedPinIndices,
            },
          }
        : {
            anonymous_state: {
              budget_remaining: progress.budgetRemaining,
              solved_pin_indices: progress.solvedPinIndices,
            },
          }
      const result = await apiFetch<GiveUpResult>(giveUpPath, {
        method: 'POST',
        body: JSON.stringify(body),
      })
      const next: Progress = {
        ...progress,
        budgetRemaining: result.budget_remaining,
        reveals: mergeReveals(progress.reveals, result.reveals),
        status: result.status,
        finishReason: 'gave_up',
      }
      localStorage.setItem(storageKey(challenge), JSON.stringify(next))
      setProgress(next)
      track(challenge.mode === 'seeded' ? 'seeded_completed' : 'daily_completed', {
        reason: 'gave_up',
        pins_solved: progress.solvedPinIndices.length,
        guesses_spent: challenge.initial_budget - result.budget_remaining,
        ...(challenge.mode === 'seeded' ? { seed: challenge.id } : {}),
      })
      setScreen('finished')
    } catch (reason) {
      setFeedback({
        kind: 'error',
        message: apiErrorMessage(reason, t, 'daily.giveUpError'),
      })
    } finally {
      setSubmitting(false)
      setConfirmingGiveUp(false)
    }
  }

  function handleGuessChange(value: string) {
    setGuess(value)
    setActiveSuggestionIndex(-1)
  }

  function chooseDistrict(district: District) {
    setGuess(district.name)
    setActiveSuggestionIndex(-1)
    void checkGuess(district)
  }

  function handleGuessKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'ArrowDown' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (current + 1) % suggestions.length)
      return
    }
    if (event.key === 'ArrowUp' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (
        current <= 0 ? suggestions.length - 1 : current - 1
      ))
      return
    }
    if (event.key === 'Escape') {
      setGuess('')
      setActiveSuggestionIndex(-1)
      return
    }
    if (event.key !== 'Enter') return

    event.preventDefault()
    const selected = suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(guess)
    if (selected) {
      chooseDistrict(selected)
      return
    }
    setFeedback({ kind: 'error', message: t('common.chooseSuggestions') })
  }

  function submitGuess(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const district = suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(guess)
    if (district) {
      chooseDistrict(district)
      return
    }
    setFeedback({ kind: 'error', message: t('common.chooseList') })
  }

  const formattedDate = challenge?.date
    ? new Intl.DateTimeFormat(activeLanguage(), {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
      }).format(new Date(`${challenge.date}T12:00:00`))
    : t('common.today')
  const isSeeded = challenge?.mode === 'seeded'
  const currentInviteUrl = isSeeded && challenge ? inviteUrl(challenge.id) : ''
  const normalizedCustomSeed = phraseToSeed(customPhrase)
  const pinsSolved = progress?.solvedPinIndices.length ?? 0
  const guessesSpent = challenge && progress
    ? challenge.initial_budget - progress.budgetRemaining
    : 0
  const normalizedGuess = guess.trim().toLocaleLowerCase('de')
  const suggestions = normalizedGuess.length === 0
    ? []
    : districts.filter((district) => (
        district.name.toLocaleLowerCase('de').includes(normalizedGuess)
      ))

  return (
    <main className={`app-shell app-shell--${screen}`}>
      <MapView
        pins={challenge?.pins ?? []}
        reveals={progress?.reveals ?? []}
        missedDistricts={progress?.missedDistricts ?? []}
        solvedPinIndices={progress?.solvedPinIndices ?? []}
        showPins={screen !== 'start' || isSeeded}
        previewMode={screen === 'start' && isSeeded}
        annotateMissedDistricts={screen === 'finished' && !isSeeded}
      />

      <header className="brand-bar">
        <button className="brand-home" type="button" onClick={onHome} aria-label={t('common.returnModes')} title={t('common.home')}>
          <Home size={17} aria-hidden="true" />
        </button>
        <span className="brand-mark"><Compass size={18} strokeWidth={2.4} /></span>
        <span>Hamburg Whereabouts</span>
      </header>

      {screen === 'start' ? (
        <section className={isSeeded ? 'start-panel start-panel--seeded' : 'start-panel'} aria-labelledby="start-title">
          <p className="eyebrow">
            {isSeeded ? t('daily.sharedMap', { seed: challenge.id }) : t('daily.dailyDistricts', { date: formattedDate })}
          </p>
          <h1 id="start-title">
            {t(isSeeded ? 'daily.seededTitle' : 'daily.title')}
          </h1>
          <p className="start-copy">
            {isSeeded
              ? t('daily.seededIntro')
              : t('daily.intro')}
          </p>
          {error ? <p className="notice notice--error">{error}</p> : null}
          {accountError ? <p className="notice notice--error">{accountError}</p> : null}
          {isSeeded ? (
            <>
              <form className="seed-form" onSubmit={previewCustomPhrase}>
                <label htmlFor="custom-seed">{t('daily.customPhrase')}</label>
                <div className="seed-control">
                  <input
                    id="custom-seed"
                    value={customPhrase}
                    maxLength={80}
                    onChange={(event) => {
                      setCustomPhrase(event.target.value)
                      setCreatorError(null)
                    }}
                    placeholder={t('daily.phrasePlaceholder')}
                  />
                  <button type="submit" disabled={normalizedCustomSeed.length < 3}>
                    <RefreshCw size={16} />
                    <span>{t('daily.preview')}</span>
                  </button>
                </div>
                <p className={creatorError ? 'seed-help seed-help--error' : 'seed-help'}>
                  {creatorError ?? t('daily.seed', { seed: normalizedCustomSeed || t('daily.typePhrase') })}
                </p>
              </form>
              <div className="share-panel">
                <div className="qr-code" role="img" aria-label={t('daily.qrLabel')}>
                  <QRCodeSVG value={currentInviteUrl} size={88} bgColor="#ffffff" fgColor="#17201c" level="M" />
                </div>
                <div className="share-panel__actions">
                  <strong>{t('daily.invitePlayers')}</strong>
                  <button className="secondary-action" type="button" onClick={() => void copyInviteLink()}>
                    <Copy size={16} />
                    <span>{t(shareLabel === 'copy' ? 'daily.copyInvite' : shareLabel === 'copied' ? 'daily.linkCopied' : 'daily.copyFailed')}</span>
                  </button>
                  <button className="secondary-action" type="button" onClick={() => void shareInviteLink()}>
                    <Share2 size={16} />
                    <span>{t('daily.shareLink')}</span>
                  </button>
                </div>
              </div>
              {shareStatus ? <p className="share-status" role="status">{shareStatus}</p> : null}
            </>
          ) : null}
          <div className="start-actions">
            <button className="primary-action" type="button" onClick={begin} disabled={loading || !!error}>
              <span>
                {loading
                  ? t('daily.loadingMap')
                  : progress?.status === 'finished'
                    ? t('daily.viewResult')
                    : t(isSeeded ? 'daily.playMap' : 'daily.playToday')}
              </span>
              <ArrowRight size={20} />
            </button>
            <button className="secondary-action" type="button" onClick={createRandomChallenge}>
              <Dices size={18} />
              <span>{t(isSeeded ? 'daily.randomise' : 'daily.createOwn')}</span>
            </button>
            {!isSeeded && (account ? (
              <div className="account-status" aria-label={t('common.signedInAs', { username: account.username })}>
                <CircleUserRound size={19} aria-hidden="true" />
                <span>{t('common.signedInAs', { username: account.username })}</span>
              </div>
            ) : (
              <div className="account-actions">
                <button ref={loginButtonRef} className="secondary-action" type="button" onClick={openLogin}>
                  <LogIn size={18} aria-hidden="true" />
                  <span>{t('common.login')}</span>
                </button>
                <button ref={registrationButtonRef} className="secondary-action" type="button" onClick={openRegistration}>
                  <UserPlus size={18} aria-hidden="true" />
                  <span>{t('common.createAccount')}</span>
                </button>
              </div>
            ))}
          </div>
          {isSeeded ? <a className="daily-link" href="/">{t('daily.returnDaily')}</a> : null}
          {!isSeeded ? (
            <div className="start-meta" aria-label={t('daily.details')}>
              <span><strong>5</strong> {t('daily.pins')}</span>
              <span><strong>10</strong> {t('daily.guesses')}</span>
              <span><strong>1</strong> Hamburg</span>
            </div>
          ) : null}
        </section>
      ) : (
        <aside className="game-panel" aria-live="polite">
          {screen === 'finished' ? (
            <div className="game-heading">
              <p className="eyebrow">{t(isSeeded ? 'daily.sharedComplete' : 'daily.complete')}</p>
              <h1>{t(isSeeded ? 'daily.yourHamburg' : 'daily.todaysHamburg')}</h1>
              <p>
                {progress?.finishReason === 'gave_up'
                  ? t('daily.foundBeforeGivingUp', { solved: pinsSolved, total: 5 })
                  : t('daily.foundInGuesses', { solved: pinsSolved, total: 5, count: guessesSpent })}
              </p>
            </div>
          ) : null}

          {screen === 'game' ? (
            <>
              <div className="daily-game-status" aria-label={t('daily.progress')}>
                <span>{t('daily.pinsFound', { solved: pinsSolved, total: 5 })}</span>
                <span>{t('daily.guessesLeft', { count: progress?.budgetRemaining ?? 10 })}</span>
              </div>
              <form className="guess-form" onSubmit={submitGuess}>
                <label htmlFor="district-guess">{t('common.districtName')}</label>
                <div className="guess-control">
                  <input
                    ref={guessInputRef}
                    id="district-guess"
                    value={guess}
                    onChange={(event) => handleGuessChange(event.target.value)}
                    onKeyDown={handleGuessKeyDown}
                    placeholder={t('common.typeName')}
                    autoComplete="off"
                    role="combobox"
                    aria-autocomplete="list"
                    aria-controls="district-suggestions"
                    aria-expanded={suggestions.length > 0}
                    aria-activedescendant={activeSuggestionIndex >= 0 ? `district-suggestion-${suggestions[activeSuggestionIndex]?.id}` : undefined}
                    readOnly={submitting}
                  />
                </div>
                {suggestions.length > 0 ? (
                  <div className="suggestion-list" id="district-suggestions" role="listbox">
                    {suggestions.map((district, index) => (
                      <button
                        key={district.id}
                        id={`district-suggestion-${district.id}`}
                        type="button"
                        role="option"
                        aria-selected={index === activeSuggestionIndex}
                        className={index === activeSuggestionIndex ? 'suggestion-list__option suggestion-list__option--active' : 'suggestion-list__option'}
                        onMouseDown={(event) => event.preventDefault()}
                        onClick={() => chooseDistrict(district)}
                      >
                        {district.name}
                      </button>
                    ))}
                  </div>
                ) : null}
              </form>

              {feedback ? (
                <p className={`notice notice--${feedback.kind}`}>{feedback.message}</p>
              ) : null}

              <button
                className={confirmingGiveUp ? 'give-up-action give-up-action--confirm' : 'give-up-action'}
                type="button"
                onClick={() => void giveUp()}
                disabled={submitting}
              >
                <Flag size={15} />
                <span>{t(confirmingGiveUp ? 'daily.confirmGiveUp' : 'daily.giveUp')}</span>
              </button>

              {progress && progress.guessHistory.length > 0 ? (
                <details className="game-details">
                  <summary>
                    <span>{t('daily.pastGuessesCount', { count: progress.guessHistory.length })}</span>
                    <ChevronDown size={18} aria-hidden="true" />
                  </summary>
                  <div className="game-details__content">
                  <div className="pin-progress" aria-label={t('daily.pinsSolvedLabel', { solved: pinsSolved, total: 5 })}>
                    {challenge?.pins.map((pin) => (
                      <span
                        key={pin.index}
                        className={progress?.solvedPinIndices.includes(pin.index) ? 'progress-dot progress-dot--solved' : 'progress-dot'}
                      >
                        {pin.index + 1}
                      </span>
                    ))}
                  </div>
                  <section className="guess-history" aria-labelledby="guess-history-title">
                    <h2 id="guess-history-title">{t('daily.pastGuesses')}</h2>
                    <ol>
                      {[...progress.guessHistory].reverse().map((entry, reverseIndex) => (
                        <li
                          key={`${progress.guessHistory.length - reverseIndex}-${entry.districtId}`}
                          className={entry.correct
                            ? 'guess-history__item guess-history__item--correct'
                            : `guess-history__item ${entry.distanceKm !== null && entry.distanceKm >= 5 ? 'guess-history__item--far' : 'guess-history__item--near'}`}
                        >
                          <span className="guess-history__icon" aria-hidden="true">
                            {entry.correct ? <Check size={14} /> : <X size={14} />}
                          </span>
                          <strong>{entry.districtName}</strong>
                          <small>
                            {entry.correct
                              ? t('daily.pinFound', { pin: (entry.solvedPinIndex ?? 0) + 1 })
                              : new Intl.NumberFormat(activeLanguage(), { style: 'unit', unit: 'kilometer', maximumFractionDigits: 1 }).format(entry.distanceKm ?? 0)}
                          </small>
                        </li>
                      ))}
                    </ol>
                  </section>
                  </div>
                </details>
              ) : null}
            </>
          ) : (
            <div className="result-block">
              <div>
                <span>{t('daily.pinsSolved')}</span>
                <strong>{pinsSolved}<small>/5</small></strong>
              </div>
              <div>
                <span>{t('daily.guessesSpent')}</span>
                <strong>{guessesSpent}<small>/10</small></strong>
              </div>
              <p>
                {progress?.finishReason === 'gave_up'
                  ? t('daily.usedGuesses', { count: challenge?.initial_budget && progress ? challenge.initial_budget - progress.budgetRemaining : 0 })
                  : isSeeded
                  ? t('daily.seededRevealed')
                  : t('daily.dailyRevealed')}
              </p>
              <div className="result-actions">
                <button className="primary-action" type="button" onClick={createRandomChallenge}>
                  <span>{t('daily.newGame')}</span>
                  <Dices size={18} />
                </button>
                <button className="panel-secondary-action" type="button" onClick={returnToStart}>
                  <ArrowLeft size={16} />
                  <span>{t('daily.backStart')}</span>
                </button>
              </div>
            </div>
          )}

          {screen === 'finished' && progress && progress.guessHistory.length > 0 ? (
            <section className="guess-history" aria-labelledby="guess-history-title">
              <h2 id="guess-history-title">{t('daily.pastGuesses')}</h2>
              <ol>
                {[...progress.guessHistory].reverse().map((entry, reverseIndex) => (
                  <li
                    key={`${progress.guessHistory.length - reverseIndex}-${entry.districtId}`}
                    className={entry.correct
                      ? 'guess-history__item guess-history__item--correct'
                      : `guess-history__item ${entry.distanceKm !== null && entry.distanceKm >= 5 ? 'guess-history__item--far' : 'guess-history__item--near'}`}
                  >
                    <span className="guess-history__icon" aria-hidden="true">
                      {entry.correct ? <Check size={14} /> : <X size={14} />}
                    </span>
                    <strong>{entry.districtName}</strong>
                    <small>
                      {entry.correct
                        ? t('daily.pinFound', { pin: (entry.solvedPinIndex ?? 0) + 1 })
                        : new Intl.NumberFormat(activeLanguage(), { style: 'unit', unit: 'kilometer', maximumFractionDigits: 1 }).format(entry.distanceKm ?? 0)}
                    </small>
                  </li>
                ))}
              </ol>
            </section>
          ) : null}

          {screen === 'finished' ? (
            <footer className="map-key">
              <LocateFixed size={16} />
              <span>{t('daily.mapKey')}</span>
            </footer>
          ) : null}
        </aside>
      )}

      <RegisterDialog
        open={registrationOpen}
        onClose={closeRegistration}
        onRegistered={handleAuthenticated}
      />
      <LoginDialog
        open={loginOpen}
        onClose={closeLogin}
        onLoggedIn={handleAuthenticated}
      />
    </main>
  )
}

/** Normalize browser paths to the application's supported route set. */
function currentPath() {
  const path = window.location.pathname.replace(/\/+$/, '') || '/'
  return path
}

/** Render lightweight browser-history routing without adding a routing dependency. */
function App() {
  const [path, setPath] = useState(currentPath)
  const [analyticsSettingsOpen, setAnalyticsSettingsOpen] = useState(false)

  useEffect(() => {
    track('app_opened', firstTouchContext())
    const handlePopState = () => setPath(currentPath())
    window.addEventListener('popstate', handlePopState)
    return () => window.removeEventListener('popstate', handlePopState)
  }, [])

  useEffect(() => {
    const mode = path === '/' ? 'home' : path.split('/')[1]
    track('mode_opened', {
      mode,
      ...(requestedSeed && mode === 'daily' ? { seed: requestedSeed } : {}),
    })
  }, [path])

  /** Navigate to one application mode and preserve browser back behavior. */
  function navigate(nextPath: string) {
    if (nextPath !== currentPath()) window.history.pushState({}, '', nextPath)
    setPath(nextPath)
  }

  let content
  if (path === '/daily') content = <DailyApp onHome={() => navigate('/')} />
  else if (path === '/explore') content = <ExploreApp onHome={() => navigate('/')} />
  else if (path === '/training') {
    content = <TrainingApp onHome={() => navigate('/')} onNavigate={navigate} />
  } else if (path === '/training/progress') {
    content = <TrainingProgressPage onHome={() => navigate('/')} onNavigate={navigate} />
  } else if (path === '/admin') {
    content = <AdminPage onHome={() => navigate('/')} />
  } else {
    content = <ModeHome onNavigate={navigate} />
  }
  return (
    <>
      {content}
      <AppMenu
        onAnalyticsSettings={() => setAnalyticsSettingsOpen(true)}
        onNavigate={navigate}
      />
      <AnalyticsPrivacy
        settingsOpen={analyticsSettingsOpen}
        onSettingsClose={() => setAnalyticsSettingsOpen(false)}
      />
    </>
  )
}

export default App
