// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleUserRound, Compass, Copy, Dices, Flag, Home, LocateFixed, LogIn, RefreshCw, Share2, UserPlus, X } from 'lucide-react'
import { QRCodeSVG } from 'qrcode.react'
import { useTranslation } from 'react-i18next'
import { AdminPage } from './AdminPage'
import { AnalyticsPrivacy } from './AnalyticsPrivacy'
import { AppMenu } from './AppMenu'
import { AccountProvider } from './Account'
import { useAccount } from './accountContext'
import type { Account } from './accountContext'
import { ExploreApp } from './ExploreApp'
import { LeaderboardApp } from './LeaderboardApp'
import { MapView } from './MapView'
import { ModeHome } from './ModeHome'
import { pinOutcomeRow, resultShareText } from './resultShare'
import { TrainingApp, TrainingProgressPage } from './TrainingApp'
import { activeLanguage } from './i18n'
import { firstTouchContext, track } from './analytics'
import { requestedSeed, useDailyChallenge } from './useDailyChallenge'
import type { District } from './useDailyChallenge'
import './App.css'

function phraseToSeed(phrase: string) {
  return phrase
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9_-]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 64)
}

function inviteUrl(seed: string) {
  const url = new URL(window.location.origin)
  url.searchParams.set('seed', seed)
  return url.toString()
}

/** Preserve the existing Daily Challenge behavior at its dedicated route. */
function DailyApp({ onHome }: { onHome: () => void }) {
  const { t } = useTranslation()
  const {
    account,
    error: accountStatusError,
    clearError: clearAccountError,
    openLogin: showLogin,
    openRegistration: showRegistration,
  } = useAccount()
  const {
    screen,
    challenge,
    districts,
    progress,
    feedback,
    loading,
    submitting,
    error,
    leaderboard,
    leaderboardError,
    setFeedback,
    begin: beginWorkflow,
    returnToStart: returnWorkflowToStart,
    checkGuess: submitWorkflowGuess,
    giveUp: giveUpWorkflow,
    handleAuthenticated: continueAuthenticatedWorkflow,
    loadLeaderboard,
  } = useDailyChallenge(account)
  const [guess, setGuess] = useState('')
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(-1)
  const [confirmingGiveUp, setConfirmingGiveUp] = useState(false)
  const [accountProgressError, setAccountProgressError] = useState<string | null>(null)
  const [shareLabel, setShareLabel] = useState<'copy' | 'copied' | 'failed'>('copy')
  const [shareStatus, setShareStatus] = useState<string | null>(null)
  const [resultShareStatus, setResultShareStatus] = useState<string | null>(null)
  const [customPhrase, setCustomPhrase] = useState(requestedSeed ?? '')
  const [creatorError, setCreatorError] = useState<string | null>(null)
  const guessInputRef = useRef<HTMLInputElement>(null)
  const loginButtonRef = useRef<HTMLButtonElement>(null)
  const registrationButtonRef = useRef<HTMLButtonElement>(null)

  /** Open login without changing anonymous Daily Challenge state. */
  function openLogin() {
    clearAccountError()
    setAccountProgressError(null)
    showLogin({
      onAuthenticated: handleAuthenticated,
      onClose: () => requestAnimationFrame(() => loginButtonRef.current?.focus()),
    })
  }

  /** Open registration without changing anonymous Daily Challenge state. */
  function openRegistration() {
    clearAccountError()
    setAccountProgressError(null)
    showRegistration({
      onAuthenticated: handleAuthenticated,
      onClose: () => requestAnimationFrame(() => registrationButtonRef.current?.focus()),
    })
  }

  /** Retain a new session, adopting a completed anonymous Daily where requested. */
  async function handleAuthenticated(authenticatedAccount: Account) {
    setAccountProgressError(null)
    try {
      await continueAuthenticatedWorkflow(authenticatedAccount)
    } catch {
      setAccountProgressError(t('daily.accountProgressError'))
    }
  }

  function begin() {
    beginWorkflow()
    requestAnimationFrame(() => guessInputRef.current?.focus())
  }

  function returnToStart() {
    setConfirmingGiveUp(false)
    returnWorkflowToStart()
  }

  function createRandomChallenge() {
    const values = crypto.getRandomValues(new Uint32Array(2))
    const seed = Array.from(values, (value) => value.toString(36)).join('-')
    window.location.assign(`/daily?seed=${seed}`)
  }

  async function copyInviteLink() {
    if (!challenge || challenge.mode !== 'seeded') return
    try {
      await navigator.clipboard.writeText(inviteUrl(challenge.id))
      setShareLabel('copied')
      setShareStatus(t('daily.inviteCopied'))
    } catch {
      setShareLabel('failed')
      setShareStatus(t('daily.clipboardBlocked'))
    }
  }

  async function shareInviteLink() {
    if (!challenge || challenge.mode !== 'seeded') return
    if (!navigator.share) {
      await copyInviteLink()
      return
    }
    try {
      await navigator.share({
        title: 'Hamburg Whereabouts',
        text: t('daily.shareText'),
        url: inviteUrl(challenge.id),
      })
      setShareStatus(t('daily.inviteShared'))
    } catch (reason) {
      if (reason instanceof DOMException && reason.name === 'AbortError') return
      setShareStatus(t('daily.shareFailed'))
    }
  }

  async function copyResult(resultText: string, resultUrl: string) {
    try {
      await navigator.clipboard.writeText(`${resultText}\n${resultUrl}`)
      setResultShareStatus(t('daily.resultCopied'))
      track(challenge?.mode === 'seeded' ? 'seeded_result_shared' : 'daily_result_shared', { method: 'clipboard' })
    } catch {
      setResultShareStatus(t('daily.clipboardBlocked'))
    }
  }

  async function shareResult(resultText: string, resultUrl: string) {
    if (!challenge || !progress || progress.status !== 'finished') return
    if (!navigator.share) {
      await copyResult(resultText, resultUrl)
      return
    }
    try {
      await navigator.share({
        title: 'Hamburg Whereabouts',
        text: resultText,
        url: resultUrl,
      })
      setResultShareStatus(t('daily.resultShared'))
      track(challenge.mode === 'seeded' ? 'seeded_result_shared' : 'daily_result_shared', { method: 'native' })
    } catch (reason) {
      if (reason instanceof DOMException && reason.name === 'AbortError') return
      setResultShareStatus(t('daily.resultShareFailed'))
    }
  }

  function previewCustomPhrase(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const seed = phraseToSeed(customPhrase)
    if (seed.length < 3) {
      setCreatorError(t('daily.phraseValidation'))
      return
    }
    window.location.assign(`/?seed=${seed}`)
  }

  function findDistrict(value: string) {
    const normalized = value.trim().toLocaleLowerCase('de')
    return districts.find(
      (district) => district.name.toLocaleLowerCase('de') === normalized,
    )
  }

  async function checkGuess(district: District) {
    const duplicate = progress?.guessHistory.some((entry) => entry.districtId === district.id) ?? false
    setConfirmingGiveUp(false)
    const accepted = await submitWorkflowGuess(district)
    if (accepted || duplicate) {
      setGuess('')
      setActiveSuggestionIndex(-1)
    }
    requestAnimationFrame(() => guessInputRef.current?.focus())
  }

  async function giveUp() {
    if (!confirmingGiveUp) {
      setConfirmingGiveUp(true)
      return
    }
    await giveUpWorkflow()
    setConfirmingGiveUp(false)
  }

  function handleGuessChange(value: string) {
    setGuess(value)
    setActiveSuggestionIndex(-1)
  }

  function chooseDistrict(district: District) {
    setGuess(district.name)
    setActiveSuggestionIndex(-1)
    void checkGuess(district)
  }

  function handleGuessKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'ArrowDown' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (current + 1) % suggestions.length)
      return
    }
    if (event.key === 'ArrowUp' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (
        current <= 0 ? suggestions.length - 1 : current - 1
      ))
      return
    }
    if (event.key === 'Escape') {
      setGuess('')
      setActiveSuggestionIndex(-1)
      return
    }
    if (event.key !== 'Enter') return

    event.preventDefault()
    const selected = suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(guess)
    if (selected) {
      chooseDistrict(selected)
      return
    }
    setFeedback({ kind: 'error', message: t('common.chooseSuggestions') })
  }

  function submitGuess(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const district = suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(guess)
    if (district) {
      chooseDistrict(district)
      return
    }
    setFeedback({ kind: 'error', message: t('common.chooseList') })
  }

  const formattedDate = challenge?.date
    ? new Intl.DateTimeFormat(activeLanguage(), {
        weekday: 'long',
        day: 'numeric',
        month: 'long',
      }).format(new Date(`${challenge.date}T12:00:00`))
    : t('common.today')
  const isSeeded = challenge?.mode === 'seeded'
  const currentInviteUrl = isSeeded && challenge ? inviteUrl(challenge.id) : ''
  const normalizedCustomSeed = phraseToSeed(customPhrase)
  const pinsSolved = progress?.solvedPinIndices.length ?? 0
  const guessesSpent = challenge && progress
    ? challenge.initial_budget - progress.budgetRemaining
    : 0
  const resultDate = challenge?.date
    ? new Intl.DateTimeFormat(activeLanguage(), {
        day: 'numeric',
        month: 'long',
        year: 'numeric',
      }).format(new Date(`${challenge.date}T12:00:00`))
    : ''
  const resultUrl = challenge
    ? challenge.mode === 'seeded'
      ? inviteUrl(challenge.id)
      : new URL('/daily', window.location.origin).toString()
    : ''
  const resultText = challenge && progress
    ? resultShareText({
        productName: 'Hamburg Whereabouts',
        challengeLabel: challenge.mode === 'seeded'
          ? t('daily.resultSharedMap')
          : t('daily.resultDaily', { date: resultDate }),
        score: t(progress.finishReason === 'gave_up' ? 'daily.resultScoreGaveUp' : 'daily.resultScore', {
          solved: pinsSolved,
          total: challenge.pins.length,
          spent: guessesSpent,
          budget: challenge.initial_budget,
          count: guessesSpent,
        }),
        outcomeRow: pinOutcomeRow(challenge.pins.length, progress.solvedPinIndices),
      })
    : ''
  const normalizedGuess = guess.trim().toLocaleLowerCase('de')
  const suggestions = normalizedGuess.length === 0
    ? []
    : districts.filter((district) => (
        district.name.toLocaleLowerCase('de').includes(normalizedGuess)
      ))

  return (
    <main className={`app-shell app-shell--${screen}`}>
      <MapView
        pins={challenge?.pins ?? []}
        reveals={progress?.reveals ?? []}
        missedDistricts={progress?.missedDistricts ?? []}
        solvedPinIndices={progress?.solvedPinIndices ?? []}
        showPins={screen !== 'start' || isSeeded}
        previewMode={screen === 'start' && isSeeded}
        annotateMissedDistricts={screen === 'finished' && !isSeeded}
      />

      <header className="brand-bar">
        <button className="brand-home" type="button" onClick={onHome} aria-label={t('common.returnModes')} title={t('common.home')}>
          <Home size={17} aria-hidden="true" />
        </button>
        <span className="brand-mark"><Compass size={18} strokeWidth={2.4} /></span>
        <span>Hamburg Whereabouts</span>
      </header>

      {screen === 'start' ? (
        <section className={isSeeded ? 'start-panel start-panel--seeded' : 'start-panel'} aria-labelledby="start-title">
          <p className="eyebrow">
            {isSeeded ? t('daily.sharedMap', { seed: challenge.id }) : t('daily.dailyDistricts', { date: formattedDate })}
          </p>
          <h1 id="start-title">
            {t(isSeeded ? 'daily.seededTitle' : 'daily.title')}
          </h1>
          <p className="start-copy">
            {isSeeded
              ? t('daily.seededIntro')
              : t('daily.intro')}
          </p>
          {error ? <p className="notice notice--error">{error}</p> : null}
          {accountStatusError || accountProgressError ? <p className="notice notice--error">{accountStatusError ?? accountProgressError}</p> : null}
          {isSeeded ? (
            <>
              <form className="seed-form" onSubmit={previewCustomPhrase}>
                <label htmlFor="custom-seed">{t('daily.customPhrase')}</label>
                <div className="seed-control">
                  <input
                    id="custom-seed"
                    value={customPhrase}
                    maxLength={80}
                    onChange={(event) => {
                      setCustomPhrase(event.target.value)
                      setCreatorError(null)
                    }}
                    placeholder={t('daily.phrasePlaceholder')}
                  />
                  <button type="submit" disabled={normalizedCustomSeed.length < 3}>
                    <RefreshCw size={16} />
                    <span>{t('daily.preview')}</span>
                  </button>
                </div>
                <p className={creatorError ? 'seed-help seed-help--error' : 'seed-help'}>
                  {creatorError ?? t('daily.seed', { seed: normalizedCustomSeed || t('daily.typePhrase') })}
                </p>
              </form>
              <div className="share-panel">
                <div className="qr-code" role="img" aria-label={t('daily.qrLabel')}>
                  <QRCodeSVG value={currentInviteUrl} size={88} bgColor="#ffffff" fgColor="#17201c" level="M" />
                </div>
                <div className="share-panel__actions">
                  <strong>{t('daily.invitePlayers')}</strong>
                  <button className="secondary-action" type="button" onClick={() => void copyInviteLink()}>
                    <Copy size={16} />
                    <span>{t(shareLabel === 'copy' ? 'daily.copyInvite' : shareLabel === 'copied' ? 'daily.linkCopied' : 'daily.copyFailed')}</span>
                  </button>
                  <button className="secondary-action" type="button" onClick={() => void shareInviteLink()}>
                    <Share2 size={16} />
                    <span>{t('daily.shareLink')}</span>
                  </button>
                </div>
              </div>
              {shareStatus ? <p className="share-status" role="status">{shareStatus}</p> : null}
            </>
          ) : null}
          <div className="start-actions">
            <button className="primary-action" type="button" onClick={begin} disabled={loading || !!error}>
              <span>
                {loading
                  ? t('daily.loadingMap')
                  : progress?.status === 'finished'
                    ? t('daily.viewResult')
                    : t(isSeeded ? 'daily.playMap' : 'daily.playToday')}
              </span>
              <ArrowRight size={20} />
            </button>
            <button className="secondary-action" type="button" onClick={createRandomChallenge}>
              <Dices size={18} />
              <span>{t(isSeeded ? 'daily.randomise' : 'daily.createOwn')}</span>
            </button>
            {!isSeeded && (account ? (
              <div className="account-status" aria-label={t('common.signedInAs', { username: account.username })}>
                <CircleUserRound size={19} aria-hidden="true" />
                <span>{t('common.signedInAs', { username: account.username })}</span>
              </div>
            ) : (
              <div className="account-actions">
                <button ref={loginButtonRef} className="secondary-action" type="button" onClick={openLogin}>
                  <LogIn size={18} aria-hidden="true" />
                  <span>{t('common.login')}</span>
                </button>
                <button ref={registrationButtonRef} className="secondary-action" type="button" onClick={openRegistration}>
                  <UserPlus size={18} aria-hidden="true" />
                  <span>{t('common.createAccount')}</span>
                </button>
              </div>
            ))}
          </div>
          {isSeeded ? <a className="daily-link" href="/">{t('daily.returnDaily')}</a> : null}
          {!isSeeded ? (
            <div className="start-meta" aria-label={t('daily.details')}>
              <span><strong>5</strong> {t('daily.pins')}</span>
              <span><strong>10</strong> {t('daily.guesses')}</span>
              <span><strong>1</strong> Hamburg</span>
            </div>
          ) : null}
        </section>
      ) : (
        <aside className="game-panel" aria-live="polite">
          {screen === 'finished' ? (
            <div className="game-heading">
              <p className="eyebrow">{t(isSeeded ? 'daily.sharedComplete' : 'daily.complete')}</p>
              <h1>{t(isSeeded ? 'daily.yourHamburg' : 'daily.todaysHamburg')}</h1>
              <p>
                {progress?.finishReason === 'gave_up'
                  ? t('daily.foundBeforeGivingUp', { solved: pinsSolved, total: 5 })
                  : t('daily.foundInGuesses', { solved: pinsSolved, total: 5, count: guessesSpent })}
              </p>
            </div>
          ) : null}

          {screen === 'game' ? (
            <>
              <div className="daily-game-status" aria-label={t('daily.progress')}>
                <span>{t('daily.pinsFound', { solved: pinsSolved, total: 5 })}</span>
                <span>{t('daily.guessesLeft', { count: progress?.budgetRemaining ?? 10 })}</span>
              </div>
              <form className="guess-form" onSubmit={submitGuess}>
                <label htmlFor="district-guess">{t('common.districtName')}</label>
                <div className="guess-control">
                  <input
                    ref={guessInputRef}
                    id="district-guess"
                    value={guess}
                    onChange={(event) => handleGuessChange(event.target.value)}
                    onKeyDown={handleGuessKeyDown}
                    placeholder={t('common.typeName')}
                    autoComplete="off"
                    role="combobox"
                    aria-autocomplete="list"
                    aria-controls="district-suggestions"
                    aria-expanded={suggestions.length > 0}
                    aria-activedescendant={activeSuggestionIndex >= 0 ? `district-suggestion-${suggestions[activeSuggestionIndex]?.id}` : undefined}
                    readOnly={submitting}
                  />
                </div>
                {suggestions.length > 0 ? (
                  <div className="suggestion-list" id="district-suggestions" role="listbox">
                    {suggestions.map((district, index) => (
                      <button
                        key={district.id}
                        id={`district-suggestion-${district.id}`}
                        type="button"
                        role="option"
                        aria-selected={index === activeSuggestionIndex}
                        className={index === activeSuggestionIndex ? 'suggestion-list__option suggestion-list__option--active' : 'suggestion-list__option'}
                        onMouseDown={(event) => event.preventDefault()}
                        onClick={() => chooseDistrict(district)}
                      >
                        {district.name}
                      </button>
                    ))}
                  </div>
                ) : null}
              </form>

              {feedback ? (
                <p className={`notice notice--${feedback.kind}`}>{feedback.message}</p>
              ) : null}

              <button
                className={confirmingGiveUp ? 'give-up-action give-up-action--confirm' : 'give-up-action'}
                type="button"
                onClick={() => void giveUp()}
                disabled={submitting}
              >
                <Flag size={15} />
                <span>{t(confirmingGiveUp ? 'daily.confirmGiveUp' : 'daily.giveUp')}</span>
              </button>

              {progress && progress.guessHistory.length > 0 ? (
                <details className="game-details">
                  <summary>
                    <span>{t('daily.pastGuessesCount', { count: progress.guessHistory.length })}</span>
                    <ChevronDown size={18} aria-hidden="true" />
                  </summary>
                  <div className="game-details__content">
                  <div className="pin-progress" aria-label={t('daily.pinsSolvedLabel', { solved: pinsSolved, total: 5 })}>
                    {challenge?.pins.map((pin) => (
                      <span
                        key={pin.index}
                        className={progress?.solvedPinIndices.includes(pin.index) ? 'progress-dot progress-dot--solved' : 'progress-dot'}
                      >
                        {pin.index + 1}
                      </span>
                    ))}
                  </div>
                  <section className="guess-history" aria-labelledby="guess-history-title">
                    <h2 id="guess-history-title">{t('daily.pastGuesses')}</h2>
                    <ol>
                      {[...progress.guessHistory].reverse().map((entry, reverseIndex) => (
                        <li
                          key={`${progress.guessHistory.length - reverseIndex}-${entry.districtId}`}
                          className={entry.correct
                            ? 'guess-history__item guess-history__item--correct'
                            : `guess-history__item ${entry.distanceKm !== null && entry.distanceKm >= 5 ? 'guess-history__item--far' : 'guess-history__item--near'}`}
                        >
                          <span className="guess-history__icon" aria-hidden="true">
                            {entry.correct ? <Check size={14} /> : <X size={14} />}
                          </span>
                          <strong>{entry.districtName}</strong>
                          <small>
                            {entry.correct
                              ? t('daily.pinFound', { pin: (entry.solvedPinIndex ?? 0) + 1 })
                              : new Intl.NumberFormat(activeLanguage(), { style: 'unit', unit: 'kilometer', maximumFractionDigits: 1 }).format(entry.distanceKm ?? 0)}
                          </small>
                        </li>
                      ))}
                    </ol>
                  </section>
                  </div>
                </details>
              ) : null}
            </>
          ) : (
            <div className="result-block">
              <div className="result-stat">
                <span>{t('daily.pinsSolved')}</span>
                <strong>{pinsSolved}<small>/5</small></strong>
              </div>
              <div className="result-stat">
                <span>{t('daily.guessesSpent')}</span>
                <strong>{guessesSpent}<small>/10</small></strong>
              </div>
              <p>
                {progress?.finishReason === 'gave_up'
                  ? t('daily.usedGuesses', { count: challenge?.initial_budget && progress ? challenge.initial_budget - progress.budgetRemaining : 0 })
                  : isSeeded
                  ? t('daily.seededRevealed')
                  : t('daily.dailyRevealed')}
              </p>
              {challenge && progress ? (
                <div className="result-share">
                  <button className="result-share__action" type="button" onClick={() => void shareResult(resultText, resultUrl)}>
                    <Share2 size={17} aria-hidden="true" />
                    <span>{t('daily.shareResult')}</span>
                  </button>
                  {resultShareStatus ? <div className="result-share__status" role="status">{resultShareStatus}</div> : null}
                </div>
              ) : null}
              {!isSeeded && !account && challenge?.state_source === 'anonymous' ? (
                <section className="result-account" aria-label={t('daily.saveResult')}>
                  <p>{t('daily.saveResultHelp')}</p>
                  <div className="result-account__actions">
                    <button type="button" onClick={openLogin}>{t('daily.loginSaveResult')}</button>
                    <button type="button" onClick={openRegistration}>{t('daily.createAccountSaveResult')}</button>
                  </div>
                </section>
              ) : null}
              {!isSeeded && leaderboard ? (
                <section className="leaderboard-summary" aria-labelledby="leaderboard-summary-title">
                  <div className="leaderboard-summary__hero">
                    <span>Today’s standings</span>
                    <strong id="leaderboard-summary-title">#{leaderboard.your_entry.rank}</strong>
                    <p>of {leaderboard.player_count} completed players</p>
                  </div>
                  <div className="leaderboard-summary__score">
                    <span><strong>{leaderboard.your_entry.pins_solved}/5</strong> pins</span>
                    <span><strong>{leaderboard.your_entry.guesses_used}</strong> guesses</span>
                    <span><strong>{leaderboard.your_entry.total_missed_distance_km.toFixed(1)} km</strong> missed</span>
                  </div>
                  <ol className="leaderboard-summary__entries">{leaderboard.context_entries.map((entry) => (
                    <li className={entry.is_you ? 'leaderboard-summary__entry leaderboard-summary__entry--you' : 'leaderboard-summary__entry'} key={entry.username}>
                      <strong>#{entry.rank}</strong><span>{entry.is_you ? 'You' : entry.username}</span><small>{entry.pins_solved}/5 · {entry.guesses_used} · {entry.total_missed_distance_km.toFixed(1)} km</small>
                    </li>
                  ))}</ol>
                  <div className="leaderboard-summary__actions">
                    <button className="panel-secondary-action" type="button" onClick={() => void loadLeaderboard(leaderboard.date)}>Refresh</button>
                    <a className="panel-secondary-action" href="/leaderboard">Past days</a>
                  </div>
                  {leaderboardError ? <p className="notice notice--error">{leaderboardError}</p> : null}
                </section>
              ) : null}
              <div className="result-actions">
                <button className="primary-action" type="button" onClick={createRandomChallenge}>
                  <span>{t('daily.newGame')}</span>
                  <Dices size={18} />
                </button>
                <button className="panel-secondary-action" type="button" onClick={returnToStart}>
                  <ArrowLeft size={16} />
                  <span>{t('daily.backStart')}</span>
                </button>
              </div>
            </div>
          )}

          {screen === 'finished' && progress && progress.guessHistory.length > 0 ? (
            <section className="guess-history" aria-labelledby="guess-history-title">
              <h2 id="guess-history-title">{t('daily.pastGuesses')}</h2>
              <ol>
                {[...progress.guessHistory].reverse().map((entry, reverseIndex) => (
                  <li
                    key={`${progress.guessHistory.length - reverseIndex}-${entry.districtId}`}
                    className={entry.correct
                      ? 'guess-history__item guess-history__item--correct'
                      : `guess-history__item ${entry.distanceKm !== null && entry.distanceKm >= 5 ? 'guess-history__item--far' : 'guess-history__item--near'}`}
                  >
                    <span className="guess-history__icon" aria-hidden="true">
                      {entry.correct ? <Check size={14} /> : <X size={14} />}
                    </span>
                    <strong>{entry.districtName}</strong>
                    <small>
                      {entry.correct
                        ? t('daily.pinFound', { pin: (entry.solvedPinIndex ?? 0) + 1 })
                        : new Intl.NumberFormat(activeLanguage(), { style: 'unit', unit: 'kilometer', maximumFractionDigits: 1 }).format(entry.distanceKm ?? 0)}
                    </small>
                  </li>
                ))}
              </ol>
            </section>
          ) : null}

          {screen === 'finished' ? (
            <footer className="map-key">
              <LocateFixed size={16} />
              <span>{t('daily.mapKey')}</span>
            </footer>
          ) : null}
        </aside>
      )}

    </main>
  )
}

/** Normalize browser paths to the application's supported route set. */
function currentPath() {
  const path = window.location.pathname.replace(/\/+$/, '') || '/'
  return path
}

/** Render lightweight browser-history routing without adding a routing dependency. */
function App() {
  const [path, setPath] = useState(currentPath)
  const [analyticsSettingsOpen, setAnalyticsSettingsOpen] = useState(false)

  useEffect(() => {
    track('app_opened', firstTouchContext())
    const handlePopState = () => setPath(currentPath())
    window.addEventListener('popstate', handlePopState)
    return () => window.removeEventListener('popstate', handlePopState)
  }, [])

  useEffect(() => {
    const mode = path === '/' ? 'home' : path.split('/')[1]
    track('mode_opened', {
      mode,
      ...(requestedSeed && mode === 'daily' ? { seed: requestedSeed } : {}),
    })
  }, [path])

  /** Navigate to one application mode and preserve browser back behavior. */
  function navigate(nextPath: string) {
    if (nextPath !== currentPath()) window.history.pushState({}, '', nextPath)
    setPath(nextPath)
  }

  let content
  if (path === '/daily') content = <DailyApp onHome={() => navigate('/')} />
  else if (path === '/explore') content = <ExploreApp onHome={() => navigate('/')} />
  else if (path === '/leaderboard') content = <LeaderboardApp onHome={() => navigate('/')} />
  else if (path === '/training') {
    content = <TrainingApp onHome={() => navigate('/')} onNavigate={navigate} />
  } else if (path === '/training/progress') {
    content = <TrainingProgressPage onHome={() => navigate('/')} onNavigate={navigate} />
  } else if (path === '/admin') {
    content = <AdminPage onHome={() => navigate('/')} />
  } else {
    content = <ModeHome onNavigate={navigate} />
  }
  return (
    <AccountProvider>
      {content}
      <AppMenu
        onAnalyticsSettings={() => setAnalyticsSettingsOpen(true)}
        onNavigate={navigate}
      />
      <AnalyticsPrivacy
        settingsOpen={analyticsSettingsOpen}
        onSettingsClose={() => setAnalyticsSettingsOpen(false)}
      />
    </AccountProvider>
  )
}

export default App
