// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, SyntheticEvent } from 'react'
import { LogIn, X } from 'lucide-react'
import type { Account } from './RegisterDialog'
import { ApiError, apiFetch } from './api'

type LoginDialogProps = {
  open: boolean
  onClose: () => void
  onLoggedIn: (account: Account) => void
}

/** Render an accessible modal for signing in to an existing Account. */
export function LoginDialog({ open, onClose, onLoggedIn }: LoginDialogProps) {
  const dialogRef = useRef<HTMLDialogElement>(null)
  const usernameRef = useRef<HTMLInputElement>(null)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    const dialog = dialogRef.current
    if (!dialog) return
    if (open && !dialog.open) {
      dialog.showModal()
      usernameRef.current?.focus()
    } else if (!open && dialog.open) {
      dialog.close()
    }
  }, [open])

  /** Clear credentials before returning focus to the opener. */
  function closeDialog() {
    if (submitting) return
    setUsername('')
    setPassword('')
    setError(null)
    onClose()
  }

  /** Close the controlled dialog when the browser receives Escape. */
  function handleCancel(event: SyntheticEvent<HTMLDialogElement>) {
    event.preventDefault()
    closeDialog()
  }

  /** Verify credentials and retain the authenticated Account. */
  async function submitLogin(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)
    setSubmitting(true)
    try {
      const account = await apiFetch<Account>('/api/auth/login', {
        method: 'POST',
        body: JSON.stringify({ username, password }),
      })
      setPassword('')
      onLoggedIn(account)
      onClose()
    } catch (reason) {
      setError(
        reason instanceof ApiError && reason.status === 401
          ? 'Username or password is incorrect.'
          : reason instanceof ApiError && reason.status === 422
            ? 'Enter a valid username and password.'
            : reason instanceof Error
              ? reason.message
              : 'Could not log in.',
      )
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <dialog
      ref={dialogRef}
      className="register-dialog"
      aria-labelledby="login-title"
      aria-describedby="login-progress-note"
      onCancel={handleCancel}
    >
      <div className="register-dialog__heading">
        <span className="register-dialog__icon" aria-hidden="true">
          <LogIn size={20} />
        </span>
        <h2 id="login-title">Log in</h2>
        <button
          className="icon-action"
          type="button"
          aria-label="Close login"
          onClick={closeDialog}
          disabled={submitting}
        >
          <X size={19} />
        </button>
      </div>

      <form className="register-form" onSubmit={submitLogin}>
        <label htmlFor="login-username">Username</label>
        <input
          ref={usernameRef}
          id="login-username"
          name="username"
          type="text"
          autoComplete="username"
          autoFocus
          minLength={3}
          maxLength={32}
          value={username}
          onChange={(event) => setUsername(event.target.value)}
          disabled={submitting}
          required
        />

        <label htmlFor="login-password">Password</label>
        <input
          id="login-password"
          name="password"
          type="password"
          autoComplete="current-password"
          minLength={8}
          maxLength={128}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          disabled={submitting}
          required
        />

        <p className="register-form__error" role="status" aria-live="polite">
          {error}
        </p>
        <p id="login-progress-note" className="register-form__note">
          Your Daily Challenge progress is restored when you sign in.
        </p>
        <button className="primary-action" type="submit" disabled={submitting}>
          <span>{submitting ? 'Logging in…' : 'Log in'}</span>
          <LogIn size={19} />
        </button>
      </form>
    </dialog>
  )
}