// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import {
  ArrowRight,
  CalendarDays,
  CircleUserRound,
  Compass,
  GraduationCap,
  LockKeyhole,
  LogIn,
  LogOut,
  MapPinned,
  Trophy,
  UserPlus,
} from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { ApiError, apiErrorMessage, apiFetch } from './api'
import i18n from './i18n'
import { LoginDialog } from './LoginDialog'
import { MapView } from './MapView'
import type { Account } from './RegisterDialog'
import { RegisterDialog } from './RegisterDialog'

type ModeHomeProps = {
  onNavigate: (path: string) => void
}

/** Present the Daily, Training, and Explore application modes. */
export function ModeHome({ onNavigate }: ModeHomeProps) {
  const { t } = useTranslation()
  const [account, setAccount] = useState<Account | null>(null)
  const [accountError, setAccountError] = useState<string | null>(null)
  const [loginOpen, setLoginOpen] = useState(false)
  const [registrationOpen, setRegistrationOpen] = useState(false)
  const [trainingPending, setTrainingPending] = useState(false)
  const [signingOut, setSigningOut] = useState(false)
  const loginButtonRef = useRef<HTMLButtonElement>(null)
  const registrationButtonRef = useRef<HTMLButtonElement>(null)


  useEffect(() => {
    let cancelled = false
    apiFetch<Account>('/api/auth/me')
      .then((currentAccount) => {
        if (!cancelled) setAccount(currentAccount)
      })
      .catch((reason: unknown) => {
        if (!cancelled && !(reason instanceof ApiError && reason.status === 401)) {
          setAccountError(i18n.t('common.accountStatusError'))
        }
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Open authentication while retaining Training as the intended destination. */
  function requestTraining() {
    if (account) {
      onNavigate('/training')
      return
    }
    setTrainingPending(true)
    setLoginOpen(true)
  }

  /** Continue to Training after either successful authentication path. */
  function handleAuthenticated(authenticatedAccount: Account) {
    setAccount(authenticatedAccount)
    setAccountError(null)
    setLoginOpen(false)
    setRegistrationOpen(false)
    if (trainingPending) onNavigate('/training')
  }

  /** Clear the Account session while keeping the mode selection open. */
  async function signOut() {
    if (signingOut) return
    setSigningOut(true)
    setAccountError(null)
    try {
      await apiFetch<{ status: string }>('/api/auth/logout', { method: 'POST' })
      setAccount(null)
      setTrainingPending(false)
    } catch (reason) {
      setAccountError(apiErrorMessage(reason, t, 'common.logoutError'))
    } finally {
      setSigningOut(false)
    }
  }

  /** Close login and restore focus to the mode that opened it. */
  function closeLogin() {
    setLoginOpen(false)
    setTrainingPending(false)
    requestAnimationFrame(() => loginButtonRef.current?.focus())
  }

  /** Close registration and restore focus to its launcher. */
  function closeRegistration() {
    setRegistrationOpen(false)
    requestAnimationFrame(() => registrationButtonRef.current?.focus())
  }

  return (
    <main className="mode-home">
      <MapView pins={[]} reveals={[]} missedDistricts={[]} solvedPinIndices={[]} showPins={false} previewMode={false} annotateMissedDistricts={false} />
      <header className="brand-bar mode-home__brand">
        <span className="brand-mark"><Compass size={18} strokeWidth={2.4} /></span>
        <span>Hamburg Whereabouts</span>
      </header>
      <section className="mode-picker" aria-labelledby="mode-title">
        <div className="mode-picker__heading">
          <p className="eyebrow">{t('home.eyebrow')}</p>
          <h1 id="mode-title">{t('home.title')}</h1>
          <p>{t('home.subtitle')}</p>
        </div>
        {accountError ? <p className="notice notice--error" role="alert">{accountError}</p> : null}
        <div className="mode-options">
          <button className="mode-option mode-option--daily" type="button" onClick={() => onNavigate('/daily')}>
            <span className="mode-option__icon"><CalendarDays aria-hidden="true" /></span>
            <span className="mode-option__copy"><strong>{t('home.daily')}</strong><small>{t('home.dailyHelp')}</small></span>
            <ArrowRight size={20} aria-hidden="true" />
          </button>
          <button ref={loginButtonRef} className="mode-option mode-option--training" type="button" onClick={requestTraining}>
            <span className="mode-option__icon"><GraduationCap aria-hidden="true" /></span>
            <span className="mode-option__copy"><strong>{t('home.training')}</strong><small>{t('home.trainingHelp')}</small></span>
            {account ? <ArrowRight size={20} aria-hidden="true" /> : <LockKeyhole size={19} aria-label={t('home.trainingRequiresLogin')} />}
          </button>
          <button className="mode-option mode-option--explore" type="button" onClick={() => onNavigate('/explore')}>
            <span className="mode-option__icon"><MapPinned aria-hidden="true" /></span>
            <span className="mode-option__copy"><strong>{t('home.explore')}</strong><small>{t('home.exploreHelp')}</small></span>
            <ArrowRight size={20} aria-hidden="true" />
          </button>
          <button className="mode-option mode-option--training" type="button" onClick={() => onNavigate('/leaderboard')}>
            <span className="mode-option__icon"><Trophy aria-hidden="true" /></span>
            <span className="mode-option__copy"><strong>Leaderboard</strong><small>Compare your completed Daily games.</small></span>
            {account ? <ArrowRight size={20} aria-hidden="true" /> : <LockKeyhole size={19} aria-label="Sign in required" />}
          </button>
        </div>
        <div className="mode-account">
          {account ? (
            <>
              <div className="account-status account-status--light" aria-label={t('common.signedInAs', { username: account.username })}>
                <CircleUserRound size={18} aria-hidden="true" />
                <span>{t('common.signedInAs', { username: account.username })}</span>
              </div>
              <button type="button" disabled={signingOut} onClick={() => void signOut()}>
                <LogOut size={17} aria-hidden="true" /> {signingOut ? t('common.loggingOut') : t('common.logout')}
              </button>
            </>
          ) : (
            <>
              <button type="button" onClick={() => setLoginOpen(true)}><LogIn size={17} /> {t('common.login')}</button>
              <button ref={registrationButtonRef} type="button" onClick={() => setRegistrationOpen(true)}><UserPlus size={17} /> {t('common.createAccount')}</button>
            </>
          )}
        </div>
      </section>
      <LoginDialog open={loginOpen} onClose={closeLogin} onLoggedIn={handleAuthenticated} />
      <RegisterDialog open={registrationOpen} onClose={closeRegistration} onRegistered={handleAuthenticated} />
    </main>
  )
}
