// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, SyntheticEvent } from 'react'
import { UserPlus, X } from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { ApiError, apiErrorMessage } from './api'

type RegisterDialogProps = {
  open: boolean
  onClose: () => void
  onSubmit: (credentials: { username: string; password: string }) => Promise<void>
}

/** Render an accessible modal that creates and signs in an Account. */
export function RegisterDialog({
  open,
  onClose,
  onSubmit,
}: RegisterDialogProps) {
  const { t } = useTranslation()
  const dialogRef = useRef<HTMLDialogElement>(null)
  const usernameRef = useRef<HTMLInputElement>(null)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)


  useEffect(() => {
    const dialog = dialogRef.current
    if (!dialog) return
    if (open && !dialog.open) {
      dialog.showModal()
      usernameRef.current?.focus()
    } else if (!open && dialog.open) {
      dialog.close()
    }
  }, [open])

  /** Clear sensitive values before returning focus to the opener. */
  function closeDialog() {
    if (submitting) return
    setUsername('')
    setPassword('')
    setPasswordConfirmation('')
    setError(null)
    onClose()
  }

  /** Close the controlled dialog when the browser receives Escape. */
  function handleCancel(event: SyntheticEvent<HTMLDialogElement>) {
    event.preventDefault()
    closeDialog()
  }

  /** Validate confirmation and submit credentials to the registration API. */
  async function submitRegistration(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)
    if (password !== passwordConfirmation) {
      setError(t('auth.passwordMismatch'))
      return
    }

    setSubmitting(true)
    try {
      await onSubmit({ username, password })
      setPassword('')
      setPasswordConfirmation('')
      onClose()
    } catch (reason) {
      setError(
        reason instanceof ApiError && reason.status === 409
          ? t('common.errorByCode.auth_username_taken')
          : reason instanceof ApiError && reason.status === 422
            ? t('auth.registerValidation')
            : apiErrorMessage(reason, t, 'auth.registerError'),
      )
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <dialog
      ref={dialogRef}
      className="register-dialog"
      aria-labelledby="register-title"
      aria-describedby="register-progress-note"
      onCancel={handleCancel}
    >
      <div className="register-dialog__heading">
        <span className="register-dialog__icon" aria-hidden="true">
          <UserPlus size={20} />
        </span>
        <h2 id="register-title">{t('auth.registerTitle')}</h2>
        <button
          className="icon-action"
          type="button"
          aria-label={t('auth.closeRegistration')}
          onClick={closeDialog}
          disabled={submitting}
        >
          <X size={19} />
        </button>
      </div>

      <form className="register-form" onSubmit={submitRegistration}>
        <label htmlFor="register-username">{t('common.username')}</label>
        <input
          ref={usernameRef}
          id="register-username"
          name="username"
          type="text"
          autoComplete="username"
          autoFocus
          minLength={3}
          maxLength={32}
          value={username}
          onChange={(event) => setUsername(event.target.value)}
          disabled={submitting}
          required
        />

        <label htmlFor="register-password">{t('common.password')}</label>
        <input
          id="register-password"
          name="password"
          type="password"
          autoComplete="new-password"
          minLength={8}
          maxLength={128}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          disabled={submitting}
          required
        />

        <label htmlFor="register-password-confirmation">{t('common.confirmPassword')}</label>
        <input
          id="register-password-confirmation"
          name="password-confirmation"
          type="password"
          autoComplete="new-password"
          minLength={8}
          maxLength={128}
          value={passwordConfirmation}
          onChange={(event) => setPasswordConfirmation(event.target.value)}
          disabled={submitting}
          required
        />

        <p className="register-form__error" role="status" aria-live="polite">
          {error}
        </p>
        <p id="register-progress-note" className="register-form__note">
          {t('auth.registerNote')}
        </p>
        <button className="primary-action" type="submit" disabled={submitting}>
          <span>{submitting ? t('common.creatingAccount') : t('common.createAccount')}</span>
          <UserPlus size={19} />
        </button>
      </form>
    </dialog>
  )
}