// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, SyntheticEvent } from 'react'
import { UserPlus, X } from 'lucide-react'
import { ApiError, apiFetch } from './api'

export type Account = {
  id: number
  username: string
}

type RegisterDialogProps = {
  open: boolean
  onClose: () => void
  onRegistered: (account: Account) => void
}

/** Render an accessible modal that creates and signs in an Account. */
export function RegisterDialog({
  open,
  onClose,
  onRegistered,
}: RegisterDialogProps) {
  const dialogRef = useRef<HTMLDialogElement>(null)
  const usernameRef = useRef<HTMLInputElement>(null)
  const [username, setUsername] = useState('')
  const [password, setPassword] = useState('')
  const [passwordConfirmation, setPasswordConfirmation] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  useEffect(() => {
    const dialog = dialogRef.current
    if (!dialog) return
    if (open && !dialog.open) {
      dialog.showModal()
      usernameRef.current?.focus()
    } else if (!open && dialog.open) {
      dialog.close()
    }
  }, [open])

  /** Clear sensitive values before returning focus to the opener. */
  function closeDialog() {
    if (submitting) return
    setUsername('')
    setPassword('')
    setPasswordConfirmation('')
    setError(null)
    onClose()
  }

  /** Close the controlled dialog when the browser receives Escape. */
  function handleCancel(event: SyntheticEvent<HTMLDialogElement>) {
    event.preventDefault()
    closeDialog()
  }

  /** Validate confirmation and submit credentials to the registration API. */
  async function submitRegistration(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setError(null)
    if (password !== passwordConfirmation) {
      setError('Passwords do not match.')
      return
    }

    setSubmitting(true)
    try {
      const account = await apiFetch<Account>('/api/auth/register', {
        method: 'POST',
        body: JSON.stringify({ username, password }),
      })
      setPassword('')
      setPasswordConfirmation('')
      onRegistered(account)
      onClose()
    } catch (reason) {
      setError(
        reason instanceof ApiError && reason.status === 409
          ? 'That username is already taken.'
          : reason instanceof ApiError && reason.status === 422
            ? 'Use a 3–32 character username and an 8–128 character password.'
          : reason instanceof Error
            ? reason.message
            : 'Account could not be created.',
      )
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <dialog
      ref={dialogRef}
      className="register-dialog"
      aria-labelledby="register-title"
      aria-describedby="register-progress-note"
      onCancel={handleCancel}
    >
      <div className="register-dialog__heading">
        <span className="register-dialog__icon" aria-hidden="true">
          <UserPlus size={20} />
        </span>
        <h2 id="register-title">Create account</h2>
        <button
          className="icon-action"
          type="button"
          aria-label="Close registration"
          onClick={closeDialog}
          disabled={submitting}
        >
          <X size={19} />
        </button>
      </div>

      <form className="register-form" onSubmit={submitRegistration}>
        <label htmlFor="register-username">Username</label>
        <input
          ref={usernameRef}
          id="register-username"
          name="username"
          type="text"
          autoComplete="username"
          autoFocus
          minLength={3}
          maxLength={32}
          value={username}
          onChange={(event) => setUsername(event.target.value)}
          disabled={submitting}
          required
        />

        <label htmlFor="register-password">Password</label>
        <input
          id="register-password"
          name="password"
          type="password"
          autoComplete="new-password"
          minLength={8}
          maxLength={128}
          value={password}
          onChange={(event) => setPassword(event.target.value)}
          disabled={submitting}
          required
        />

        <label htmlFor="register-password-confirmation">Confirm password</label>
        <input
          id="register-password-confirmation"
          name="password-confirmation"
          type="password"
          autoComplete="new-password"
          minLength={8}
          maxLength={128}
          value={passwordConfirmation}
          onChange={(event) => setPasswordConfirmation(event.target.value)}
          disabled={submitting}
          required
        />

        <p className="register-form__error" role="status" aria-live="polite">
          {error}
        </p>
        <p id="register-progress-note" className="register-form__note">
          Your Daily Challenge progress is saved to your account.
        </p>
        <button className="primary-action" type="submit" disabled={submitting}>
          <span>{submitting ? 'Creating account…' : 'Create account'}</span>
          <UserPlus size={19} />
        </button>
      </form>
    </dialog>
  )
}