// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef } from 'react'
import type { GeoJsonObject } from 'geojson'
import L from 'leaflet'
import { GeoJSON, MapContainer, TileLayer, useMap } from 'react-leaflet'
import { useTranslation } from 'react-i18next'

export type TrainingDistrict = {
  id: number
  name: string
  bezirk: string
  boundary: GeoJsonObject
}

export type TrainingMasteryCategory =
  | 'not_seen'
  | 'needs_practice'
  | 'learning'
  | 'familiar'
  | 'known'
  | 'shelved'

type TrainingMapProps = {
  districts: TrainingDistrict[]
  direction: 'name' | 'find'
  targetDistrictId: number | null
  selectedDistrictId: number | null
  highlightedBezirke: string[]
  masteryByDistrict: Partial<Record<number, TrainingMasteryCategory>>
  answered: boolean
  correct: boolean | null
  onSelect: (districtId: number) => void
}

const HAMBURG_BOUNDS = L.latLngBounds(
  [53.39, 9.72],
  [53.75, 10.32],
)
const HAMBURG_VIEW_BOUNDS = HAMBURG_BOUNDS.pad(0.05)

const BEZIRK_COLORS: Record<string, { border: string; fill: string }> = {
  Altona: { border: '#2457a6', fill: '#4f83d1' },
  Bergedorf: { border: '#087f5b', fill: '#34b27b' },
  Eimsbüttel: { border: '#6d3e9c', fill: '#9b6ac4' },
  Harburg: { border: '#a43d65', fill: '#d16b91' },
  'Hamburg-Mitte': { border: '#b94338', fill: '#e76f61' },
  'Hamburg-Nord': { border: '#14758c', fill: '#49a7bb' },
  Wandsbek: { border: '#9a6500', fill: '#d99b24' },
}

const MASTERY_FILL_OPACITY: Record<TrainingMasteryCategory, number> = {
  shelved: 0.12,
  not_seen: 0.2,
  needs_practice: 0.35,
  learning: 0.55,
  familiar: 0.75,
  known: 1,
}

/** Keep Name It contextual and Find It city-wide until feedback is shown. */
function TrainingViewport({
  districts,
  direction,
  targetDistrictId,
  selectedDistrictId,
  answered,
}: Omit<TrainingMapProps, 'correct' | 'masteryByDistrict' | 'onSelect'>) {
  const map = useMap()

  useEffect(() => {
    const target = districts.find((district) => district.id === targetDistrictId)
    const selected = districts.find((district) => district.id === selectedDistrictId)

    function fitViewport() {
      map.invalidateSize({ animate: false })
      const desktopPanelWidth = map.getSize().x > 760 ? 430 : 0
      const paddingTopLeft: L.PointExpression = [desktopPanelWidth + 36, 36]
      const paddingBottomRight: L.PointExpression = [36, 36]

      if (answered && target) {
        const feedbackBounds = L.geoJSON(target.boundary).getBounds()
        if (selected) feedbackBounds.extend(L.geoJSON(selected.boundary).getBounds())
        map.fitBounds(feedbackBounds, {
          paddingTopLeft,
          paddingBottomRight,
          maxZoom: 13,
        })
        return
      }
      if (direction === 'name' && target) {
        map.fitBounds(L.geoJSON(target.boundary).getBounds(), {
          paddingTopLeft,
          paddingBottomRight,
          maxZoom: 12,
        })
        return
      }
      map.fitBounds(HAMBURG_BOUNDS, { padding: [24, 24] })
    }

    fitViewport()
    map.on('resize', fitViewport)
    return () => {
      map.off('resize', fitViewport)
    }
  }, [answered, direction, districts, map, selectedDistrictId, targetDistrictId])

  return null
}

/** Render one boundary with pointer and keyboard selection parity. */
function TrainingBoundary({
  district,
  style,
  selectable,
  selected,
  onSelect,
}: {
  district: TrainingDistrict
  style: L.PathOptions
  selectable: boolean
  selected: boolean
  onSelect: (districtId: number) => void
}) {
  const { t } = useTranslation()
  const layerRef = useRef<L.GeoJSON | null>(null)

  useEffect(() => {
    const cleanups: Array<() => void> = []
    layerRef.current?.eachLayer((layer) => {
      if (!(layer instanceof L.Path)) return
      if (selected) layer.bringToFront()
      const element = layer.getElement()
      if (!element) return
      element.setAttribute('role', selectable ? 'button' : 'img')
      element.setAttribute('tabindex', selectable ? '0' : '-1')
      element.setAttribute(
        'aria-label',
        selectable
          ? t('training.selectableArea', {
              id: district.id,
              selected: selected ? t('training.selectedSuffix') : '',
            })
          : `${district.name}, ${district.bezirk}`,
      )
      const handleKeyDown = (event: Event) => {
        if (
          !(event instanceof KeyboardEvent)
          || !selectable
          || (event.key !== 'Enter' && event.key !== ' ')
        ) return
        event.preventDefault()
        onSelect(district.id)
      }
      element.addEventListener('keydown', handleKeyDown)
      cleanups.push(() => element.removeEventListener('keydown', handleKeyDown))
    })
    return () => cleanups.forEach((cleanup) => cleanup())
  }, [district, onSelect, selectable, selected, t])

  return (
    <GeoJSON
      ref={layerRef}
      data={district.boundary}
      style={style}
      eventHandlers={{
        click: () => {
          if (selectable) onSelect(district.id)
        },
      }}
    />
  )
}

/** Display the complete non-satellite Hamburg Training map. */
export function TrainingMap({
  districts,
  direction,
  targetDistrictId,
  selectedDistrictId,
  highlightedBezirke,
  masteryByDistrict,
  answered,
  correct,
  onSelect,
}: TrainingMapProps) {
  const { t } = useTranslation()
  function districtStyle(district: TrainingDistrict): L.PathOptions {
    const isTarget = district.id === targetDistrictId
    const isSelected = district.id === selectedDistrictId
    if (answered && isTarget) {
      return {
        color: '#087f5b',
        fillColor: '#34b27b',
        fillOpacity: 0.52,
        opacity: 1,
        weight: 3,
      }
    }
    if (answered && isSelected && !correct) {
      return {
        color: '#b52f36',
        fillColor: '#d9484f',
        fillOpacity: 0.44,
        opacity: 1,
        weight: 3,
      }
    }
    if (!answered && direction === 'name' && isTarget) {
      return {
        color: '#075f47',
        fillColor: '#18a573',
        fillOpacity: 0.55,
        opacity: 1,
        weight: 3,
      }
    }
    if (!answered && direction === 'find' && isSelected) {
      return {
        color: '#075f47',
        fillColor: '#18a573',
        fillOpacity: 0.62,
        opacity: 1,
        weight: 4,
      }
    }
    if (highlightedBezirke.includes(district.bezirk)) {
      const colors = BEZIRK_COLORS[district.bezirk] ?? {
        border: '#405a50',
        fill: '#789486',
      }
      return {
        color: colors.border,
        fillColor: colors.fill,
        fillOpacity: MASTERY_FILL_OPACITY[masteryByDistrict[district.id] ?? 'not_seen'],
        opacity: 1,
        weight: 1.75,
      }
    }
    return {
      color: '#64756e',
      fillColor: '#dce4df',
      fillOpacity: 0.12,
      opacity: 0.68,
      weight: 1.25,
    }
  }

  return (
    <div className="map-surface training-map" aria-label={t('common.interactiveDistrictMap')}>
      <MapContainer
        center={[53.55, 10]}
        zoom={10}
        minZoom={9}
        maxZoom={16}
        maxBounds={HAMBURG_VIEW_BOUNDS}
        maxBoundsViscosity={1}
        zoomControl={false}
        attributionControl
      >
        <TileLayer
          attribution="Tiles &copy; Esri"
          url="https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
        />
        <TrainingViewport
          districts={districts}
          direction={direction}
          targetDistrictId={targetDistrictId}
          selectedDistrictId={selectedDistrictId}
          highlightedBezirke={highlightedBezirke}
          answered={answered}
        />
        {districts.map((district) => (
          <TrainingBoundary
            key={district.id}
            district={district}
            style={districtStyle(district)}
            selectable={direction === 'find' && !answered}
            selected={district.id === selectedDistrictId}
            onSelect={onSelect}
          />
        ))}
      </MapContainer>
    </div>
  )
}
