// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import {
  ArrowRight,
  BarChart3,
  Check,
  ChevronRight,
  Home,
  Layers3,
  LockKeyhole,
  LogIn,
  RotateCcw,
  Search,
  ShieldCheck,
  SquareMousePointer,
  UserPlus,
  X,
} from 'lucide-react'
import { ApiError, apiFetch } from './api'
import { LoginDialog } from './LoginDialog'
import { RegisterDialog } from './RegisterDialog'
import { TrainingMap } from './TrainingMap'
import type { TrainingDistrict } from './TrainingMap'

type Direction = 'name' | 'find'
type TrainingView = 'setup' | 'question' | 'feedback' | 'summary'
type MasteryCategory = 'not_seen' | 'needs_practice' | 'learning' | 'familiar' | 'known' | 'shelved'

type DirectionProgress = {
  attempts: number
  correct: number
  accuracy: number
  practiced: number
  due: number
}

type ProgressItem = {
  district_id: number
  name: string
  bezirk: string
  name_category: MasteryCategory
  find_category: MasteryCategory
  fully_known: boolean
}

export type TrainingProgress = {
  attempts: number
  correct: number
  accuracy: number
  practiced: number
  fully_known: number
  directions: Record<Direction, DirectionProgress>
  items: ProgressItem[]
}

type TrainingBootstrap = {
  districts: TrainingDistrict[]
  bezirke: string[]
  progress: TrainingProgress
}

type TrainingQuestion = {
  session_id: number
  direction: Direction
  district_id: number
  prompt_name: string | null
  bezirk: string | null
  attempt_count: number
  correct_count: number
}

type TrainingFeedback = {
  correct: boolean
  outcome: 'correct' | 'incorrect' | 'dont_know'
  answer: {
    district_id: number
    name: string
    bezirk: string
  }
  selected: {
    district_id: number
    name: string
  } | null
  stage: number
  due_at: string
  session: {
    attempts: number
    correct: number
    introduced: number
  }
}

type SessionSummary = {
  attempts: number
  correct: number
  accuracy: number
  introduced: number
  needs_practice: number
}

type TrainingAppProps = {
  onHome: () => void
  onNavigate: (path: string) => void
}

/** Calculate an accuracy label without duplicating rendering conditions. */
function accuracyLabel(correct: number, attempts: number) {
  return attempts === 0 ? '0%' : `${Math.round((correct / attempts) * 100)}%`
}

/** Render the authenticated, endless Training workflow. */
export function TrainingApp({ onHome, onNavigate }: TrainingAppProps) {
  const [bootstrap, setBootstrap] = useState<TrainingBootstrap | null>(null)
  const [direction, setDirection] = useState<Direction>('name')
  const [selectedBezirke, setSelectedBezirke] = useState<string[]>([])
  const [view, setView] = useState<TrainingView>('setup')
  const [question, setQuestion] = useState<TrainingQuestion | null>(null)
  const [feedback, setFeedback] = useState<TrainingFeedback | null>(null)
  const [summary, setSummary] = useState<SessionSummary | null>(null)
  const [answerText, setAnswerText] = useState('')
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(-1)
  const [selectedDistrictId, setSelectedDistrictId] = useState<number | null>(null)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [authenticationRequired, setAuthenticationRequired] = useState(false)
  const [loginOpen, setLoginOpen] = useState(false)
  const [registrationOpen, setRegistrationOpen] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const nextButtonRef = useRef<HTMLButtonElement>(null)
  const loginButtonRef = useRef<HTMLButtonElement>(null)
  const registrationButtonRef = useRef<HTMLButtonElement>(null)

  /** Reload geometry and server progress after authentication or reset. */
  async function loadTraining() {
    setLoading(true)
    setError(null)
    try {
      const result = await apiFetch<TrainingBootstrap>('/api/training/bootstrap')
      setBootstrap(result)
      setSelectedBezirke(result.bezirke)
      setAuthenticationRequired(false)
    } catch (reason) {
      if (reason instanceof ApiError && reason.status === 401) {
        setAuthenticationRequired(true)
      } else {
        setError(reason instanceof Error ? reason.message : 'Training could not be loaded.')
      }
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    let cancelled = false
    apiFetch<TrainingBootstrap>('/api/training/bootstrap')
      .then((result) => {
        if (cancelled) return
        setBootstrap(result)
        setSelectedBezirke(result.bezirke)
        setAuthenticationRequired(false)
      })
      .catch((reason: unknown) => {
        if (cancelled) return
        if (reason instanceof ApiError && reason.status === 401) {
          setAuthenticationRequired(true)
        } else {
          setError(reason instanceof Error ? reason.message : 'Training could not be loaded.')
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  useEffect(() => {
    if (submitting) return
    if (view === 'question' && direction === 'name' && question) {
      inputRef.current?.focus()
    } else if (view === 'feedback') {
      nextButtonRef.current?.focus()
    }
  }, [direction, question, submitting, view])

  /** Restore Training immediately after a successful login or registration. */
  async function handleAuthenticated() {
    setLoginOpen(false)
    setRegistrationOpen(false)
    await loadTraining()
  }

  /** Start a fresh server-owned queue for the selected mode and scope. */
  async function startSession(nextDirection: Direction = direction) {
    if (!bootstrap || selectedBezirke.length === 0) return
    setSubmitting(true)
    setError(null)
    try {
      const nextQuestion = await apiFetch<TrainingQuestion>('/api/training/sessions', {
        method: 'POST',
        body: JSON.stringify({
          direction: nextDirection,
          selected_bezirke: selectedBezirke,
        }),
      })
      setDirection(nextDirection)
      setQuestion(nextQuestion)
      setFeedback(null)
      setSummary(null)
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      setSelectedDistrictId(null)
      setView('question')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Training could not start.')
    } finally {
      setSubmitting(false)
    }
  }

  /** Submit the first Name It answer or confirmed Find It selection. */
  async function submitAnswer(dontKnow = false, nameAnswer = answerText) {
    if (!question || submitting) return
    setSubmitting(true)
    setError(null)
    try {
      const result = await apiFetch<TrainingFeedback>(
        `/api/training/sessions/${question.session_id}/answer`,
        {
          method: 'POST',
          body: JSON.stringify(
            dontKnow
              ? { dont_know: true }
              : direction === 'name'
                ? { answer_text: nameAnswer }
                : { selected_district_id: selectedDistrictId },
          ),
        },
      )
      setFeedback(result)
      setView('feedback')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Answer could not be checked.')
    } finally {
      setSubmitting(false)
    }
  }

  function findDistrict(value: string) {
    const normalized = value.trim().toLocaleLowerCase('de')
    return districts.find(
      (district) => district.name.toLocaleLowerCase('de') === normalized,
    )
  }

  function handleAnswerChange(value: string) {
    setAnswerText(value)
    setActiveSuggestionIndex(-1)
  }

  function chooseDistrict(district: TrainingDistrict) {
    setAnswerText(district.name)
    setActiveSuggestionIndex(-1)
    void submitAnswer(false, district.name)
  }

  function selectedSuggestion() {
    return suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(answerText)
  }

  function handleAnswerKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'ArrowDown' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (current + 1) % suggestions.length)
      return
    }
    if (event.key === 'ArrowUp' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (
        current <= 0 ? suggestions.length - 1 : current - 1
      ))
      return
    }
    if (event.key === 'Escape') {
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      return
    }
    if (event.key !== 'Enter') return

    event.preventDefault()
    const district = selectedSuggestion()
    if (district) {
      chooseDistrict(district)
      return
    }
    setError('Choose a Stadtteil from the suggestions.')
  }

  /** Grade only a selected or exactly matched Name It answer. */
  function handleNameSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const district = selectedSuggestion()
    if (district) {
      chooseDistrict(district)
      return
    }
    setError('Choose a Stadtteil from the list.')
  }

  /** Acknowledge feedback and request the next queued question. */
  async function nextQuestion() {
    if (!question || submitting) return
    setSubmitting(true)
    setError(null)
    try {
      const next = await apiFetch<TrainingQuestion>(
        `/api/training/sessions/${question.session_id}/next`,
        { method: 'POST' },
      )
      setQuestion(next)
      setFeedback(null)
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      setSelectedDistrictId(null)
      setView('question')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'The next question could not be loaded.')
    } finally {
      setSubmitting(false)
    }
  }

  /** Stop the active session and display its server-calculated summary. */
  async function stopSession(confirmStop = true) {
    if (!question || submitting) return
    if (confirmStop && view === 'question' && !window.confirm('Stop this Training session? The unanswered question will not be graded.')) return
    setSubmitting(true)
    try {
      const result = await apiFetch<SessionSummary>(
        `/api/training/sessions/${question.session_id}/stop`,
        { method: 'POST' },
      )
      setSummary(result)
      setQuestion(null)
      setFeedback(null)
      setView('summary')
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Training could not be stopped.')
    } finally {
      setSubmitting(false)
    }
  }

  /** Return Home without accidentally grading the active question. */
  async function goHome() {
    if (question && view === 'question') {
      if (!window.confirm('Return Home? The unanswered question will not be graded.')) return
      await stopSession(false)
    } else if (question) {
      await stopSession(false)
    }
    onHome()
  }

  /** Change exercise mode only after the current answer has been resolved. */
  async function changeDirection(nextDirection: Direction) {
    if (nextDirection === direction || view === 'question') return
    if (question) await stopSession(false)
    setDirection(nextDirection)
    setView('setup')
    setSummary(null)
    setError(null)
  }

  /** Apply Already Known or Shelf to the latest graded card. */
  async function manageCurrentCard(action: 'already_known' | 'shelve') {
    if (!feedback || submitting) return
    setSubmitting(true)
    try {
      const progress = await apiFetch<TrainingProgress>(
        `/api/training/cards/${direction}/${feedback.answer.district_id}`,
        { method: 'POST', body: JSON.stringify({ action }) },
      )
      if (bootstrap) setBootstrap({ ...bootstrap, progress })
      if (action === 'shelve' && question) {
        try {
          const next = await apiFetch<TrainingQuestion>(
            `/api/training/sessions/${question.session_id}/next`,
            { method: 'POST' },
          )
          setQuestion(next)
          setFeedback(null)
          setAnswerText('')
          setActiveSuggestionIndex(-1)
          setSelectedDistrictId(null)
          setView('question')
        } catch (reason) {
          if (!(reason instanceof ApiError && reason.status === 409)) throw reason
          const result = await apiFetch<SessionSummary>(
            `/api/training/sessions/${question.session_id}/stop`,
            { method: 'POST' },
          )
          setSummary(result)
          setQuestion(null)
          setFeedback(null)
          setView('summary')
        }
      }
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Progress could not be updated.')
    } finally {
      setSubmitting(false)
    }
  }

  /** Toggle one Bezirk while preventing an empty study scope. */
  function toggleBezirk(bezirk: string) {
    setSelectedBezirke((current) => {
      if (!current.includes(bezirk)) return [...current, bezirk]
      if (current.length === 1) return current
      return current.filter((item) => item !== bezirk)
    })
  }

  const districts = bootstrap?.districts ?? []
  const normalizedAnswer = answerText.trim().toLocaleLowerCase('de')
  const suggestions = normalizedAnswer
    ? districts.filter((district) => (
        district.name.toLocaleLowerCase('de').includes(normalizedAnswer)
      ))
    : []
  const sessionAttempts = feedback?.session.attempts ?? question?.attempt_count ?? 0
  const sessionCorrect = feedback?.session.correct ?? question?.correct_count ?? 0

  if (loading) {
    return (
      <main className="training-shell training-shell--loading">
        <div className="training-loading" role="status">Loading Training…</div>
      </main>
    )
  }

  if (authenticationRequired) {
    return (
      <main className="training-shell training-shell--locked">
        <section className="training-locked" aria-labelledby="training-locked-title">
          <span className="training-locked__icon"><LockKeyhole aria-hidden="true" /></span>
          <p className="eyebrow">Account training</p>
          <h1 id="training-locked-title">Sign in to train</h1>
          <p>Your review schedule and mastery stay attached to your account.</p>
          <div className="training-locked__actions">
            <button ref={loginButtonRef} className="primary-action" type="button" onClick={() => setLoginOpen(true)}>
              <span>Log in</span><LogIn size={19} aria-hidden="true" />
            </button>
            <button ref={registrationButtonRef} className="secondary-action secondary-action--light" type="button" onClick={() => setRegistrationOpen(true)}>
              <UserPlus size={18} aria-hidden="true" /><span>Create account</span>
            </button>
            <button className="text-action" type="button" onClick={onHome}>Return Home</button>
          </div>
        </section>
        <LoginDialog open={loginOpen} onClose={() => setLoginOpen(false)} onLoggedIn={handleAuthenticated} />
        <RegisterDialog open={registrationOpen} onClose={() => setRegistrationOpen(false)} onRegistered={handleAuthenticated} />
      </main>
    )
  }

  return (
    <main className={`training-shell training-shell--${view}`}>
      <TrainingMap
        districts={districts}
        direction={direction}
        targetDistrictId={question?.district_id ?? feedback?.answer.district_id ?? null}
        selectedDistrictId={selectedDistrictId ?? feedback?.selected?.district_id ?? null}
        answered={view === 'feedback'}
        correct={feedback?.correct ?? null}
        onSelect={setSelectedDistrictId}
      />

      <header className="training-topbar">
        <button className="icon-action icon-action--surface" type="button" onClick={() => void goHome()} aria-label="Return to mode selection" title="Home">
          <Home size={19} aria-hidden="true" />
        </button>
        <div className="training-brand"><Layers3 size={18} aria-hidden="true" /><span>Hamburg Training</span></div>
        <button className="icon-action icon-action--surface" type="button" onClick={() => onNavigate('/training/progress')} aria-label="View Training progress" title="Progress">
          <BarChart3 size={19} aria-hidden="true" />
        </button>
      </header>

      <aside className="training-panel" aria-live="polite">
        <div className="direction-switch" aria-label="Training exercise">
          <button type="button" className={direction === 'name' ? 'is-active' : ''} disabled={view === 'question'} onClick={() => void changeDirection('name')}>
            <Search size={16} aria-hidden="true" /> Name It
          </button>
          <button type="button" className={direction === 'find' ? 'is-active' : ''} disabled={view === 'question'} onClick={() => void changeDirection('find')}>
            <SquareMousePointer size={16} aria-hidden="true" /> Find It
          </button>
        </div>

        {error ? <p className="notice notice--error" role="alert">{error}</p> : null}

        {view === 'setup' ? (
          <section className="training-setup" aria-labelledby="training-title">
            <p className="eyebrow">Spaced repetition</p>
            <h1 id="training-title">{direction === 'name' ? 'Name Hamburg' : 'Find Hamburg'}</h1>
            <p>
              {direction === 'name'
                ? 'A Stadtteil lights up. Give it a name before the answer fades.'
                : 'Read the name, select its shape, then confirm your choice.'}
            </p>
            <div className="training-metrics" aria-label="Current Training progress">
              <div><strong>{bootstrap?.progress.directions[direction].due ?? 0}</strong><span>Due now</span></div>
              <div><strong>{bootstrap?.progress.directions[direction].practiced ?? 0}</strong><span>Practiced</span></div>
              <div><strong>{bootstrap?.progress.directions[direction].accuracy ?? 0}%</strong><span>Accuracy</span></div>
            </div>
            <fieldset className="scope-picker">
              <legend>Studying</legend>
              <button type="button" onClick={() => setSelectedBezirke(bootstrap?.bezirke ?? [])}>All Hamburg</button>
              <div>
                {bootstrap?.bezirke.map((bezirk) => (
                  <label key={bezirk}>
                    <input type="checkbox" checked={selectedBezirke.includes(bezirk)} onChange={() => toggleBezirk(bezirk)} />
                    <span>{bezirk}</span>
                  </label>
                ))}
              </div>
            </fieldset>
            <button className="primary-action" type="button" disabled={submitting} onClick={() => void startSession()}>
              <span>{submitting ? 'Preparing…' : 'Start Training'}</span><ArrowRight size={20} aria-hidden="true" />
            </button>
          </section>
        ) : null}

        {view === 'question' && question ? (
          <section className="training-question" aria-labelledby="training-question-title">
            <p className="eyebrow">Question {sessionAttempts + 1}</p>
            {direction === 'name' ? (
              <>
                <h1 id="training-question-title">Which Stadtteil is this?</h1>
                <form className="training-answer-form" onSubmit={handleNameSubmit}>
                  <label htmlFor="training-answer">Stadtteil name</label>
                  <div className="guess-control">
                    <input
                      ref={inputRef}
                      id="training-answer"
                      value={answerText}
                      onChange={(event) => handleAnswerChange(event.target.value)}
                      onKeyDown={handleAnswerKeyDown}
                      autoComplete="off"
                      placeholder="Type the name…"
                      role="combobox"
                      aria-autocomplete="list"
                      aria-controls="training-suggestions"
                      aria-expanded={suggestions.length > 0}
                      aria-activedescendant={activeSuggestionIndex >= 0 ? `training-suggestion-${suggestions[activeSuggestionIndex]?.id}` : undefined}
                      readOnly={submitting}
                    />
                    <button type="submit" disabled={!answerText.trim() || submitting} aria-label="Submit answer"><ArrowRight size={20} /></button>
                  </div>
                  {suggestions.length > 0 ? (
                    <div className="training-suggestions" id="training-suggestions" role="listbox">
                      {suggestions.map((district, index) => (
                        <button
                          key={district.id}
                          id={`training-suggestion-${district.id}`}
                          type="button"
                          role="option"
                          aria-selected={index === activeSuggestionIndex}
                          className={index === activeSuggestionIndex ? 'is-active' : ''}
                          onMouseDown={(event) => event.preventDefault()}
                          onClick={() => chooseDistrict(district)}
                        >
                          {district.name}
                        </button>
                      ))}
                    </div>
                  ) : null}
                </form>
              </>
            ) : (
              <>
                <h1 id="training-question-title">Where is {question.prompt_name}?</h1>
                <p>Select a boundary on the map. You can change it before confirming.</p>
                <div className="selected-answer" aria-live="polite">
                  {selectedDistrictId !== null ? <><span>Selected</span><strong>Area selected</strong></> : <span>No Stadtteil selected</span>}
                </div>
                <button className="primary-action" type="button" disabled={selectedDistrictId === null || submitting} onClick={() => void submitAnswer()}>
                  <span>Confirm location</span><Check size={19} aria-hidden="true" />
                </button>
              </>
            )}
            <div className="question-actions">
              <button type="button" onClick={() => void submitAnswer(true)} disabled={submitting}>Don’t Know</button>
              <button type="button" onClick={() => void stopSession()} disabled={submitting}>Stop for now</button>
            </div>
          </section>
        ) : null}

        {view === 'feedback' && feedback ? (
          <section className="training-feedback" aria-labelledby="feedback-title">
            <span className={feedback.correct ? 'feedback-icon feedback-icon--correct' : 'feedback-icon feedback-icon--wrong'}>
              {feedback.correct ? <Check aria-hidden="true" /> : <X aria-hidden="true" />}
            </span>
            <p className="eyebrow">{feedback.correct ? 'Correct' : feedback.outcome === 'dont_know' ? 'Noted' : 'Not quite'}</p>
            <h1 id="feedback-title">{feedback.answer.name}</h1>
            <p>{feedback.answer.bezirk}</p>
            {!feedback.correct && feedback.selected ? <p className="feedback-comparison">You selected <strong>{feedback.selected.name}</strong>.</p> : null}
            <div className="session-line">
              <span>{sessionCorrect}/{sessionAttempts} correct</span>
              <span>{accuracyLabel(sessionCorrect, sessionAttempts)}</span>
            </div>
            <button ref={nextButtonRef} className="primary-action" type="button" disabled={submitting} onClick={() => void nextQuestion()}>
              <span>Next</span><ChevronRight size={20} aria-hidden="true" />
            </button>
            <div className="feedback-actions">
              {feedback.correct ? <button type="button" onClick={() => void manageCurrentCard('already_known')} disabled={submitting}><ShieldCheck size={16} /> Already know this</button> : null}
              <button type="button" onClick={() => void manageCurrentCard('shelve')} disabled={submitting}>Shelve</button>
              <button type="button" onClick={() => void stopSession(false)} disabled={submitting}>Stop for now</button>
            </div>
          </section>
        ) : null}

        {view === 'summary' && summary ? (
          <section className="training-summary" aria-labelledby="summary-title">
            <p className="eyebrow">Session complete</p>
            <h1 id="summary-title">Good stopping point.</h1>
            <div className="summary-grid">
              <div><strong>{summary.attempts}</strong><span>Attempts</span></div>
              <div><strong>{summary.accuracy}%</strong><span>Accuracy</span></div>
              <div><strong>{summary.introduced}</strong><span>Introduced</span></div>
              <div><strong>{summary.needs_practice}</strong><span>Need practice</span></div>
            </div>
            <button className="primary-action" type="button" onClick={() => setView('setup')}><span>Continue Training</span><RotateCcw size={19} /></button>
            <button className="text-action" type="button" onClick={onHome}>Return Home</button>
          </section>
        ) : null}
      </aside>
    </main>
  )
}

/** Display signed-in aggregate and per-mode mastery with reset controls. */
export function TrainingProgressPage({ onHome, onNavigate }: TrainingAppProps) {
  const [progress, setProgress] = useState<TrainingProgress | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  /** Load compact Training statistics without downloading map geometry. */
  async function loadProgress() {
    setLoading(true)
    try {
      setProgress(await apiFetch<TrainingProgress>('/api/training/progress'))
      setError(null)
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Progress could not be loaded.')
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    let cancelled = false
    apiFetch<TrainingProgress>('/api/training/progress')
      .then((result) => {
        if (!cancelled) setProgress(result)
      })
      .catch((reason: unknown) => {
        if (!cancelled) setError(reason instanceof Error ? reason.message : 'Progress could not be loaded.')
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Permanently reset only Training records after explicit confirmation. */
  async function resetProgress() {
    if (!window.confirm('Reset all Training progress? Daily history and your account will not be changed.')) return
    try {
      await apiFetch<void>('/api/training', { method: 'DELETE' })
      await loadProgress()
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Training progress could not be reset.')
    }
  }

  /** Restore both shelved direction cards for one Stadtteil when present. */
  async function restoreItem(item: ProgressItem) {
    try {
      let latest = progress
      if (item.name_category === 'shelved') {
        latest = await apiFetch<TrainingProgress>(
          `/api/training/cards/name/${item.district_id}`,
          { method: 'POST', body: JSON.stringify({ action: 'restore' }) },
        )
      }
      if (item.find_category === 'shelved') {
        latest = await apiFetch<TrainingProgress>(
          `/api/training/cards/find/${item.district_id}`,
          { method: 'POST', body: JSON.stringify({ action: 'restore' }) },
        )
      }
      setProgress(latest)
      setError(null)
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'The Stadtteil could not be restored.')
    }
  }

  const categories: Array<{ key: MasteryCategory; label: string }> = [
    { key: 'needs_practice', label: 'Needs practice' },
    { key: 'learning', label: 'Learning' },
    { key: 'familiar', label: 'Familiar' },
    { key: 'known', label: 'Known' },
    { key: 'shelved', label: 'Shelved' },
  ]

  return (
    <main className="progress-page">
      <header className="progress-topbar">
        <button className="icon-action" type="button" onClick={onHome} aria-label="Return to mode selection" title="Home"><Home size={19} /></button>
        <strong>Training progress</strong>
        <button className="text-action" type="button" onClick={() => onNavigate('/training')}>Train</button>
      </header>
      <div className="progress-content">
        <p className="eyebrow">Your Hamburg</p>
        <h1>Progress that remembers.</h1>
        {loading ? <p role="status">Loading progress…</p> : null}
        {error ? <p className="notice notice--error" role="alert">{error}</p> : null}
        {progress ? (
          <>
            <section className="progress-overview" aria-label="Overall progress">
              <div><strong>{progress.practiced}<small>/104</small></strong><span>Practiced</span></div>
              <div><strong>{progress.accuracy}%</strong><span>Recall accuracy</span></div>
              <div><strong>{progress.fully_known}</strong><span>Known both ways</span></div>
            </section>
            <section className="mode-breakdown" aria-labelledby="mode-progress-title">
              <h2 id="mode-progress-title">By exercise</h2>
              {(['name', 'find'] as const).map((mode) => (
                <div key={mode}>
                  <span>{mode === 'name' ? 'Name It' : 'Find It'}</span>
                  <strong>{progress.directions[mode].accuracy}%</strong>
                  <small>{progress.directions[mode].attempts} attempts · {progress.directions[mode].due} due</small>
                </div>
              ))}
            </section>
            <section className="mastery-list" aria-labelledby="mastery-title">
              <h2 id="mastery-title">Stadtteile</h2>
              {categories.map((category) => {
                const items = progress.items.filter((item) => item.name_category === category.key || item.find_category === category.key)
                return (
                  <details key={category.key} open={category.key === 'needs_practice'}>
                    <summary>{category.label}<span>{items.length}</span></summary>
                    {items.length > 0 ? (
                      <ul>{items.map((item) => (
                        <li key={item.district_id}>
                          <strong>{item.name}</strong><span>{item.bezirk}</span>
                          {category.key === 'shelved' ? <button type="button" onClick={() => void restoreItem(item)}>Restore</button> : null}
                        </li>
                      ))}</ul>
                    ) : <p>Nothing here yet.</p>}
                  </details>
                )
              })}
            </section>
            <section className="reset-training" aria-labelledby="reset-title">
              <h2 id="reset-title">Reset Training</h2>
              <p>Delete every Training attempt and review schedule. Daily history and account credentials stay intact.</p>
              <button type="button" onClick={() => void resetProgress()}><RotateCcw size={17} /> Reset all Training progress</button>
            </section>
          </>
        ) : null}
      </div>
    </main>
  )
}
