// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef, useState } from 'react'
import type { FormEvent, KeyboardEvent } from 'react'
import {
  ArrowRight,
  BarChart3,
  Check,
  ChevronRight,
  Home,
  Layers3,
  LockKeyhole,
  LogIn,
  LogOut,
  RotateCcw,
  Search,
  ShieldCheck,
  SquareMousePointer,
  UserPlus,
  X,
} from 'lucide-react'
import { Trans, useTranslation } from 'react-i18next'
import { useAccount } from './accountContext'
import { ApiError, apiErrorMessage, apiFetch } from './api'
import i18n, { activeLanguage, formatPercent } from './i18n'
import { TrainingMap } from './TrainingMap'
import type { TrainingDistrict, TrainingMasteryCategory } from './TrainingMap'

type Direction = 'name' | 'find'
type TrainingView = 'setup' | 'question' | 'feedback' | 'summary'
type MasteryCategory = TrainingMasteryCategory

type DirectionProgress = {
  attempts: number
  correct: number
  accuracy: number
  practiced: number
  due: number
}

type ProgressItem = {
  district_id: number
  name: string
  bezirk: string
  name_category: MasteryCategory
  find_category: MasteryCategory
  fully_known: boolean
}

export type TrainingProgress = {
  attempts: number
  correct: number
  accuracy: number
  practiced: number
  fully_known: number
  directions: Record<Direction, DirectionProgress>
  items: ProgressItem[]
}

type TrainingBootstrap = {
  districts: TrainingDistrict[]
  bezirke: string[]
  progress: TrainingProgress
}

type TrainingQuestion = {
  session_id: number
  direction: Direction
  district_id: number
  prompt_name: string | null
  bezirk: string | null
  attempt_count: number
  correct_count: number
}

type TrainingFeedback = {
  correct: boolean
  outcome: 'correct' | 'incorrect' | 'dont_know'
  answer: {
    district_id: number
    name: string
    bezirk: string
  }
  selected: {
    district_id: number
    name: string
  } | null
  stage: number
  due_at: string
  session: {
    attempts: number
    correct: number
    introduced: number
  }
}

type SessionSummary = {
  attempts: number
  correct: number
  accuracy: number
  introduced: number
  needs_practice: number
}

type TrainingAppProps = {
  onHome: () => void
  onNavigate: (path: string) => void
}

/** Calculate an accuracy label without duplicating rendering conditions. */
function accuracyLabel(correct: number, attempts: number) {
  return new Intl.NumberFormat(activeLanguage(), { style: 'percent', maximumFractionDigits: 0 }).format(attempts === 0 ? 0 : correct / attempts)
}

/** Render the authenticated, endless Training workflow. */
export function TrainingApp({ onHome, onNavigate }: TrainingAppProps) {
  const { t } = useTranslation()
  const {
    status: accountStatus,
    error: accountError,
    signingOut,
    openLogin,
    openRegistration,
    signOut: signOutAccount,
    markAnonymous,
  } = useAccount()
  const [bootstrap, setBootstrap] = useState<TrainingBootstrap | null>(null)
  const [direction, setDirection] = useState<Direction>('name')
  const [selectedBezirke, setSelectedBezirke] = useState<string[]>([])
  const [view, setView] = useState<TrainingView>('setup')
  const [question, setQuestion] = useState<TrainingQuestion | null>(null)
  const [feedback, setFeedback] = useState<TrainingFeedback | null>(null)
  const [summary, setSummary] = useState<SessionSummary | null>(null)
  const [answerText, setAnswerText] = useState('')
  const [activeSuggestionIndex, setActiveSuggestionIndex] = useState(-1)
  const [selectedDistrictId, setSelectedDistrictId] = useState<number | null>(null)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [authenticationRequired, setAuthenticationRequired] = useState(false)
  const inputRef = useRef<HTMLInputElement>(null)
  const nextButtonRef = useRef<HTMLButtonElement>(null)

  useEffect(() => {
    if (accountStatus !== 'authenticated') return

    let cancelled = false
    Promise.all([
      apiFetch<TrainingDistrict[]>('/api/map/districts/v1'),
      apiFetch<TrainingProgress>('/api/training/progress'),
    ])
      .then(([districts, progress]) => {
        if (cancelled) return
        const bezirke = [...new Set(districts.map((district) => district.bezirk))].sort()
        setBootstrap({ districts, bezirke, progress })
        setSelectedBezirke(bezirke)
        setAuthenticationRequired(false)
      })
      .catch((reason: unknown) => {
        if (cancelled) return
        if (reason instanceof ApiError && reason.status === 401) {
          markAnonymous()
          setAuthenticationRequired(true)
        } else {
          setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.loadError'))
        }
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [accountStatus, markAnonymous])

  useEffect(() => {
    if (submitting) return
    if (view === 'question' && direction === 'name' && question) {
      inputRef.current?.focus()
    } else if (view === 'feedback') {
      nextButtonRef.current?.focus()
    }
  }, [direction, question, submitting, view])

  /** End the Account session and return Training to its authentication gate. */
  async function signOut() {
    if (!(await signOutAccount())) return
    setBootstrap(null)
    setQuestion(null)
    setFeedback(null)
    setAuthenticationRequired(true)
  }

  /** Start a fresh server-owned queue for the selected mode and scope. */
  async function startSession(nextDirection: Direction = direction) {
    if (!bootstrap || selectedBezirke.length === 0) return
    setSubmitting(true)
    setError(null)
    try {
      const nextQuestion = await apiFetch<TrainingQuestion>('/api/training/sessions', {
        method: 'POST',
        body: JSON.stringify({
          direction: nextDirection,
          selected_bezirke: selectedBezirke,
        }),
      })
      setDirection(nextDirection)
      setQuestion(nextQuestion)
      setFeedback(null)
      setSummary(null)
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      setSelectedDistrictId(null)
      setView('question')
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.startError'))
    } finally {
      setSubmitting(false)
    }
  }

  /** Submit the first Name It answer or confirmed Find It selection. */
  async function submitAnswer(dontKnow = false, nameAnswer = answerText) {
    if (!question || submitting) return
    setSubmitting(true)
    setError(null)
    try {
      const result = await apiFetch<TrainingFeedback>(
        `/api/training/sessions/${question.session_id}/answer`,
        {
          method: 'POST',
          body: JSON.stringify(
            dontKnow
              ? { dont_know: true }
              : direction === 'name'
                ? { answer_text: nameAnswer }
                : { selected_district_id: selectedDistrictId },
          ),
        },
      )
      setFeedback(result)
      setView('feedback')
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.answerError'))
    } finally {
      setSubmitting(false)
    }
  }

  function findDistrict(value: string) {
    const normalized = value.trim().toLocaleLowerCase('de')
    return districts.find(
      (district) => district.name.toLocaleLowerCase('de') === normalized,
    )
  }

  function handleAnswerChange(value: string) {
    setAnswerText(value)
    setActiveSuggestionIndex(-1)
  }

  function chooseDistrict(district: TrainingDistrict) {
    setAnswerText(district.name)
    setActiveSuggestionIndex(-1)
    void submitAnswer(false, district.name)
  }

  function selectedSuggestion() {
    return suggestions.length === 1
      ? suggestions[0]
      : suggestions[activeSuggestionIndex] ?? findDistrict(answerText)
  }

  function handleAnswerKeyDown(event: KeyboardEvent<HTMLInputElement>) {
    if (event.key === 'ArrowDown' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (current + 1) % suggestions.length)
      return
    }
    if (event.key === 'ArrowUp' && suggestions.length > 0) {
      event.preventDefault()
      setActiveSuggestionIndex((current) => (
        current <= 0 ? suggestions.length - 1 : current - 1
      ))
      return
    }
    if (event.key === 'Escape') {
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      return
    }
    if (event.key !== 'Enter') return

    event.preventDefault()
    const district = selectedSuggestion()
    if (district) {
      chooseDistrict(district)
      return
    }
    setError(t('training.chooseSuggestions'))
  }

  /** Grade only a selected or exactly matched Name It answer. */
  function handleNameSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const district = selectedSuggestion()
    if (district) {
      chooseDistrict(district)
      return
    }
    setError(t('training.chooseList'))
  }

  /** Acknowledge feedback and request the next queued question. */
  async function nextQuestion() {
    if (!question || submitting) return
    setSubmitting(true)
    setError(null)
    try {
      const next = await apiFetch<TrainingQuestion>(
        `/api/training/sessions/${question.session_id}/next`,
        { method: 'POST' },
      )
      setQuestion(next)
      setFeedback(null)
      setAnswerText('')
      setActiveSuggestionIndex(-1)
      setSelectedDistrictId(null)
      setView('question')
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.nextError'))
    } finally {
      setSubmitting(false)
    }
  }

  /** Stop the active session and display its server-calculated summary. */
  async function stopSession(confirmStop = true) {
    if (!question || submitting) return
    if (confirmStop && view === 'question' && !window.confirm(t('training.stopConfirm'))) return
    setSubmitting(true)
    try {
      const result = await apiFetch<SessionSummary>(
        `/api/training/sessions/${question.session_id}/stop`,
        { method: 'POST' },
      )
      setSummary(result)
      setQuestion(null)
      setFeedback(null)
      setView('summary')
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.stopError'))
    } finally {
      setSubmitting(false)
    }
  }

  /** Return Home without accidentally grading the active question. */
  async function goHome() {
    if (question && view === 'question') {
      if (!window.confirm(t('training.homeConfirm'))) return
      await stopSession(false)
    } else if (question) {
      await stopSession(false)
    }
    onHome()
  }

  /** Change exercise mode only after the current answer has been resolved. */
  async function changeDirection(nextDirection: Direction) {
    if (nextDirection === direction || view === 'question') return
    if (question) await stopSession(false)
    setDirection(nextDirection)
    setView('setup')
    setSummary(null)
    setError(null)
  }

  /** Apply Already Known or Shelf to the latest graded card. */
  async function manageCurrentCard(action: 'already_known' | 'shelve') {
    if (!feedback || submitting) return
    setSubmitting(true)
    try {
      const progress = await apiFetch<TrainingProgress>(
        `/api/training/cards/${direction}/${feedback.answer.district_id}`,
        { method: 'POST', body: JSON.stringify({ action }) },
      )
      if (bootstrap) setBootstrap({ ...bootstrap, progress })
      if (action === 'shelve' && question) {
        try {
          const next = await apiFetch<TrainingQuestion>(
            `/api/training/sessions/${question.session_id}/next`,
            { method: 'POST' },
          )
          setQuestion(next)
          setFeedback(null)
          setAnswerText('')
          setActiveSuggestionIndex(-1)
          setSelectedDistrictId(null)
          setView('question')
        } catch (reason) {
          if (!(reason instanceof ApiError && reason.status === 409)) throw reason
          const result = await apiFetch<SessionSummary>(
            `/api/training/sessions/${question.session_id}/stop`,
            { method: 'POST' },
          )
          setSummary(result)
          setQuestion(null)
          setFeedback(null)
          setView('summary')
        }
      }
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.progressUpdateError'))
    } finally {
      setSubmitting(false)
    }
  }

  /** Toggle one Bezirk while preventing an empty study scope. */
  function toggleBezirk(bezirk: string) {
    setSelectedBezirke((current) => {
      if (!current.includes(bezirk)) return [...current, bezirk]
      if (current.length === 1) return current
      return current.filter((item) => item !== bezirk)
    })
  }

  const districts = bootstrap?.districts ?? []
  const normalizedAnswer = answerText.trim().toLocaleLowerCase('de')
  const suggestions = normalizedAnswer
    ? districts.filter((district) => (
        district.name.toLocaleLowerCase('de').includes(normalizedAnswer)
      ))
    : []
  const sessionAttempts = feedback?.session.attempts ?? question?.attempt_count ?? 0
  const sessionCorrect = feedback?.session.correct ?? question?.correct_count ?? 0
  const masteryByDistrict: Partial<Record<number, MasteryCategory>> = view === 'setup'
    ? Object.fromEntries(
        (bootstrap?.progress.items ?? []).map((item) => [
          item.district_id,
          direction === 'name' ? item.name_category : item.find_category,
        ]),
      )
    : {}

  if (accountStatus === 'loading' || (accountStatus === 'authenticated' && loading)) {
    return (
      <main className="training-shell training-shell--loading">
        <div className="training-loading" role="status">{t('training.loading')}</div>
      </main>
    )
  }

  if (accountStatus === 'anonymous' || authenticationRequired) {
    return (
      <main className="training-shell training-shell--locked">
        <section className="training-locked" aria-labelledby="training-locked-title">
          <span className="training-locked__icon"><LockKeyhole aria-hidden="true" /></span>
          <p className="eyebrow">{t('training.accountTraining')}</p>
          <h1 id="training-locked-title">{t('training.signInTitle')}</h1>
          <p>{t('training.signInHelp')}</p>
          <div className="training-locked__actions">
            <button className="primary-action" type="button" onClick={() => openLogin({ onAuthenticated: () => setLoading(true) })}>
              <span>{t('common.login')}</span><LogIn size={19} aria-hidden="true" />
            </button>
            <button className="secondary-action secondary-action--light" type="button" onClick={() => openRegistration({ onAuthenticated: () => setLoading(true) })}>
              <UserPlus size={18} aria-hidden="true" /><span>{t('common.createAccount')}</span>
            </button>
            <button className="text-action" type="button" onClick={onHome}>{t('common.returnHome')}</button>
          </div>
          {accountError ? <p className="notice notice--error" role="alert">{accountError}</p> : null}
        </section>
      </main>
    )
  }

  return (
    <main className={`training-shell training-shell--${view}`}>
      <TrainingMap
        districts={districts}
        direction={direction}
        targetDistrictId={question?.district_id ?? feedback?.answer.district_id ?? null}
        selectedDistrictId={selectedDistrictId ?? feedback?.selected?.district_id ?? null}
        highlightedBezirke={view === 'setup' ? selectedBezirke : []}
        masteryByDistrict={masteryByDistrict}
        answered={view === 'feedback'}
        correct={feedback?.correct ?? null}
        onSelect={setSelectedDistrictId}
      />

      <header className="training-topbar">
        <button className="icon-action icon-action--surface" type="button" onClick={() => void goHome()} aria-label={t('common.returnModes')} title={t('common.home')}>
          <Home size={19} aria-hidden="true" />
        </button>
        <div className="training-brand"><Layers3 size={18} aria-hidden="true" /><span>{t('training.brand')}</span></div>
        <div className="training-topbar__actions">
          <button className="icon-action icon-action--surface" type="button" onClick={() => onNavigate('/training/progress')} aria-label={t('training.viewProgress')} title={t('training.progressTitle')}>
            <BarChart3 size={19} aria-hidden="true" />
          </button>
          <button className="icon-action icon-action--surface" type="button" disabled={signingOut} onClick={() => void signOut()} aria-label={t('common.logout')} title={t('common.logout')}>
            <LogOut size={19} aria-hidden="true" />
          </button>
        </div>
      </header>

      <aside className="training-panel" aria-live="polite">
        <div className="direction-switch" aria-label={t('training.exercise')}>
          <button type="button" className={direction === 'name' ? 'is-active' : ''} disabled={view === 'question'} onClick={() => void changeDirection('name')}>
            <Search size={16} aria-hidden="true" /> {t('training.nameIt')}
          </button>
          <button type="button" className={direction === 'find' ? 'is-active' : ''} disabled={view === 'question'} onClick={() => void changeDirection('find')}>
            <SquareMousePointer size={16} aria-hidden="true" /> {t('training.findIt')}
          </button>
        </div>

        {accountError || error ? <p className="notice notice--error" role="alert">{accountError ?? error}</p> : null}

        {view === 'setup' ? (
          <section className="training-setup" aria-labelledby="training-title">
            <p className="eyebrow">{t('training.spacedRepetition')}</p>
            <h1 id="training-title">{t(direction === 'name' ? 'training.nameHamburg' : 'training.findHamburg')}</h1>
            <p>
              {direction === 'name'
                ? t('training.nameHelp')
                : t('training.findHelp')}
            </p>
            <div className="training-metrics" aria-label={t('training.currentProgress')}>
              <div><strong>{bootstrap?.progress.directions[direction].due ?? 0}</strong><span>{t('training.dueNow')}</span></div>
              <div><strong>{bootstrap?.progress.directions[direction].practiced ?? 0}</strong><span>{t('training.practiced')}</span></div>
              <div><strong>{formatPercent(bootstrap?.progress.directions[direction].accuracy ?? 0)}</strong><span>{t('training.accuracy')}</span></div>
            </div>
            <fieldset className="scope-picker">
              <legend>{t('training.studying')}</legend>
              <button type="button" onClick={() => setSelectedBezirke(bootstrap?.bezirke ?? [])}>{t('training.allHamburg')}</button>
              <div>
                {bootstrap?.bezirke.map((bezirk) => (
                  <label key={bezirk}>
                    <input type="checkbox" checked={selectedBezirke.includes(bezirk)} onChange={() => toggleBezirk(bezirk)} />
                    <span>{bezirk}</span>
                  </label>
                ))}
              </div>
            </fieldset>
            <button className="primary-action" type="button" disabled={submitting} onClick={() => void startSession()}>
              <span>{t(submitting ? 'training.preparing' : 'training.start')}</span><ArrowRight size={20} aria-hidden="true" />
            </button>
          </section>
        ) : null}

        {view === 'question' && question ? (
          <section className="training-question" aria-label={direction === 'name' ? t('training.nameDistrict') : t('training.findDistrict', { district: question.prompt_name })}>
            <p className="eyebrow">{t('training.question', { number: sessionAttempts + 1 })}</p>
            {direction === 'name' ? (
              <>
                <form className="training-answer-form" onSubmit={handleNameSubmit}>
                  <label htmlFor="training-answer">{t('common.districtName')}</label>
                  <div className="guess-control">
                    <input
                      ref={inputRef}
                      id="training-answer"
                      value={answerText}
                      onChange={(event) => handleAnswerChange(event.target.value)}
                      onKeyDown={handleAnswerKeyDown}
                      autoComplete="off"
                      placeholder={t('common.typeName')}
                      role="combobox"
                      aria-autocomplete="list"
                      aria-controls="training-suggestions"
                      aria-expanded={suggestions.length > 0}
                      aria-activedescendant={activeSuggestionIndex >= 0 ? `training-suggestion-${suggestions[activeSuggestionIndex]?.id}` : undefined}
                      readOnly={submitting}
                    />
                  </div>
                  {suggestions.length > 0 ? (
                    <div className="training-suggestions" id="training-suggestions" role="listbox">
                      {suggestions.map((district, index) => (
                        <button
                          key={district.id}
                          id={`training-suggestion-${district.id}`}
                          type="button"
                          role="option"
                          aria-selected={index === activeSuggestionIndex}
                          className={index === activeSuggestionIndex ? 'is-active' : ''}
                          onMouseDown={(event) => event.preventDefault()}
                          onClick={() => chooseDistrict(district)}
                        >
                          {district.name}
                        </button>
                      ))}
                    </div>
                  ) : null}
                </form>
              </>
            ) : (
              <>
                <h1>{t('training.where', { district: question.prompt_name })}</h1>
                <p>{t('training.selectBoundary')}</p>
                <div className="selected-answer" aria-live="polite">
                  {selectedDistrictId !== null ? <><span>{t('common.selected')}</span><strong>{t('training.areaSelected')}</strong></> : <span>{t('training.noneSelected')}</span>}
                </div>
                <button className="primary-action" type="button" disabled={selectedDistrictId === null || submitting} onClick={() => void submitAnswer()}>
                  <span>{t('training.confirmLocation')}</span><Check size={19} aria-hidden="true" />
                </button>
              </>
            )}
            <div className="question-actions">
              <button type="button" onClick={() => void submitAnswer(true)} disabled={submitting}>{t('training.dontKnow')}</button>
              <button type="button" onClick={() => void stopSession()} disabled={submitting}>{t('training.stopNow')}</button>
            </div>
          </section>
        ) : null}

        {view === 'feedback' && feedback ? (
          <section className="training-feedback" aria-labelledby="feedback-title">
            <span className={feedback.correct ? 'feedback-icon feedback-icon--correct' : 'feedback-icon feedback-icon--wrong'}>
              {feedback.correct ? <Check aria-hidden="true" /> : <X aria-hidden="true" />}
            </span>
            <p className="eyebrow">{t(feedback.correct ? 'training.correct' : feedback.outcome === 'dont_know' ? 'training.noted' : 'training.notQuite')}</p>
            <h1 id="feedback-title">{feedback.answer.name}</h1>
            <p>{feedback.answer.bezirk}</p>
            {!feedback.correct && feedback.selected ? <p className="feedback-comparison"><Trans i18nKey="training.youSelected" values={{ district: feedback.selected.name }} components={{ strong: <strong /> }} /></p> : null}
            <div className="session-line">
              <span>{t('training.correctCount', { correct: sessionCorrect, attempts: sessionAttempts })}</span>
              <span>{accuracyLabel(sessionCorrect, sessionAttempts)}</span>
            </div>
            <button ref={nextButtonRef} className="primary-action" type="button" disabled={submitting} onClick={() => void nextQuestion()}>
              <span>{t('common.next')}</span><ChevronRight size={20} aria-hidden="true" />
            </button>
            <div className="feedback-actions">
              {feedback.correct ? <button type="button" onClick={() => void manageCurrentCard('already_known')} disabled={submitting}><ShieldCheck size={16} /> {t('training.alreadyKnow')}</button> : null}
              <button type="button" onClick={() => void manageCurrentCard('shelve')} disabled={submitting}>{t('training.shelve')}</button>
              <button type="button" onClick={() => void stopSession(false)} disabled={submitting}>{t('training.stopNow')}</button>
            </div>
          </section>
        ) : null}

        {view === 'summary' && summary ? (
          <section className="training-summary" aria-labelledby="summary-title">
            <p className="eyebrow">{t('training.sessionComplete')}</p>
            <h1 id="summary-title">{t('training.goodStop')}</h1>
            <div className="summary-grid">
              <div><strong>{summary.attempts}</strong><span>{t('training.attempts')}</span></div>
              <div><strong>{formatPercent(summary.accuracy)}</strong><span>{t('training.accuracy')}</span></div>
              <div><strong>{summary.introduced}</strong><span>{t('training.introduced')}</span></div>
              <div><strong>{summary.needs_practice}</strong><span>{t('training.needPractice')}</span></div>
            </div>
            <button className="primary-action" type="button" onClick={() => setView('setup')}><span>{t('training.continue')}</span><RotateCcw size={19} /></button>
            <button className="text-action" type="button" onClick={onHome}>{t('common.returnHome')}</button>
          </section>
        ) : null}
      </aside>
    </main>
  )
}

/** Display signed-in aggregate and per-mode mastery with reset controls. */
export function TrainingProgressPage({ onHome, onNavigate }: TrainingAppProps) {
  const { t } = useTranslation()
  const [progress, setProgress] = useState<TrainingProgress | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)


  /** Load compact Training statistics without downloading map geometry. */
  async function loadProgress() {
    setLoading(true)
    try {
      setProgress(await apiFetch<TrainingProgress>('/api/training/progress'))
      setError(null)
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.progressLoadError'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    let cancelled = false
    apiFetch<TrainingProgress>('/api/training/progress')
      .then((result) => {
        if (!cancelled) setProgress(result)
      })
      .catch((reason: unknown) => {
        if (!cancelled) setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.progressLoadError'))
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })
    return () => {
      cancelled = true
    }
  }, [])

  /** Permanently reset only Training records after explicit confirmation. */
  async function resetProgress() {
    if (!window.confirm(t('training.resetConfirm'))) return
    try {
      await apiFetch<void>('/api/training', { method: 'DELETE' })
      await loadProgress()
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.resetError'))
    }
  }

  /** Restore both shelved direction cards for one Stadtteil when present. */
  async function restoreItem(item: ProgressItem) {
    try {
      let latest = progress
      if (item.name_category === 'shelved') {
        latest = await apiFetch<TrainingProgress>(
          `/api/training/cards/name/${item.district_id}`,
          { method: 'POST', body: JSON.stringify({ action: 'restore' }) },
        )
      }
      if (item.find_category === 'shelved') {
        latest = await apiFetch<TrainingProgress>(
          `/api/training/cards/find/${item.district_id}`,
          { method: 'POST', body: JSON.stringify({ action: 'restore' }) },
        )
      }
      setProgress(latest)
      setError(null)
    } catch (reason) {
      setError(apiErrorMessage(reason, i18n.t.bind(i18n), 'training.restoreError'))
    }
  }

  const categories: Array<{ key: MasteryCategory; label: string }> = [
    { key: 'needs_practice', label: t('training.needsPractice') },
    { key: 'learning', label: t('training.learning') },
    { key: 'familiar', label: t('training.familiar') },
    { key: 'known', label: t('training.known') },
    { key: 'shelved', label: t('training.shelved') },
  ]

  return (
    <main className="progress-page">
      <header className="progress-topbar">
        <button className="icon-action" type="button" onClick={onHome} aria-label={t('common.returnModes')} title={t('common.home')}><Home size={19} /></button>
        <strong>{t('training.progress')}</strong>
        <button className="text-action" type="button" onClick={() => onNavigate('/training')}>{t('training.train')}</button>
      </header>
      <div className="progress-content">
        <p className="eyebrow">{t('training.yourHamburg')}</p>
        <h1>{t('training.rememberingProgress')}</h1>
        {loading ? <p role="status">{t('training.loadingProgress')}</p> : null}
        {error ? <p className="notice notice--error" role="alert">{error}</p> : null}
        {progress ? (
          <>
            <section className="progress-overview" aria-label={t('training.overallProgress')}>
              <div><strong>{progress.practiced}<small>/104</small></strong><span>{t('training.practiced')}</span></div>
              <div><strong>{formatPercent(progress.accuracy)}</strong><span>{t('training.recallAccuracy')}</span></div>
              <div><strong>{progress.fully_known}</strong><span>{t('training.knownBoth')}</span></div>
            </section>
            <section className="mode-breakdown" aria-labelledby="mode-progress-title">
              <h2 id="mode-progress-title">{t('training.byExercise')}</h2>
              {(['name', 'find'] as const).map((mode) => (
                <div key={mode}>
                  <span>{t(mode === 'name' ? 'training.nameIt' : 'training.findIt')}</span>
                  <strong>{formatPercent(progress.directions[mode].accuracy)}</strong>
                  <small>{t('training.attemptsDue', { attempts: progress.directions[mode].attempts, due: progress.directions[mode].due })}</small>
                </div>
              ))}
            </section>
            <section className="mastery-list" aria-labelledby="mastery-title">
              <h2 id="mastery-title">{t('training.districts')}</h2>
              {categories.map((category) => {
                const items = progress.items.filter((item) => item.name_category === category.key || item.find_category === category.key)
                return (
                  <details key={category.key} open={category.key === 'needs_practice'}>
                    <summary>{category.label}<span>{items.length}</span></summary>
                    {items.length > 0 ? (
                      <ul>{items.map((item) => (
                        <li key={item.district_id}>
                          <strong>{item.name}</strong><span>{item.bezirk}</span>
                          {category.key === 'shelved' ? <button type="button" onClick={() => void restoreItem(item)}>{t('training.restore')}</button> : null}
                        </li>
                      ))}</ul>
                    ) : <p>{t('training.empty')}</p>}
                  </details>
                )
              })}
            </section>
            <section className="reset-training" aria-labelledby="reset-title">
              <h2 id="reset-title">{t('training.reset')}</h2>
              <p>{t('training.resetHelp')}</p>
              <button type="button" onClick={() => void resetProgress()}><RotateCcw size={17} /> {t('training.resetAll')}</button>
            </section>
          </>
        ) : null}
      </div>
    </main>
  )
}
