// Generated by GitHub Copilot - Aug-28-2026
import { useEffect, useRef } from 'react'
import type { GeoJsonObject } from 'geojson'
import L from 'leaflet'
import { GeoJSON, MapContainer, TileLayer, useMap } from 'react-leaflet'

export type TrainingDistrict = {
  id: number
  name: string
  bezirk: string
  boundary: GeoJsonObject
}

type TrainingMapProps = {
  districts: TrainingDistrict[]
  direction: 'name' | 'find'
  targetDistrictId: number | null
  selectedDistrictId: number | null
  answered: boolean
  correct: boolean | null
  onSelect: (districtId: number) => void
}

const HAMBURG_BOUNDS = L.latLngBounds(
  [53.39, 9.72],
  [53.75, 10.32],
)

/** Keep Name It contextual and Find It city-wide until feedback is shown. */
function TrainingViewport({
  districts,
  direction,
  targetDistrictId,
  selectedDistrictId,
  answered,
}: Omit<TrainingMapProps, 'correct' | 'onSelect'>) {
  const map = useMap()

  useEffect(() => {
    const target = districts.find((district) => district.id === targetDistrictId)
    const selected = districts.find((district) => district.id === selectedDistrictId)

    function fitViewport() {
      map.invalidateSize({ animate: false })
      const desktopPanelWidth = map.getSize().x > 760 ? 430 : 0
      const paddingTopLeft: L.PointExpression = [desktopPanelWidth + 36, 36]
      const paddingBottomRight: L.PointExpression = [36, 36]

      if (answered && target) {
        const feedbackBounds = L.geoJSON(target.boundary).getBounds()
        if (selected) feedbackBounds.extend(L.geoJSON(selected.boundary).getBounds())
        map.fitBounds(feedbackBounds, {
          paddingTopLeft,
          paddingBottomRight,
          maxZoom: 13,
        })
        return
      }
      if (direction === 'name' && target) {
        map.fitBounds(L.geoJSON(target.boundary).getBounds(), {
          paddingTopLeft,
          paddingBottomRight,
          maxZoom: 12,
        })
        return
      }
      map.fitBounds(HAMBURG_BOUNDS, { padding: [24, 24] })
    }

    fitViewport()
    map.on('resize', fitViewport)
    return () => {
      map.off('resize', fitViewport)
    }
  }, [answered, direction, districts, map, selectedDistrictId, targetDistrictId])

  return null
}

/** Render one boundary with pointer and keyboard selection parity. */
function TrainingBoundary({
  district,
  style,
  selectable,
  selected,
  onSelect,
}: {
  district: TrainingDistrict
  style: L.PathOptions
  selectable: boolean
  selected: boolean
  onSelect: (districtId: number) => void
}) {
  const layerRef = useRef<L.GeoJSON | null>(null)

  useEffect(() => {
    const cleanups: Array<() => void> = []
    layerRef.current?.eachLayer((layer) => {
      if (!(layer instanceof L.Path)) return
      const element = layer.getElement()
      if (!element) return
      element.setAttribute('role', selectable ? 'button' : 'img')
      element.setAttribute('tabindex', selectable ? '0' : '-1')
      element.setAttribute(
        'aria-label',
        selectable
          ? `Selectable Hamburg map area ${district.id}${selected ? ', selected' : ''}`
          : `${district.name}, ${district.bezirk}`,
      )
      const handleKeyDown = (event: Event) => {
        if (
          !(event instanceof KeyboardEvent)
          || !selectable
          || (event.key !== 'Enter' && event.key !== ' ')
        ) return
        event.preventDefault()
        onSelect(district.id)
      }
      element.addEventListener('keydown', handleKeyDown)
      cleanups.push(() => element.removeEventListener('keydown', handleKeyDown))
    })
    return () => cleanups.forEach((cleanup) => cleanup())
  }, [district, onSelect, selectable, selected])

  return (
    <GeoJSON
      ref={layerRef}
      data={district.boundary}
      style={style}
      eventHandlers={{
        click: () => {
          if (selectable) onSelect(district.id)
        },
      }}
    />
  )
}

/** Display the complete non-satellite Hamburg Training map. */
export function TrainingMap({
  districts,
  direction,
  targetDistrictId,
  selectedDistrictId,
  answered,
  correct,
  onSelect,
}: TrainingMapProps) {
  function districtStyle(districtId: number): L.PathOptions {
    const isTarget = districtId === targetDistrictId
    const isSelected = districtId === selectedDistrictId
    if (answered && isTarget) {
      return {
        color: '#087f5b',
        fillColor: '#34b27b',
        fillOpacity: 0.52,
        opacity: 1,
        weight: 3,
      }
    }
    if (answered && isSelected && !correct) {
      return {
        color: '#b52f36',
        fillColor: '#d9484f',
        fillOpacity: 0.44,
        opacity: 1,
        weight: 3,
      }
    }
    if (!answered && direction === 'name' && isTarget) {
      return {
        color: '#075f47',
        fillColor: '#18a573',
        fillOpacity: 0.55,
        opacity: 1,
        weight: 3,
      }
    }
    if (!answered && direction === 'find' && isSelected) {
      return {
        color: '#155e75',
        fillColor: '#38bdf8',
        fillOpacity: 0.38,
        opacity: 1,
        weight: 3,
      }
    }
    return {
      color: '#64756e',
      fillColor: '#dce4df',
      fillOpacity: 0.2,
      opacity: 0.78,
      weight: 1.25,
    }
  }

  return (
    <div className="map-surface training-map" aria-label="Interactive map of Hamburg Stadtteile">
      <MapContainer
        center={[53.55, 10]}
        zoom={10}
        minZoom={9}
        maxZoom={16}
        zoomControl
        attributionControl
      >
        <TileLayer
          attribution="Tiles &copy; Esri"
          url="https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/World_Light_Gray_Base/MapServer/tile/{z}/{y}/{x}"
        />
        <TrainingViewport
          districts={districts}
          direction={direction}
          targetDistrictId={targetDistrictId}
          selectedDistrictId={selectedDistrictId}
          answered={answered}
        />
        {districts.map((district) => (
          <TrainingBoundary
            key={district.id}
            district={district}
            style={districtStyle(district.id)}
            selectable={direction === 'find' && !answered}
            selected={district.id === selectedDistrictId}
            onSelect={onSelect}
          />
        ))}
      </MapContainer>
    </div>
  )
}
