# Generated by GitHub Copilot - Aug-28-2026
"""Create the Account table.

Revision ID: 0001_create_account
Revises:
Create Date: 2026-08-28
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_create_account"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create Accounts and enforce case-insensitive username uniqueness."""
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=32), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "uq_account_username_lower",
        "account",
        [sa.text("lower(username)")],
        unique=True,
    )


def downgrade() -> None:
    """Remove the Account table and its indexes."""
    op.drop_index("uq_account_username_lower", table_name="account")
    op.drop_table("account")