# Generated by GitHub Copilot - Aug-28-2026
"""Create persistent Account Daily Challenge Games and Guesses.

Revision ID: 0002_create_daily_games
Revises: 0001_create_account
Create Date: 2026-08-28
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002_create_daily_games"
down_revision: str | None = "0001_create_account"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create Account-scoped Daily Challenge and Guess storage."""
    op.create_table(
        "game_daily_districts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("challenge_date", sa.Date(), nullable=False),
        sa.Column("budget_remaining", sa.Integer(), nullable=False),
        sa.Column("solved_pin_indices", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "budget_remaining BETWEEN 0 AND 10", name="ck_game_budget_range"
        ),
        sa.CheckConstraint(
            "status IN ('in_progress', 'finished')", name="ck_game_status"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "challenge_date",
            name="uq_game_account_challenge_date",
        ),
    )
    op.create_table(
        "guess",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("game_id", sa.Integer(), nullable=False),
        sa.Column("guessed_district_id", sa.Integer(), nullable=False),
        sa.Column("was_correct", sa.Boolean(), nullable=False),
        sa.Column("solved_pin_index", sa.Integer(), nullable=True),
        sa.Column("distance_km", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"], ["game_daily_districts.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Remove persistent Account Daily Challenge storage."""
    op.drop_table("guess")
    op.drop_table("game_daily_districts")