# Generated by GitHub Copilot - Aug-28-2026
"""Create Account Training cards, attempts, and sessions.

Revision ID: 0003_create_training
Revises: 0002_create_daily_games
Create Date: 2026-08-28
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_create_training"
down_revision: str | None = "0002_create_daily_games"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create server-authoritative Training persistence."""
    op.create_table(
        "training_card",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("stage", sa.Integer(), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("shelved", sa.Boolean(), nullable=False),
        sa.Column("already_known", sa.Boolean(), nullable=False),
        sa.Column("last_was_correct", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint("stage BETWEEN 0 AND 6", name="ck_training_card_stage"),
        sa.CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_card_direction"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "account_id",
            "district_id",
            "direction",
            name="uq_training_card_account_district_direction",
        ),
    )
    op.create_index(
        "ix_training_card_account_due",
        "training_card",
        ["account_id", "due_at"],
    )
    op.create_table(
        "training_attempt",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("district_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("outcome", sa.String(length=16), nullable=False),
        sa.Column("answered_district_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_attempt_direction"
        ),
        sa.CheckConstraint(
            "outcome IN ('correct', 'incorrect', 'dont_know')",
            name="ck_training_attempt_outcome",
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_training_attempt_account_created",
        "training_attempt",
        ["account_id", "created_at"],
    )
    op.create_table(
        "training_session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("selected_bezirke", sa.JSON(), nullable=False),
        sa.Column("queue_district_ids", sa.JSON(), nullable=False),
        sa.Column("recent_district_ids", sa.JSON(), nullable=False),
        sa.Column("active_district_id", sa.Integer(), nullable=True),
        sa.Column("last_answer_district_id", sa.Integer(), nullable=True),
        sa.Column("last_answer_correct", sa.Boolean(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("introduced_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "direction IN ('name', 'find')", name="ck_training_session_direction"
        ),
        sa.CheckConstraint(
            "status IN ('active', 'stopped')", name="ck_training_session_status"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )


def downgrade() -> None:
    """Remove Account Training persistence."""
    op.drop_table("training_session")
    op.drop_index(
        "ix_training_attempt_account_created", table_name="training_attempt"
    )
    op.drop_table("training_attempt")
    op.drop_index("ix_training_card_account_due", table_name="training_card")
    op.drop_table("training_card")